import Link from "next/link";
import { redirect } from "next/navigation";
import { getAppContext } from "@/lib/auth/context";
import { getContractEditorDetails } from "@/lib/contracts/queries";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { AppShell } from "@/components/layout/app-shell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { generateContractDocumentAction } from "./actions";

type ContractDocumentRow = { id: string; contract_version_id: string; status: string; file_name: string; file_size: number | null; page_count: number | null; generated_at: string; metadata: Record<string, unknown> | null };

export default async function ContractDocumentPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ erro?: string; gerado?: string }> }) {
  const { id }=await params; const query=await searchParams; const context=await getAppContext(); if(context.status!=="ready"||!context.member||!context.lawFirm)redirect("/entrar");
  const editor=await getContractEditorDetails(id); if(!editor)redirect(`/contratos/${id}`); const supabase=await getSupabaseServerClient(); const docs: { data: ContractDocumentRow[] | null }=supabase?await (supabase as any).from("contract_documents").select("id,contract_version_id,status,file_name,file_size,page_count,generated_at,metadata").eq("law_firm_id",context.lawFirm.id).eq("contract_id",id).order("generated_at",{ascending:false}):{data:[]}; const active=editor.versions.find((v)=>v.isActive)??editor.versions.at(-1); const canGenerate=["proprietario","administrador","advogado"].includes(context.member.role);
  return <AppShell memberName={context.member.name}><div className="mx-auto max-w-5xl space-y-6"><Link href={`/contratos/${id}`} className="text-sm text-muted-foreground underline">Voltar para contrato</Link><Card><CardHeader><CardTitle>Documento contratual</CardTitle></CardHeader><CardContent className="space-y-5"><p className="text-sm text-muted-foreground">Prévia baseada na versão ativa. A geração cria um PDF interno imutável.</p>{query.erro?<p role="alert" aria-live="polite" className="text-sm text-destructive">Não foi possível gerar o documento ({query.erro}).</p>:null}{query.gerado?<p role="status" aria-live="polite" className="text-sm text-emerald-600">Documento gerado com sucesso.</p>:null}<div className="rounded-lg border bg-muted/30 p-6"><h1 className="text-center text-xl font-semibold">{active?.title??editor.contract.title}</h1><p className="mt-4 whitespace-pre-wrap text-sm">{active?.content||"Prévia contratual composta pelas partes, cláusulas e termos comerciais da versão selecionada."}</p>{active?.clauses.map((clause)=><section key={String(clause.id)} className="mt-5"><h2 className="font-semibold">{String(clause.title)}</h2><p className="mt-1 whitespace-pre-wrap text-sm text-muted-foreground">{String(clause.content??"")}</p></section>)}</div>{canGenerate&&active?<form action={generateContractDocumentAction}><input type="hidden" name="contractId" value={id}/><input type="hidden" name="versionId" value={active.id}/><input type="hidden" name="idempotencyKey" value={`document-${id}-${active.id}`}/><button className="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground" type="submit">Gerar PDF da versão ativa</button></form>:<p className="text-sm text-muted-foreground">Seu perfil não pode gerar documentos.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Documentos gerados</CardTitle></CardHeader><CardContent><ul className="space-y-3">{(docs.data??[]).map((doc)=>{const stale=doc.contract_version_id!==active?.id;return <li key={doc.id} className="flex flex-wrap items-center justify-between gap-3 border-b pb-3 text-sm"><span>v{String((doc.metadata as Record<string,unknown>)?.versionNumber??"-")} · {doc.file_name} · {doc.status}{stale?<strong className="text-amber-600"> desatualizado</strong>:null}</span>{doc.status==="completed"?<a className="underline" href={`/api/contratos/${id}/documentos/${doc.id}`}>Baixar</a>:null}</li>})}{!docs.data?.length?<li className="text-sm text-muted-foreground">Nenhum documento gerado.</li>:null}</ul></CardContent></Card></div></AppShell>;
}
