export type SystemDocumentTemplate = { id: string; name: string; description: string; category: string; content: string };

export const systemDocumentTemplates: SystemDocumentTemplate[] = [
  { id: "system-procuracao", name: "Procuração", description: "Procuração para representação judicial e extrajudicial.", category: "procuracao", content: "PROCURAÇÃO\n\nOUTORGANTE: {{client.name}}, CPF/CNPJ {{client.document}}.\n\nOUTORGADO: {{firm.name}}.\n\nPelo presente instrumento, o OUTORGANTE constitui o OUTORGADO como seu bastante procurador para representá-lo nos atos necessários relacionados ao processo {{case.number}}.\n\n{{today}}" },
  { id: "system-honorarios", name: "Contrato de Honorários", description: "Modelo inicial de contrato de prestação de serviços advocatícios.", category: "contrato", content: "CONTRATO DE HONORÁRIOS ADVOCATÍCIOS\n\nCONTRATANTE: {{client.name}}, CPF/CNPJ {{client.document}}.\nCONTRATADO: {{firm.name}}.\n\nObjeto: {{contract.description}}.\nHonorários: {{contract.value}}.\n\n{{today}}" },
  { id: "system-notificacao", name: "Notificação Extrajudicial", description: "Comunicação formal para constituir a parte em mora ou solicitar providência.", category: "notificacao", content: "NOTIFICAÇÃO EXTRAJUDICIAL\n\nNotificante: {{client.name}}.\nNotificado: {{case.opposing_party}}.\n\nAssunto: {{case.title}}.\n\nFica o(a) notificado(a) para apresentar manifestação no prazo aplicável.\n\n{{today}}" },
  { id: "system-recebimento", name: "Recibo de Pagamento", description: "Recibo simples para honorários ou despesas reembolsáveis.", category: "financeiro", content: "RECIBO\n\nRecebi de {{client.name}} a quantia de {{contract.value}}, referente a {{contract.description}}.\n\n{{today}}\n\n{{firm.name}}" },
  { id: "system-relatorio", name: "Relatório ao Cliente", description: "Atualização objetiva sobre o andamento de processo.", category: "relatorio", content: "RELATÓRIO DE ANDAMENTO\n\nCliente: {{client.name}}\nProcesso: {{case.number}}\nTribunal: {{case.court}}\n\nSituação atual:\n[Descreva os principais fatos e próximos passos.]\n\n{{today}}\n{{firm.name}}" },
  { id: "system-declaracao", name: "Declaração de Hipossuficiência", description: "Declaração inicial para pedido de gratuidade da justiça.", category: "declaracao", content: "DECLARAÇÃO DE HIPOSSUFICIÊNCIA\n\nEu, {{client.name}}, CPF/CNPJ {{client.document}}, declaro, sob as penas da lei, não possuir recursos suficientes para arcar com custas e despesas processuais sem prejuízo do meu sustento.\n\n{{today}}" },
  { id: "system-peticao", name: "Petição de Juntada", description: "Modelo de petição simples para juntada de documentos.", category: "peticao", content: "EXCELENTÍSSIMO(A) SENHOR(A) DOUTOR(A) JUIZ(A)\n\nProcesso nº {{case.number}}\n\n{{client.name}}, por seu advogado, vem requerer a juntada dos documentos anexos.\n\nTermos em que, pede deferimento.\n\n{{today}}\n{{firm.name}}" },
  { id: "system-encerramento", name: "Termo de Encerramento", description: "Formaliza a conclusão do atendimento ou contrato jurídico.", category: "geral", content: "TERMO DE ENCERRAMENTO\n\nCliente: {{client.name}}\nAssunto: {{case.title}}\n\nAs partes registram o encerramento dos serviços descritos acima, sem prejuízo das obrigações pendentes previstas em contrato.\n\n{{today}}\n{{firm.name}}" },
];
