import { createHash, randomUUID } from "node:crypto";
import { PDFDocument } from "pdf-lib";
import { getSignatureProviderAdapter } from "./delivery/registry";
import type { Db } from "./repository";
import { SignatureEnvelopeError } from "./errors";

const allowedRoles = new Set(["proprietario", "administrador", "advogado"]);
const sha = (bytes: Uint8Array | string) => createHash("sha256").update(bytes).digest("hex");
const safe = (value: unknown) => String((value as { code?: string })?.code ?? (value as Error)?.message ?? "SIGNATURE_ARTIFACT_RETRIEVAL_FAILED").replace(/[^A-Z0-9_.:-]/gi, "_").slice(0, 120);
const inputHash = (envelope: Record<string, unknown>, delivery: Record<string, unknown>) => sha(JSON.stringify({ envelope: envelope.id, document: envelope.contract_document_id, source: envelope.document_hash, provider: delivery.provider, providerEnvelope: delivery.provider_envelope_id }));
const assertPdf = async (bytes: Uint8Array, expectedHash?: string) => { if (bytes.length < 8 || new TextDecoder().decode(bytes.slice(0, 5)) !== "%PDF-") throw new SignatureEnvelopeError("SIGNATURE_ARTIFACT_INVALID_PDF"); const pdf = await PDFDocument.load(bytes); if (!pdf.getPageCount()) throw new SignatureEnvelopeError("SIGNATURE_ARTIFACT_INVALID_PDF"); const hash = sha(bytes); if (expectedHash && hash !== expectedHash) throw new SignatureEnvelopeError("SIGNATURE_ARTIFACT_PROVIDER_HASH_MISMATCH"); return { hash, pageCount: pdf.getPageCount() }; };
const event = async (client: Db, lawFirmId: string, envelopeId: string, actor: string, type: string, key: string, metadata: Record<string, unknown>) => { const result = await client.from("contract_signature_events").insert({ law_firm_id: lawFirmId, envelope_id: envelopeId, event_type: type, actor_user_id: actor, deduplication_key: key, safe_metadata_json: metadata }); if (result.error && !String(result.error.code).includes("23505") && type !== "signature_artifacts_retrieval_requested") throw new SignatureEnvelopeError("SIGNATURE_ARTIFACT_EVENT_FAILED"); };

export type ArtifactContext = { lawFirmId: string; userId: string; role: string };
export async function retrieveCompletedSignatureArtifacts(client: Db, context: ArtifactContext, envelopeId: string, idempotencyKey: string) {
  if (!allowedRoles.has(context.role) || !idempotencyKey.trim()) throw new SignatureEnvelopeError(!allowedRoles.has(context.role) ? "SIGNATURE_PERMISSION_DENIED" : "SIGNATURE_IDEMPOTENCY_REQUIRED");
  const envelopeResult = await client.from("contract_signature_envelopes").select("*").eq("id", envelopeId).eq("law_firm_id", context.lawFirmId).maybeSingle(); if (envelopeResult.error || !envelopeResult.data) throw new SignatureEnvelopeError("SIGNATURE_NOT_FOUND");
  const envelope = envelopeResult.data as Record<string, unknown>; if (envelope.status !== "signed") throw new SignatureEnvelopeError("SIGNATURE_ARTIFACTS_REQUIRE_SIGNED");
  const deliveryResult = await client.from("contract_signature_provider_deliveries").select("*").eq("envelope_id", envelopeId).eq("law_firm_id", context.lawFirmId).eq("provider", "internal_sandbox").maybeSingle(); if (deliveryResult.error || !deliveryResult.data?.provider_envelope_id || deliveryResult.data.status !== "signed") throw new SignatureEnvelopeError("SIGNATURE_DELIVERY_INVALID");
  const delivery = deliveryResult.data as Record<string, unknown>; const hash = inputHash(envelope, delivery); const existing = await client.from("contract_signature_artifact_operations").select("*").eq("law_firm_id", context.lawFirmId).eq("envelope_id", envelopeId).eq("operation_type", "retrieval").eq("idempotency_key", idempotencyKey).maybeSingle(); if (existing.data) { if (existing.data.input_hash !== hash) throw new SignatureEnvelopeError("SIGNATURE_IDEMPOTENCY_CONFLICT"); if (existing.data.status === "completed") return listSignatureArtifacts(client, context.lawFirmId, envelopeId); }
  const operation = await client.from("contract_signature_artifact_operations").insert({ law_firm_id: context.lawFirmId, contract_id: envelope.contract_id, envelope_id: envelopeId, operation_type: "retrieval", status: "processing", idempotency_key: idempotencyKey, input_hash: hash }).select("id").maybeSingle(); if (operation.error && !String(operation.error.code).includes("23505")) throw new SignatureEnvelopeError("SIGNATURE_ARTIFACT_OPERATION_FAILED"); if (operation.error) return listSignatureArtifacts(client, context.lawFirmId, envelopeId);
  await event(client, context.lawFirmId, envelopeId, context.userId, "signature_artifacts_retrieval_requested", `artifact-retrieval:${envelopeId}:${idempotencyKey}`, {});
  const sourceResult = await client.from("contract_documents").select("file_hash,title,storage_bucket,storage_path").eq("id", envelope.contract_document_id).eq("law_firm_id", context.lawFirmId).maybeSingle(); const source = { contractId: envelope.contract_id, contractDocumentId: envelope.contract_document_id, contractVersionId: envelope.contract_version_id, status: "completed", documentHash: sourceResult.data?.file_hash ?? envelope.document_hash, fileSize: Number(envelope.document_file_size), pageCount: Number(envelope.document_page_count), title: String(envelope.title), ...(sourceResult.data?.title ? { title: sourceResult.data.title } : {}) } as never;
  const signersResult = await client.from("contract_signature_signers").select("id,signer_type,role,name,email,signing_order,requires_identity_verification").eq("envelope_id", envelopeId).eq("law_firm_id", context.lawFirmId).neq("status", "removed").order("signing_order"); const signers = (signersResult.data ?? []).map((s: Record<string, unknown>) => ({ ...s, signerType: s.signer_type, signingOrder: s.signing_order, requiresIdentityVerification: s.requires_identity_verification }));
  try { const result = await getSignatureProviderAdapter("internal_sandbox").getCompletedArtifacts({ provider: "internal_sandbox", providerEnvelopeId: String(delivery.provider_envelope_id), source, signers }); const files = [result.signedDocument, result.completionCertificate, result.signersEvidence]; const inserted: Record<string, unknown>[] = []; for (const file of files) { const artifactInsert = await client.from("contract_signature_artifacts").insert({ law_firm_id: context.lawFirmId, contract_id: envelope.contract_id, envelope_id: envelopeId, delivery_id: delivery.id, contract_document_id: envelope.contract_document_id, provider: "internal_sandbox", provider_envelope_id: result.providerEnvelopeId, artifact_type: file.type, status: "retrieving", storage_bucket: "documents", storage_path: `contracts/${context.lawFirmId}/${envelope.contract_id}/signatures/${envelopeId}/${randomUUID()}/${file.fileName}`, mime_type: file.mimeType, file_name: file.fileName, provider_hash: file.providerHash, source_document_hash: envelope.document_hash }).select("*").single(); if (artifactInsert.error || !artifactInsert.data) throw new SignatureEnvelopeError("SIGNATURE_ARTIFACT_CREATE_FAILED"); const artifactRow = artifactInsert.data; const storagePath = artifactRow.storage_path as string; const upload = await (client as unknown as { storage: { from: (bucket: string) => { upload: (path: string, bytes: Uint8Array, opts: Record<string, unknown>) => Promise<{ error: Error | null }> } } }).storage.from("documents").upload(storagePath, file.bytes, { contentType: file.mimeType, upsert: false }); if (upload.error) throw new SignatureEnvelopeError("SIGNATURE_ARTIFACT_STORAGE_FAILED"); const validation = await assertPdf(file.bytes, file.providerHash); const updated = await client.from("contract_signature_artifacts").update({ status: "completed", file_hash: validation.hash, file_size: file.fileSize, page_count: validation.pageCount, retrieved_at: result.completedAt, validated_at: result.completedAt, evidence_snapshot_json: { artifactType: file.type, provider: "internal_sandbox", completedAt: result.completedAt, signerCount: signers.length }, provider_metadata_json: result.providerMetadata, updated_at: result.completedAt, lock_version: 2 }).eq("id", artifactRow.id).eq("status", "retrieving").select("*").single(); if (updated.error) throw new SignatureEnvelopeError("SIGNATURE_ARTIFACT_UPDATE_FAILED"); inserted.push(updated.data); }
    await client.from("contract_signature_artifact_operations").update({ status: "completed", completed_at: result.completedAt, updated_at: result.completedAt }).eq("law_firm_id", context.lawFirmId).eq("envelope_id", envelopeId).eq("operation_type", "retrieval").eq("idempotency_key", idempotencyKey); await event(client, context.lawFirmId, envelopeId, context.userId, "signature_artifacts_retrieved", `artifact-retrieved:${envelopeId}:${idempotencyKey}:done`, { count: inserted.length }); return inserted;
  } catch (error) { const code = safe(error); await client.from("contract_signature_artifacts").update({ status: "failed", updated_at: new Date().toISOString() }).eq("law_firm_id", context.lawFirmId).eq("envelope_id", envelopeId).eq("status", "retrieving"); await client.from("contract_signature_artifact_operations").update({ status: "failed", safe_error_code: code, updated_at: new Date().toISOString() }).eq("law_firm_id", context.lawFirmId).eq("envelope_id", envelopeId).eq("operation_type", "retrieval").eq("idempotency_key", idempotencyKey); await event(client, context.lawFirmId, envelopeId, context.userId, "signature_artifacts_failed", `artifact-failed:${envelopeId}:${idempotencyKey}`, { safeErrorCode: code }); throw new SignatureEnvelopeError(code); }
}
export async function listSignatureArtifacts(client: Db, lawFirmId: string, envelopeId: string) { const result = await client.from("contract_signature_artifacts").select("id,contract_id,envelope_id,artifact_type,status,mime_type,file_name,file_hash,file_size,page_count,source_document_hash,retrieved_at,validated_at,archived_at,provider,evidence_snapshot_json").eq("law_firm_id", lawFirmId).eq("envelope_id", envelopeId).order("artifact_type"); if (result.error) throw new SignatureEnvelopeError("SIGNATURE_ARTIFACT_READ_FAILED"); return result.data ?? []; }
export async function archiveSignatureArtifact(client: Db, context: ArtifactContext, artifactId: string, idempotencyKey: string) { if (!allowedRoles.has(context.role)) throw new SignatureEnvelopeError("SIGNATURE_PERMISSION_DENIED"); const row = await client.from("contract_signature_artifacts").select("*").eq("id", artifactId).eq("law_firm_id", context.lawFirmId).maybeSingle(); if (row.error || !row.data) throw new SignatureEnvelopeError("SIGNATURE_ARTIFACT_NOT_FOUND"); if (row.data.status === "archived") return row.data; if (row.data.status !== "completed") throw new SignatureEnvelopeError("SIGNATURE_ARTIFACT_ARCHIVE_INVALID"); const operation = await client.from("contract_signature_artifact_operations").insert({ law_firm_id: context.lawFirmId, contract_id: row.data.contract_id, envelope_id: row.data.envelope_id, operation_type: "archive", status: "processing", idempotency_key: idempotencyKey, input_hash: sha(JSON.stringify({ artifactId, status: row.data.status })) }).select("id").maybeSingle(); if (operation.error && String(operation.error.code).includes("23505")) return row.data; if (operation.error) throw new SignatureEnvelopeError("SIGNATURE_ARTIFACT_OPERATION_FAILED"); const archived = await client.from("contract_signature_artifacts").update({ status: "archived", archived_at: new Date().toISOString(), updated_at: new Date().toISOString(), lock_version: Number(row.data.lock_version) + 1 }).eq("id", artifactId).eq("law_firm_id", context.lawFirmId).eq("status", "completed").select("*").single(); if (archived.error) throw new SignatureEnvelopeError("SIGNATURE_ARTIFACT_ARCHIVE_FAILED"); await client.from("contract_signature_artifact_operations").update({ status: "completed", completed_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", operation.data.id); await event(client, context.lawFirmId, row.data.envelope_id, context.userId, "signature_artifact_archived", `artifact-archived:${artifactId}:${idempotencyKey}`, { artifactType: row.data.artifact_type }); return archived.data; }
