import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/lib/supabase/types";
import type { ProposalDetailDTO, ProposalEventDTO, ProposalListDTO, ProposalLawyerDTO, ProposalOwnerDTO, ProposalRestrictedDTO } from "../application/dto";
import type { CommercialProposalItem, CommercialProposalRecipient, CommercialProposalSection, CommercialProposalVersion } from "../domain/types";
import { sanitizeProposalEvent } from "../domain/events";
import type { ProposalRepository } from "./repositories";
type QueryClient = SupabaseClient<Database>;
type Row = Record<string, unknown>;
function rpcQuery(client: QueryClient, name: string, args: Record<string, unknown>) { const rpc = client.rpc as unknown as (rpcName: string, parameters: Record<string, unknown>) => Promise<{ data: Row[] | null; error: { message: string } | null }>; return rpc.call(client, name, args); }
type TableResult = { data: Row[] | null; error: { message: string } | null };
function isoDate(value: unknown) { const raw = String(value); if (raw.includes("T") && /(?:Z|[+-]\d\d:\d\d)$/.test(raw)) return raw.replace(/[+-]00:00$/, "Z"); const normalized = raw.replace(" ", "T").replace(/\+00$/, "Z"); return normalized; }
const summaryDefaults = { subtotalCents: 0, discountCents: 0, totalCents: 0, entryAmountCents: 0, installmentCount: 0, installmentAmountCents: 0, recurringAmountCents: 0, recurringMonths: 0, successFeeBps: 0 };
function mapSummary(row: Row): CommercialProposalVersion["commercialSummary"] { const raw = (row.commercial_summary_json ?? {}) as Record<string, unknown>; return { currency: String(raw.currency ?? row.currency ?? "BRL"), ...summaryDefaults, ...Object.fromEntries(Object.keys(summaryDefaults).map((key) => [key, Number(raw[key] ?? row[key] ?? 0)])) }; }
type TableQuery = PromiseLike<TableResult> & { eq(column: string, value: unknown): TableQuery; order(column: string, options?: { ascending?: boolean }): TableQuery };
function tableRows(client: QueryClient, table: string, columns: string, filters: Array<[string, unknown]>): PromiseLike<TableResult> { let query = (client.from as unknown as (name: string) => { select(columns: string): TableQuery })(table).select(columns); for (const [column, value] of filters) query = query.eq(column, value); return query; }
function mapList(row: Row): ProposalListDTO { return { id: String(row.id), title: String(row.title), status: row.status as ProposalListDTO["status"], originType: row.origin_type as ProposalListDTO["originType"], currency: String(row.currency), activeVersionId: row.active_version_id ? String(row.active_version_id) : null, validUntil: row.valid_until ? isoDate(row.valid_until) : null, createdAt: isoDate(row.created_at), updatedAt: isoDate(row.updated_at) }; }
function mapProposal(row: Row, role: "owner" | "lawyer" | "restricted"): ProposalOwnerDTO | ProposalLawyerDTO | ProposalRestrictedDTO { const base = { id: String(row.id), lawFirmId: String(row.law_firm_id), title: String(row.title), status: row.status as ProposalOwnerDTO["status"], originType: row.origin_type as ProposalOwnerDTO["originType"], currency: String(row.currency), activeVersionId: row.active_version_id ? String(row.active_version_id) : null, validUntil: row.valid_until ? isoDate(row.valid_until) : null, createdAt: isoDate(row.created_at), updatedAt: isoDate(row.updated_at) }; if (role === "restricted") return base; const lawyer = { ...base, internalReference: row.internal_reference ? String(row.internal_reference) : null }; if (role === "lawyer") return lawyer; return { ...lawyer, internalNotes: row.internal_notes ? String(row.internal_notes) : null, sourcePricingScenarioId: row.source_pricing_scenario_id ? String(row.source_pricing_scenario_id) : null, sourcePricingVersionId: row.source_pricing_version_id ? String(row.source_pricing_version_id) : null }; }
function mapSection(row: Row): CommercialProposalSection { return { id: String(row.id), proposalVersionId: String(row.proposal_version_id), sectionType: String(row.section_type), title: row.title ? String(row.title) : null, bodyMarkdown: row.body_markdown ? String(row.body_markdown) : null, orderIndex: Number(row.order_index ?? 0), isRequired: Boolean(row.is_required) }; }
function mapItem(row: Row): CommercialProposalItem { return { id: String(row.id), proposalVersionId: String(row.proposal_version_id), itemType: String(row.item_type), description: String(row.description ?? ""), quantity: Number(row.quantity ?? 0), unitAmountCents: Number(row.unit_amount_cents ?? 0), totalAmountCents: Number(row.total_amount_cents ?? 0), isOptional: Boolean(row.is_optional), isIncluded: Boolean(row.is_included), orderIndex: Number(row.order_index ?? 0), metadata: (row.metadata ?? {}) as Record<string, unknown> }; }
function mapRecipient(row: Row, role: "owner" | "lawyer" | "restricted"): CommercialProposalRecipient { const recipient: CommercialProposalRecipient = { id: String(row.id), proposalId: String(row.proposal_id), recipientType: String(row.recipient_type), name: String(row.name ?? ""), isPrimary: Boolean(row.is_primary) }; if (role !== "restricted") { if (row.email) recipient.email = String(row.email); if (row.phone) recipient.phone = String(row.phone); if (row.company_name) recipient.companyName = String(row.company_name); } return recipient; }
export class SupabaseProposalRepository implements ProposalRepository {
  constructor(private readonly client: QueryClient, private readonly role: "owner" | "lawyer" | "restricted" = "lawyer") {}
  async list(status?: string) { const result = await rpcQuery(this.client, "get_commercial_proposals_secure", { p_status: status ?? null }); if (result.error) throw result.error; return (result.data ?? []).map(mapList); }
  async detail(proposalId: string) { const proposalResult = await rpcQuery(this.client, "get_commercial_proposal_secure", { p_proposal_id: proposalId }); if (proposalResult.error) throw proposalResult.error; const row = proposalResult.data?.[0]; if (!row) return null; const versionResult = await rpcQuery(this.client, "get_commercial_proposal_version_secure", { p_proposal_id: proposalId, p_version_id: null }); if (versionResult.error) throw versionResult.error; const versionRow = versionResult.data?.[0] ?? null; const versionId = versionRow?.id ? String(versionRow.id) : null; const [sectionsResult, itemsResult, recipientsResult] = await Promise.all([versionId ? tableRows(this.client, "commercial_proposal_sections", "id, proposal_version_id, section_type, title, body_markdown, order_index, is_required", [["proposal_version_id", versionId]]) : Promise.resolve({ data: [], error: null }), versionId ? tableRows(this.client, "commercial_proposal_items", "id, proposal_version_id, item_type, description, quantity, unit_amount_cents, total_amount_cents, is_optional, is_included, order_index, metadata", [["proposal_version_id", versionId]]) : Promise.resolve({ data: [], error: null }), rpcQuery(this.client, "get_commercial_proposal_recipients_secure", { p_proposal_id: proposalId })]); if (sectionsResult.error) throw sectionsResult.error; if (itemsResult.error) throw itemsResult.error; if (recipientsResult.error) throw recipientsResult.error; const activeVersion = versionRow ? ({ id: String(versionRow.id), proposalId: String(versionRow.proposal_id), versionNumber: Number(versionRow.version_number), schemaVersion: 1, title: String(versionRow.title), currency: String(versionRow.currency), commercialSummary: mapSummary(versionRow), paymentTerms: {}, contentHash: String(versionRow.content_hash), createdAt: isoDate(versionRow.created_at) } satisfies CommercialProposalVersion) : null; return { proposal: mapProposal(row, this.role), activeVersion, sections: (sectionsResult.data ?? []).map(mapSection), items: (itemsResult.data ?? []).map(mapItem), recipients: (recipientsResult.data ?? []).map((recipient) => mapRecipient(recipient, this.role)) } satisfies ProposalDetailDTO; }
  async events(proposalId: string) { const result = await rpcQuery(this.client, "get_commercial_proposal_events_secure", { p_proposal_id: proposalId }); if (result.error) throw result.error; return (result.data ?? []).map((row) => sanitizeProposalEvent({ id: String(row.id), proposalId: String(row.proposal_id), proposalVersionId: row.proposal_version_id ? String(row.proposal_version_id) : null, eventType: row.event_type as ProposalEventDTO["eventType"], metadata: (row.metadata ?? {}) as Record<string, unknown>, createdAt: String(row.created_at) })); }
}
