import { createHash } from "node:crypto";
import { canManageSignatureEnvelope } from "../permissions";
import { evaluateSignatureEnvelopeReadiness } from "../readiness";
import { getSignatureSource, type Db } from "../repository";
import { SignatureEnvelopeError } from "../errors";
import { buildDeliverySnapshot } from "./snapshot";
import { getSignatureProviderAdapter, isSignatureSandboxEnabled } from "./registry";
import { assertDeliveryTransition, transitionForProviderEvent } from "./state";
import type { DeliveryStatus, NormalizedSignatureEvent, SignatureProvider } from "./types";

const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value), "utf8").digest("hex");
const safeError = (error: unknown) => String((error as { code?: string; message?: string })?.code ?? (error as Error)?.message ?? "SIGNATURE_DELIVERY_FAILED").replace(/[^A-Z0-9_.:-]/gi, "_").slice(0, 120);
const contextCheck = (context: { lawFirmId: string; userId: string; role: string }) => { if (!canManageSignatureEnvelope(context.role as never)) throw new SignatureEnvelopeError("SIGNATURE_PERMISSION_DENIED"); };
const row = async (client: Db, table: string, id: string, lawFirmId: string) => { const result = await client.from(table).select("*").eq("id", id).eq("law_firm_id", lawFirmId).maybeSingle(); if (result.error) throw new SignatureEnvelopeError("SIGNATURE_DELIVERY_READ_FAILED"); return result.data; };
const event = async (client: Db, lawFirmId: string, envelopeId: string, actorUserId: string, eventType: string, deduplicationKey: string, metadata: Record<string, unknown> = {}) => { const result = await client.from("contract_signature_events").insert({ law_firm_id: lawFirmId, envelope_id: envelopeId, event_type: eventType, actor_user_id: actorUserId, deduplication_key: deduplicationKey, safe_metadata_json: metadata }); console.info("[signature-delivery] event_insert", { envelopeId, eventType, inserted: !result.error, errorCode: result.error?.code ?? null }); if (result.error && !String(result.error.code).includes("23505")) throw new SignatureEnvelopeError("SIGNATURE_DELIVERY_EVENT_FAILED"); };
const delivery = async (client: Db, lawFirmId: string, envelopeId: string, provider: SignatureProvider) => { const result = await client.from("contract_signature_provider_deliveries").select("*").eq("law_firm_id", lawFirmId).eq("envelope_id", envelopeId).eq("provider", provider).maybeSingle(); if (result.error) throw new SignatureEnvelopeError("SIGNATURE_DELIVERY_READ_FAILED"); return result.data; };
const waitForSentEvent = async (client: Db, envelopeId: string) => { for (let attempt = 0; attempt < 20; attempt += 1) { const result = await client.from("contract_signature_events").select("id").eq("envelope_id", envelopeId).eq("event_type", "signature_envelope_sent").maybeSingle(); if (result.data) return; await new Promise((resolve) => setTimeout(resolve, 50)); } };

export async function getSignatureDelivery(client: Db, lawFirmId: string, envelopeId: string) { const result = await client.from("contract_signature_provider_deliveries").select("id,law_firm_id,envelope_id,provider,provider_envelope_id,status,attempt_number,last_error_code,last_error_at,sent_at,last_synced_at,created_at,updated_at,lock_version").eq("law_firm_id", lawFirmId).eq("envelope_id", envelopeId).eq("provider", "internal_sandbox").maybeSingle(); return result.data ?? null; }

type DeliveryContext = { lawFirmId: string; userId: string; role: string };
export async function sendSignatureEnvelope(client: Db, context: DeliveryContext, envelopeId: string, provider: SignatureProvider, idempotencyKey: string, inputHash?: string) {
  contextCheck(context); if (!isSignatureSandboxEnabled()) throw new SignatureEnvelopeError("SIGNATURE_PROVIDER_DISABLED"); if (!idempotencyKey.trim()) throw new SignatureEnvelopeError("SIGNATURE_IDEMPOTENCY_REQUIRED");
  const adapter = getSignatureProviderAdapter(provider); const envelope = await row(client, "contract_signature_envelopes", envelopeId, context.lawFirmId); console.info("[signature-delivery] envelope_loaded", { envelopeId, found: Boolean(envelope), status: envelope?.status ?? null }); if (!envelope || envelope.status !== "prepared") throw new SignatureEnvelopeError("SIGNATURE_SEND_REQUIRES_PREPARED");
  const source = await getSignatureSource(client, context.lawFirmId, envelope.contract_document_id); console.info("[signature-delivery] source_loaded", { envelopeId, found: Boolean(source), status: source?.status ?? null }); if (!source || source.status !== "completed") throw new SignatureEnvelopeError("SIGNATURE_SOURCE_INVALID");
  const signersResult = await client.from("contract_signature_signers").select("*").eq("law_firm_id", context.lawFirmId).eq("envelope_id", envelopeId).neq("status", "removed").order("signing_order"); if (signersResult.error) throw new SignatureEnvelopeError("SIGNATURE_DELIVERY_READ_FAILED");
  const signers = (signersResult.data ?? []).map((signer: Record<string, unknown>) => ({ ...signer, signerType: signer.signer_type, signingOrder: signer.signing_order, requiresIdentityVerification: signer.requires_identity_verification }));
  const readiness = evaluateSignatureEnvelopeReadiness(source, signers, envelope.consent_version, envelope.document_snapshot_json); console.info("[signature-delivery] readiness", { envelopeId, ready: readiness.ready, signers: signers.length, blockers: readiness.blockers }); if (!readiness.ready) throw new SignatureEnvelopeError(`SIGNATURE_NOT_READY:${readiness.blockers.join(",")}`);
  const snapshot = buildDeliverySnapshot({ ...envelope, id: envelope.id, lawFirmId: context.lawFirmId, contractId: envelope.contract_id, contractDocumentId: envelope.contract_document_id, contractVersionId: envelope.contract_version_id, status: envelope.status, title: envelope.title, consentVersion: envelope.consent_version, signingOrderEnabled: envelope.signing_order_enabled, expiresAt: envelope.expires_at, preparedAt: envelope.prepared_at, cancelledAt: envelope.cancelled_at, documentHash: envelope.document_hash, documentFileSize: envelope.document_file_size, documentPageCount: envelope.document_page_count, lockVersion: envelope.lock_version, signers: [], snapshot: envelope.document_snapshot_json }, source, readiness.normalizedSigners);
  const deterministicHash = inputHash ?? hash({ envelopeId, provider, snapshot }); const existingOperation = await client.from("contract_signature_outbox").select("id,status,input_hash").eq("law_firm_id", context.lawFirmId).eq("envelope_id", envelopeId).eq("operation_type", "send").eq("idempotency_key", idempotencyKey).maybeSingle(); console.info("[signature-delivery] outbox_lookup", { envelopeId, found: Boolean(existingOperation?.data), status: existingOperation?.data?.status ?? null, errorCode: existingOperation?.error?.code ?? null }); if (existingOperation?.data) { if (existingOperation.data.input_hash !== deterministicHash) throw new SignatureEnvelopeError("SIGNATURE_IDEMPOTENCY_CONFLICT"); if (existingOperation.data.status === "completed") return getSignatureDelivery(client, context.lawFirmId, envelopeId); }
  let current = await delivery(client, context.lawFirmId, envelopeId, provider); if (["sent", "viewed", "partially_signed", "signed", "refused", "expired", "cancelled"].includes(current?.status ?? "")) return current;
  console.info("[signature-delivery] send_prepared", { envelopeId, currentStatus: current?.status ?? null, currentPresent: Boolean(current), provider });
  if (!current) { const inserted = await client.from("contract_signature_provider_deliveries").insert({ law_firm_id: context.lawFirmId, envelope_id: envelopeId, provider, status: "sending", attempt_number: 1, request_snapshot_json: snapshot, lock_version: 1 }).select("*").single(); if (inserted.error || !inserted.data) { const recovered = await delivery(client, context.lawFirmId, envelopeId, provider); if (recovered) return recovered; throw new SignatureEnvelopeError("SIGNATURE_DELIVERY_CREATE_FAILED"); } current = inserted.data; }
  if (!current) throw new SignatureEnvelopeError("SIGNATURE_DELIVERY_CREATE_FAILED");
  const outbox = await client.from("contract_signature_outbox").insert({ law_firm_id: context.lawFirmId, envelope_id: envelopeId, operation_type: "send", status: "processing", attempt_count: current.attempt_number, idempotency_key: idempotencyKey, input_hash: deterministicHash }).select("id").maybeSingle(); if (outbox.error) { if (String(outbox.error.code).includes("23505")) { await waitForSentEvent(client, envelopeId); return getSignatureDelivery(client, context.lawFirmId, envelopeId); } throw new SignatureEnvelopeError("SIGNATURE_OUTBOX_CREATE_FAILED"); }
  console.info("[signature-delivery] send_claimed", { envelopeId, deliveryId: current.id, attempt: current.attempt_number }); await event(client, context.lawFirmId, envelopeId, context.userId, "signature_delivery_requested", `delivery_requested:${envelopeId}:${idempotencyKey}`, { provider }); await event(client, context.lawFirmId, envelopeId, context.userId, "signature_delivery_started", `delivery_started:${envelopeId}:${current.attempt_number}`, { provider, attempt: current.attempt_number });
  try { const result = await adapter.createEnvelope({ provider, envelopeId, source, signers: readiness.normalizedSigners, consentVersion: envelope.consent_version, expiresAt: envelope.expires_at, callbackReference: `internal://signature/${envelopeId}` });
    const updated = await client.from("contract_signature_provider_deliveries").update({ provider_envelope_id: result.providerEnvelopeId, status: "sent", response_snapshot_json: result.responseSnapshot, sent_at: new Date().toISOString(), updated_at: new Date().toISOString(), lock_version: current.lock_version + 1 }).eq("id", current.id).eq("lock_version", current.lock_version).select("*").single(); if (updated.error) throw new SignatureEnvelopeError("SIGNATURE_DELIVERY_STALE_LOCK");
    await client.from("contract_signature_envelopes").update({ status: "sent", provider, provider_envelope_id: result.providerEnvelopeId, updated_by: context.userId, lock_version: envelope.lock_version + 1 }).eq("id", envelopeId).eq("law_firm_id", context.lawFirmId).eq("status", "prepared").eq("lock_version", envelope.lock_version).select("id").single(); await client.from("contract_signature_outbox").update({ status: "completed", completed_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("law_firm_id", context.lawFirmId).eq("envelope_id", envelopeId).eq("operation_type", "send").eq("idempotency_key", idempotencyKey); await event(client, context.lawFirmId, envelopeId, context.userId, "signature_envelope_sent", `envelope_sent:${envelopeId}:${current.attempt_number}`, { provider }); return updated.data;
  } catch (error) { const code = safeError(error); await client.from("contract_signature_provider_deliveries").update({ status: "failed", last_error_code: code, last_error_at: new Date().toISOString(), updated_at: new Date().toISOString(), lock_version: current.lock_version + 1 }).eq("id", current.id); await client.from("contract_signature_outbox").update({ status: "failed", safe_error_code: code, updated_at: new Date().toISOString() }).eq("law_firm_id", context.lawFirmId).eq("envelope_id", envelopeId).eq("operation_type", "send").eq("idempotency_key", idempotencyKey); await event(client, context.lawFirmId, envelopeId, context.userId, "signature_delivery_failed", `delivery_failed:${envelopeId}:${current.attempt_number}`, { provider, safeErrorCode: code }); throw new SignatureEnvelopeError(code); }
}

export async function retrySignatureDelivery(client: Db, context: DeliveryContext, envelopeId: string, idempotencyKey: string) { contextCheck(context); const current = await delivery(client, context.lawFirmId, envelopeId, "internal_sandbox"); if (!current || current.status !== "failed") throw new SignatureEnvelopeError("SIGNATURE_RETRY_REQUIRES_FAILED"); const envelope = await row(client, "contract_signature_envelopes", envelopeId, context.lawFirmId); if (!envelope || envelope.status !== "prepared") throw new SignatureEnvelopeError("SIGNATURE_RETRY_STATE_INVALID"); await client.from("contract_signature_provider_deliveries").update({ status: "sending", attempt_number: current.attempt_number + 1, last_error_code: null, updated_at: new Date().toISOString(), lock_version: current.lock_version + 1 }).eq("id", current.id).eq("lock_version", current.lock_version); await event(client, context.lawFirmId, envelopeId, context.userId, "signature_delivery_retry_requested", `delivery_retry:${envelopeId}:${current.attempt_number + 1}`, { provider: "internal_sandbox", attempt: current.attempt_number + 1 }); return sendSignatureEnvelope(client, context, envelopeId, "internal_sandbox", idempotencyKey); }

export async function cancelSentSignatureEnvelope(client: Db, context: DeliveryContext, envelopeId: string) { contextCheck(context); const current = await delivery(client, context.lawFirmId, envelopeId, "internal_sandbox"); if (!current?.provider_envelope_id) throw new SignatureEnvelopeError("SIGNATURE_CANCEL_SEND_NOT_STARTED"); if (["signed", "refused", "expired", "cancelled"].includes(current.status)) throw new SignatureEnvelopeError("SIGNATURE_CANCEL_TERMINAL"); const result = await getSignatureProviderAdapter("internal_sandbox").cancelEnvelope({ provider: "internal_sandbox", providerEnvelopeId: current.provider_envelope_id }); await client.from("contract_signature_provider_deliveries").update({ status: "cancelled", response_snapshot_json: result.responseSnapshot, updated_at: new Date().toISOString(), lock_version: current.lock_version + 1 }).eq("id", current.id).eq("lock_version", current.lock_version); await client.from("contract_signature_envelopes").update({ status: "cancelled", cancelled_at: new Date().toISOString(), cancelled_by: context.userId, cancellation_reason: "Cancelamento da solicitação sandbox", updated_by: context.userId, lock_version: (await row(client, "contract_signature_envelopes", envelopeId, context.lawFirmId)).lock_version + 1 }).eq("id", envelopeId).eq("law_firm_id", context.lawFirmId); await event(client, context.lawFirmId, envelopeId, context.userId, "signature_provider_cancelled", `provider_cancelled:${envelopeId}`, { provider: "internal_sandbox" }); return getSignatureDelivery(client, context.lawFirmId, envelopeId); }

export async function reconcileSignatureEnvelopeStatus(client: Db, context: DeliveryContext, envelopeId: string) { contextCheck(context); const current = await delivery(client, context.lawFirmId, envelopeId, "internal_sandbox"); if (!current?.provider_envelope_id) throw new SignatureEnvelopeError("SIGNATURE_RECONCILE_NOT_SENT"); const result = await getSignatureProviderAdapter("internal_sandbox").getEnvelopeStatus({ provider: "internal_sandbox", providerEnvelopeId: current.provider_envelope_id }); const next = result.status; if (next !== current.status) assertDeliveryTransition(current.status as DeliveryStatus, next); await client.from("contract_signature_provider_deliveries").update({ status: next, response_snapshot_json: result.responseSnapshot, last_synced_at: new Date().toISOString(), updated_at: new Date().toISOString(), lock_version: current.lock_version + 1 }).eq("id", current.id).eq("lock_version", current.lock_version); await event(client, context.lawFirmId, envelopeId, context.userId, "signature_delivery_reconciled", `delivery_reconciled:${envelopeId}:${next}`, { provider: "internal_sandbox", status: next }); return getSignatureDelivery(client, context.lawFirmId, envelopeId); }

export async function applyNormalizedSignatureEvent(client: Db, eventInput: NormalizedSignatureEvent, actorUserId: string) {
  const deliveryRow = await client.from("contract_signature_provider_deliveries").select("*").eq("provider", eventInput.provider).eq("provider_envelope_id", eventInput.providerEnvelopeId).maybeSingle();
  if (deliveryRow.error || !deliveryRow.data) throw new SignatureEnvelopeError("SIGNATURE_WEBHOOK_ENVELOPE_NOT_FOUND");
  const current = deliveryRow.data;
  const signersResult = await client.from("contract_signature_signers").select("id,email,status").eq("envelope_id", current.envelope_id).neq("status", "removed").order("signing_order");
  if (signersResult.error) throw new SignatureEnvelopeError("SIGNATURE_DELIVERY_READ_FAILED");
  const signerEmails = new Set((eventInput.signerEmails ?? []).map((email) => email.toLowerCase()));
  const matchingSigners = (signersResult.data ?? []).filter((signer: { email: string }) => signerEmails.has(String(signer.email).toLowerCase()));
  const allSignersMatched = matchingSigners.length > 0 && matchingSigners.length === (signersResult.data ?? []).length;
  const nextEvent = eventInput.eventType === "signed" && !allSignersMatched && matchingSigners.length > 0 ? { ...eventInput, eventType: "partially_signed" as const } : eventInput;
  const next = transitionForProviderEvent(current.status as DeliveryStatus, nextEvent);
  const updated = await client.from("contract_signature_provider_deliveries").update({ status: next, last_synced_at: new Date().toISOString(), updated_at: new Date().toISOString(), lock_version: current.lock_version + 1 }).eq("id", current.id).eq("lock_version", current.lock_version).select("*").maybeSingle();
  if (!updated.data) return current;
  const envelope = await client.from("contract_signature_envelopes").select("lock_version,status").eq("id", current.envelope_id).single();
  if (envelope.data && envelope.data.status === current.status) await client.from("contract_signature_envelopes").update({ status: next, updated_by: actorUserId, lock_version: envelope.data.lock_version + 1 }).eq("id", current.envelope_id).eq("status", current.status).eq("lock_version", envelope.data.lock_version);
  if (["viewed", "partially_signed", "signed", "refused", "expired"].includes(next)) {
    const signerStatus = next === "signed" ? "signed" : next === "refused" ? "refused" : next === "expired" ? "expired" : next === "partially_signed" ? "signed" : "viewed";
    const target = signerEmails.size ? (signersResult.data ?? []).filter((signer: { email: string }) => signerEmails.has(String(signer.email).toLowerCase())).map((signer: { id: string }) => signer.id) : (signersResult.data ?? []).map((signer: { id: string }) => signer.id);
    if (target.length) await client.from("contract_signature_signers").update({ status: signerStatus }).in("id", target);
  }
  await event(client, current.law_firm_id, current.envelope_id, actorUserId, `signature_provider_${eventInput.eventType}`, `provider_event:${eventInput.providerEventId}`, { provider: eventInput.provider });
  return updated.data;
}
