"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { getAppContext } from "@/lib/auth/context";
import { can } from "@/lib/auth/permissions";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { checkOverdueTasks } from "@/lib/alerts/check-overdue-tasks";

type TaskClient = { from(table: "tasks" | "audit_logs"): { select(columns: string): { eq(column: string, value: string): { eq(column: string, value: string): { single(): Promise<{ data: unknown; error: Error | null }> } } }; update(values: Record<string, unknown>): { eq(column: string, value: string): { eq(column: string, value: string): PromiseLike<{ error: Error | null }> } }; insert(values: Record<string, unknown>): PromiseLike<{ error: Error | null }> } };
function fail(id: string, code: string): never { redirect(`/tarefas/${id}?erro=${code}`); }
async function contextFor(id: string) { const context = await getAppContext(); if (context.status === "signed-out") redirect("/entrar"); if (context.status !== "ready" || !context.member || !context.lawFirm) redirect("/onboarding"); if (!can(context.member.role, "tarefas.gerenciar")) fail(id, "permissao"); return { context, lawFirm: context.lawFirm, member: context.member }; }
async function updateTask(id: string, values: Record<string, unknown>, action: string, metadata: Record<string, unknown>) { const { lawFirm, member } = await contextFor(id); const supabase = await getSupabaseServerClient(); if (!supabase) fail(id, "ambiente"); const client = supabase as unknown as TaskClient; const { error } = await client.from("tasks").update(values).eq("law_firm_id", lawFirm.id).eq("id", id); if (error) fail(id, "atualizacao"); await client.from("audit_logs").insert({ law_firm_id: lawFirm.id, actor_id: member.id, action, entity_type: "task", entity_id: id, metadata }); revalidatePath(`/tarefas/${id}`); revalidatePath("/tarefas"); redirect(`/tarefas/${id}?salvo=1`); }
export async function addChecklistItemAction(formData: FormData) { const id = String(formData.get("taskId") ?? ""); const title = String(formData.get("title") ?? "").trim(); if (!id || title.length < 2) fail(id, "validacao"); const { lawFirm, member } = await contextFor(id); const supabase = await getSupabaseServerClient(); if (!supabase) fail(id, "ambiente"); const client = supabase as unknown as TaskClient; const current = await client.from("tasks").select("checklist").eq("law_firm_id", lawFirm.id).eq("id", id).single(); if (current.error) fail(id, "tarefa"); const checklist = Array.isArray((current.data as { checklist?: unknown }).checklist) ? (current.data as { checklist: Array<{ id: string; title: string; done: boolean }> }).checklist : []; await updateTask(id, { checklist: [...checklist, { id: crypto.randomUUID(), title, done: false }] }, "adicionou_item_checklist", { title }); }
export async function toggleChecklistItemAction(formData: FormData) { const id = String(formData.get("taskId") ?? ""); const itemId = String(formData.get("itemId") ?? ""); if (!id || !itemId) fail(id, "validacao"); const { lawFirm, member } = await contextFor(id); const supabase = await getSupabaseServerClient(); if (!supabase) fail(id, "ambiente"); const client = supabase as unknown as TaskClient; const current = await client.from("tasks").select("checklist").eq("law_firm_id", lawFirm.id).eq("id", id).single(); if (current.error) fail(id, "tarefa"); const checklist = ((current.data as { checklist?: unknown }).checklist ?? []) as Array<{ id: string; title: string; done: boolean }>; await updateTask(id, { checklist: checklist.map((item) => item.id === itemId ? { ...item, done: !item.done } : item) }, "alterou_checklist_tarefa", { item_id: itemId }); }
export async function addTaskCommentAction(formData: FormData) { const id = String(formData.get("taskId") ?? ""); const body = String(formData.get("body") ?? "").trim(); if (!id || body.length < 2) fail(id, "validacao"); const { lawFirm, member } = await contextFor(id); const supabase = await getSupabaseServerClient(); if (!supabase) fail(id, "ambiente"); const client = supabase as unknown as TaskClient; const current = await client.from("tasks").select("comments").eq("law_firm_id", lawFirm.id).eq("id", id).single(); if (current.error) fail(id, "tarefa"); const comments = ((current.data as { comments?: unknown }).comments ?? []) as Array<{ id: string; body: string; author: string; createdAt: string }>; await updateTask(id, { comments: [...comments, { id: crypto.randomUUID(), body, author: member.name, createdAt: new Date().toISOString() }] }, "comentou_em_tarefa", {}); }

type TaskReadClient = { from(table: "tasks"): { select(columns: string): { eq(column: string, value: string): { eq(column: string, value: string): { maybeSingle(): Promise<{ data: unknown | null; error: Error | null }> } } } } };

export type TaskData = { id: string; title: string; description: string | null; status: string; priority: string; due_at: string | null; client_id: string | null; legal_case_id: string | null; responsible_member_id: string | null; checklist: Array<{ id: string; title: string; done: boolean }>; comments: Array<{ id: string; body: string; author: string; createdAt: string }>; created_at: string; updated_at: string };

export async function getTaskById(lawFirmId: string, taskId: string): Promise<TaskData | null> { const supabase = await getSupabaseServerClient(); if (!supabase) return null; const { data } = await (supabase as unknown as TaskReadClient).from("tasks").select("id, title, description, status, priority, due_at, client_id, legal_case_id, responsible_member_id, checklist, comments, created_at, updated_at").eq("law_firm_id", lawFirmId).eq("id", taskId).maybeSingle(); return (data as TaskData | null) ?? null; }

export async function updateTaskAction(formData: FormData) { const taskId = String(formData.get("taskId") ?? ""); if (!taskId) fail(taskId, "validacao"); const context = await getAppContext(); if (context.status !== "ready" || !context.member || !context.lawFirm) redirect("/entrar"); if (!can(context.member.role, "tarefas.gerenciar")) fail(taskId, "permissao"); const { taskSchema } = await import("@/lib/validations/foundation"); const parsed = taskSchema.safeParse({ title: String(formData.get("title") ?? "").trim(), description: String(formData.get("description") ?? "").trim(), clientId: String(formData.get("clientId") ?? ""), legalCaseId: String(formData.get("legalCaseId") ?? ""), responsibleMemberId: String(formData.get("responsibleMemberId") ?? ""), priority: String(formData.get("priority") ?? "normal"), dueAt: String(formData.get("dueAt") ?? "") }); if (!parsed.success) fail(taskId, "validacao"); const supabase = await getSupabaseServerClient(); if (!supabase) fail(taskId, "ambiente"); const client = supabase as unknown as TaskClient; const { error } = await client.from("tasks").update({ title: parsed.data.title, description: parsed.data.description || null, client_id: parsed.data.clientId || null, legal_case_id: parsed.data.legalCaseId || null, responsible_member_id: parsed.data.responsibleMemberId || context.member.id, priority: parsed.data.priority, due_at: parsed.data.dueAt ? new Date(parsed.data.dueAt).toISOString() : null, updated_at: new Date().toISOString() } as Record<string, unknown>).eq("law_firm_id", context.lawFirm.id).eq("id", taskId); if (error) fail(taskId, "atualizacao"); await client.from("audit_logs").insert({ law_firm_id: context.lawFirm.id, actor_id: context.member.id, action: "atualizou_tarefa", entity_type: "task", entity_id: taskId, metadata: { title: parsed.data.title } }); revalidatePath(`/tarefas/${taskId}`); revalidatePath("/tarefas"); revalidatePath("/dashboard"); checkOverdueTasks().catch((err) => console.error("[background] checkOverdueTasks:", err)); redirect(`/tarefas/${taskId}?salvo=1`); }

export async function deleteTaskAction(formData: FormData) { const taskId = String(formData.get("taskId") ?? ""); if (!taskId) fail(taskId, "validacao"); const context = await getAppContext(); if (context.status !== "ready" || !context.member || !context.lawFirm) redirect("/entrar"); if (!can(context.member.role, "tarefas.gerenciar")) fail(taskId, "permissao"); const supabase = await getSupabaseServerClient(); if (!supabase) fail(taskId, "ambiente"); const client = supabase as unknown as TaskClient; const { error } = await client.from("tasks").update({ status: "cancelado", updated_at: new Date().toISOString() } as Record<string, unknown>).eq("law_firm_id", context.lawFirm.id).eq("id", taskId); if (error) fail(taskId, "atualizacao"); await client.from("audit_logs").insert({ law_firm_id: context.lawFirm.id, actor_id: context.member.id, action: "cancelou_tarefa", entity_type: "task", entity_id: taskId, metadata: {} }); revalidatePath("/tarefas"); revalidatePath("/dashboard"); redirect("/tarefas?cancelado=1"); }
