import Link from "next/link";
import { AppShell } from "@/components/layout/app-shell";
import { PageHeader } from "@/components/page-header";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getAppContext } from "@/lib/auth/context";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { formatDateTime } from "@/lib/formatters";
import { addChecklistItemAction, addTaskCommentAction, toggleChecklistItemAction } from "./actions";

export default async function TaskDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ erro?: string; salvo?: string }> }) {
  const { id } = await params; const query = await searchParams; const context = await getAppContext();
  if (context.status !== "ready" || !context.lawFirm || !context.member) return <AppShell memberName={null}><PageHeader title="Tarefa" description="Detalhes da tarefa." /><Card><CardContent className="p-6"><Link className="underline" href="/entrar">Entrar</Link></CardContent></Card></AppShell>;
  const supabase = await getSupabaseServerClient(); const result = supabase ? await (supabase as unknown as { from(table: string): { select(columns: string): { eq(column: string, value: string): { eq(column: string, value: string): { maybeSingle(): Promise<{ data: unknown; error: Error | null }> } } } } }).from("tasks").select("id, title, description, status, due_at, checklist, comments, legal_case_id").eq("law_firm_id", context.lawFirm.id).eq("id", id).maybeSingle() : { data: null, error: null };
  if (!result.data) return <AppShell memberName={context.member.name}><PageHeader title="Tarefa não encontrada" description="O registro não existe ou não está disponível." /><Link href="/tarefas" className="underline">Voltar para tarefas</Link></AppShell>;
  const task = result.data as { title: string; description: string | null; status: string; due_at: string | null; checklist: Array<{ id: string; title: string; done: boolean }>; comments: Array<{ id: string; body: string; author: string; createdAt: string }> ; legal_case_id: string | null };
  return <AppShell memberName={context.member.name}><div className="space-y-6"><PageHeader title={task.title} description={task.description ?? "Sem descrição"} /><div className="flex flex-wrap gap-4 text-sm text-muted-foreground"><span>Status: {task.status}</span><span>Entrega: {task.due_at ? formatDateTime(task.due_at) : "Sem prazo"}</span>{task.legal_case_id ? <Link href={`/processos/${task.legal_case_id}`} className="underline">Abrir processo vinculado</Link> : null}</div>{query.erro ? <Card className="border-destructive/30 bg-destructive/5 rounded-lg"><CardContent className="p-4 text-sm text-destructive">Não foi possível salvar a alteração.</CardContent></Card> : null}{query.salvo ? <Card className="border-[var(--chart-2)]/30 bg-[var(--chart-2)]/5 rounded-lg"><CardContent className="p-4 text-sm">Alteração salva.</CardContent></Card> : null}<div className="grid gap-6 lg:grid-cols-2"><Card className="rounded-lg"><CardHeader><CardTitle>Checklist</CardTitle><CardDescription>Itens persistidos na tarefa.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="space-y-2">{task.checklist?.map((item) => <form action={toggleChecklistItemAction} key={item.id} className="flex items-center gap-2"><input type="hidden" name="taskId" value={id} /><input type="hidden" name="itemId" value={item.id} /><button type="submit" aria-label={item.done ? "Reabrir item" : "Concluir item"} className={`size-4 rounded border ${item.done ? "bg-primary" : ""}`} /> <span className={item.done ? "text-sm line-through text-muted-foreground" : "text-sm"}>{item.title}</span></form>)}</div><form action={addChecklistItemAction} className="flex gap-2"><input type="hidden" name="taskId" value={id} /><Input name="title" placeholder="Novo item" required /><button className="rounded-lg bg-primary px-3 text-sm text-primary-foreground" type="submit">Adicionar</button></form></CardContent></Card><Card className="rounded-lg"><CardHeader><CardTitle>Comentários</CardTitle><CardDescription>Registro colaborativo da execução.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="space-y-3">{task.comments?.map((comment) => <div key={comment.id} className="border-b pb-3 last:border-0"><p className="text-sm">{comment.body}</p><p className="mt-1 text-xs text-muted-foreground">{comment.author} · {formatDateTime(comment.createdAt)}</p></div>)}</div><form action={addTaskCommentAction} className="space-y-2"><input type="hidden" name="taskId" value={id} /><Label htmlFor="body">Novo comentário</Label><textarea id="body" name="body" rows={3} className="w-full rounded-lg border border-input bg-transparent px-2.5 py-2 text-sm" required /><button className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground" type="submit">Comentar</button></form></CardContent></Card></div></div></AppShell>;
}
