-- Migration: Solo Pro — Estabilização
-- Descrição: Tabelas, RPCs, seeds e políticas RLS para o Solo Pro.
-- NÃO destrói dados existentes. Usa IF NOT EXISTS.

-- =============================================================================
-- PART 0: Protect against re-run
-- =============================================================================

BEGIN;

-- =============================================================================
-- PART 1: Add columns to law_firms (idempotent)
-- =============================================================================

ALTER TABLE public.law_firms
ADD COLUMN IF NOT EXISTS solo_pro_enabled BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS setup_diagnostic_completed_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS office_health_config JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS setup_diagnostic_answers JSONB DEFAULT '{}';

-- =============================================================================
-- PART 2: Create tables for Solo Pro features
-- =============================================================================

-- Operational rules for generating recommendations
CREATE TABLE IF NOT EXISTS public.operational_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    law_firm_id UUID REFERENCES public.law_firms(id) ON DELETE CASCADE,
    rule_key TEXT NOT NULL,
    rule_type TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    priority TEXT NOT NULL DEFAULT 'informativa',
    entity_type TEXT,
    entity_id UUID,
    action_url TEXT,
    action_label TEXT,
    enabled BOOLEAN DEFAULT true,
    version INTEGER DEFAULT 1,
    cooldown_hours INTEGER DEFAULT 24,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Operational recommendations generated by rules engine
CREATE TABLE IF NOT EXISTS public.operational_recommendations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    law_firm_id UUID REFERENCES public.law_firms(id) ON DELETE CASCADE,
    rule_id UUID REFERENCES public.operational_rules(id) ON DELETE SET NULL,
    rule_key TEXT NOT NULL,
    recommendation_type TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    priority TEXT NOT NULL DEFAULT 'informativa',
    entity_type TEXT,
    entity_id UUID,
    related_entity_name TEXT,
    reason TEXT,
    action_label TEXT,
    action_url TEXT,
    status TEXT DEFAULT 'ativa',
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    expires_at TIMESTAMP WITH TIME ZONE,
    dismissed_at TIMESTAMP WITH TIME ZONE,
    dismissed_by TEXT,
    dismissed_reason TEXT,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Recommendation dismissals tracking
CREATE TABLE IF NOT EXISTS public.recommendation_dismissals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    law_firm_id UUID REFERENCES public.law_firms(id) ON DELETE CASCADE,
    recommendation_id UUID REFERENCES public.operational_recommendations(id) ON DELETE CASCADE,
    dismissed_by UUID REFERENCES public.law_firm_members(id) ON DELETE SET NULL,
    dismissed_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Recommendation actions tracking
CREATE TABLE IF NOT EXISTS public.recommendation_actions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    law_firm_id UUID REFERENCES public.law_firms(id) ON DELETE CASCADE,
    recommendation_id UUID REFERENCES public.operational_recommendations(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    action_label TEXT,
    action_url TEXT,
    executed_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    executed_by UUID REFERENCES public.law_firm_members(id) ON DELETE SET NULL,
    result TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Recommendation preferences (for silencing rules)
CREATE TABLE IF NOT EXISTS public.recommendation_preferences (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    law_firm_id UUID REFERENCES public.law_firms(id) ON DELETE CASCADE,
    rule_key TEXT NOT NULL,
    muted BOOLEAN DEFAULT false,
    muted_at TIMESTAMP WITH TIME ZONE,
    muted_until TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UNIQUE(law_firm_id, rule_key)
);

-- Office health snapshots
CREATE TABLE IF NOT EXISTS public.office_health_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    law_firm_id UUID REFERENCES public.law_firms(id) ON DELETE CASCADE,
    snapshot_type TEXT NOT NULL DEFAULT 'daily',
    snapshot_date DATE NOT NULL,
    clients_total INTEGER DEFAULT 0,
    clients_active INTEGER DEFAULT 0,
    clients_inactive INTEGER DEFAULT 0,
    cases_active INTEGER DEFAULT 0,
    cases_pending_action INTEGER DEFAULT 0,
    cases_overdue INTEGER DEFAULT 0,
    proposals_pending INTEGER DEFAULT 0,
    proposals_expired INTEGER DEFAULT 0,
    follow_ups_pending INTEGER DEFAULT 0,
    follow_ups_overdue INTEGER DEFAULT 0,
    tasks_pending INTEGER DEFAULT 0,
    tasks_overdue INTEGER DEFAULT 0,
    deadlines_upcoming INTEGER DEFAULT 0,
    deadlines_overdue INTEGER DEFAULT 0,
    revenue_month_cents INTEGER DEFAULT 0,
    received_month_cents INTEGER DEFAULT 0,
    overdue_amount_cents INTEGER DEFAULT 0,
    expenses_month_cents INTEGER DEFAULT 0,
    recommendations_active INTEGER DEFAULT 0,
    recommendations_critical INTEGER DEFAULT 0,
    score_number INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UNIQUE(law_firm_id, snapshot_date)
);

-- Setup diagnostic questions and answers
CREATE TABLE IF NOT EXISTS public.setup_diagnostic (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    law_firm_id UUID REFERENCES public.law_firms(id) ON DELETE CASCADE,
    question_key TEXT NOT NULL,
    question_text TEXT NOT NULL,
    answer_value TEXT,
    answer_options JSONB DEFAULT '[]',
    order_index INTEGER DEFAULT 0,
    completed BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Client update schedules
CREATE TABLE IF NOT EXISTS public.client_update_schedules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    law_firm_id UUID REFERENCES public.law_firms(id) ON DELETE CASCADE,
    client_id UUID REFERENCES public.clients(id) ON DELETE CASCADE,
    legal_case_id UUID REFERENCES public.legal_cases(id) ON DELETE SET NULL,
    frequency TEXT NOT NULL DEFAULT 'mensal',
    preferred_channel TEXT DEFAULT 'email',
    responsible_member_id UUID REFERENCES public.law_firm_members(id) ON DELETE SET NULL,
    last_update_date DATE,
    next_update_date DATE,
    message_template TEXT,
    status TEXT DEFAULT 'ativo',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- =============================================================================
-- PART 3: Indexes
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_operational_rules_firm ON public.operational_rules(law_firm_id);
CREATE INDEX IF NOT EXISTS idx_operational_rules_key ON public.operational_rules(rule_key);
CREATE INDEX IF NOT EXISTS idx_operational_rules_type ON public.operational_rules(rule_type);
CREATE INDEX IF NOT EXISTS idx_operational_recommendations_firm ON public.operational_recommendations(law_firm_id);
CREATE INDEX IF NOT EXISTS idx_operational_recommendations_status ON public.operational_recommendations(status);
CREATE INDEX IF NOT EXISTS idx_operational_recommendations_priority ON public.operational_recommendations(priority);
CREATE INDEX IF NOT EXISTS idx_operational_recommendations_rule_key ON public.operational_recommendations(rule_key);
CREATE INDEX IF NOT EXISTS idx_operational_recommendations_entity ON public.operational_recommendations(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_dismissals_firm ON public.recommendation_dismissals(law_firm_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_dismissals_rec ON public.recommendation_dismissals(recommendation_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_actions_firm ON public.recommendation_actions(law_firm_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_actions_rec ON public.recommendation_actions(recommendation_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_preferences_firm ON public.recommendation_preferences(law_firm_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_preferences_key ON public.recommendation_preferences(rule_key);
CREATE INDEX IF NOT EXISTS idx_office_health_snapshots_firm ON public.office_health_snapshots(law_firm_id);
CREATE INDEX IF NOT EXISTS idx_office_health_snapshots_date ON public.office_health_snapshots(snapshot_date);
CREATE INDEX IF NOT EXISTS idx_setup_diagnostic_firm ON public.setup_diagnostic(law_firm_id);
CREATE INDEX IF NOT EXISTS idx_client_update_schedules_firm ON public.client_update_schedules(law_firm_id);
CREATE INDEX IF NOT EXISTS idx_client_update_schedules_client ON public.client_update_schedules(client_id);

-- =============================================================================
-- PART 4: RLS Policies
-- =============================================================================

ALTER TABLE public.operational_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operational_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recommendation_dismissals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recommendation_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recommendation_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.office_health_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.setup_diagnostic ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_update_schedules ENABLE ROW LEVEL SECURITY;

-- Policies: operational_rules
CREATE POLICY "operational_rules_select" ON public.operational_rules
    FOR SELECT USING (has_law_firm_access(law_firm_id) OR law_firm_id IS NULL);
CREATE POLICY "operational_rules_insert" ON public.operational_rules
    FOR INSERT WITH CHECK (has_law_firm_access(law_firm_id));
CREATE POLICY "operational_rules_update" ON public.operational_rules
    FOR UPDATE USING (has_law_firm_access(law_firm_id));
CREATE POLICY "operational_rules_delete" ON public.operational_rules
    FOR DELETE USING (has_law_firm_access(law_firm_id));

-- Policies: operational_recommendations
CREATE POLICY "operational_recommendations_select" ON public.operational_recommendations
    FOR SELECT USING (has_law_firm_access(law_firm_id));
CREATE POLICY "operational_recommendations_insert" ON public.operational_recommendations
    FOR INSERT WITH CHECK (has_law_firm_access(law_firm_id));
CREATE POLICY "operational_recommendations_update" ON public.operational_recommendations
    FOR UPDATE USING (has_law_firm_access(law_firm_id));
CREATE POLICY "operational_recommendations_delete" ON public.operational_recommendations
    FOR DELETE USING (has_law_firm_access(law_firm_id));

-- Policies: recommendation_dismissals
CREATE POLICY "recommendation_dismissals_select" ON public.recommendation_dismissals
    FOR SELECT USING (has_law_firm_access(law_firm_id));
CREATE POLICY "recommendation_dismissals_insert" ON public.recommendation_dismissals
    FOR INSERT WITH CHECK (has_law_firm_access(law_firm_id));
CREATE POLICY "recommendation_dismissals_delete" ON public.recommendation_dismissals
    FOR DELETE USING (has_law_firm_access(law_firm_id));

-- Policies: recommendation_actions
CREATE POLICY "recommendation_actions_select" ON public.recommendation_actions
    FOR SELECT USING (has_law_firm_access(law_firm_id));
CREATE POLICY "recommendation_actions_insert" ON public.recommendation_actions
    FOR INSERT WITH CHECK (has_law_firm_access(law_firm_id));
CREATE POLICY "recommendation_actions_delete" ON public.recommendation_actions
    FOR DELETE USING (has_law_firm_access(law_firm_id));

-- Policies: recommendation_preferences
CREATE POLICY "recommendation_preferences_select" ON public.recommendation_preferences
    FOR SELECT USING (has_law_firm_access(law_firm_id));
CREATE POLICY "recommendation_preferences_insert" ON public.recommendation_preferences
    FOR INSERT WITH CHECK (has_law_firm_access(law_firm_id));
CREATE POLICY "recommendation_preferences_update" ON public.recommendation_preferences
    FOR UPDATE USING (has_law_firm_access(law_firm_id));
CREATE POLICY "recommendation_preferences_delete" ON public.recommendation_preferences
    FOR DELETE USING (has_law_firm_access(law_firm_id));

-- Policies: office_health_snapshots
CREATE POLICY "office_health_snapshots_select" ON public.office_health_snapshots
    FOR SELECT USING (has_law_firm_access(law_firm_id));
CREATE POLICY "office_health_snapshots_insert" ON public.office_health_snapshots
    FOR INSERT WITH CHECK (has_law_firm_access(law_firm_id));
CREATE POLICY "office_health_snapshots_update" ON public.office_health_snapshots
    FOR UPDATE USING (has_law_firm_access(law_firm_id));
CREATE POLICY "office_health_snapshots_delete" ON public.office_health_snapshots
    FOR DELETE USING (has_law_firm_access(law_firm_id));

-- Policies: setup_diagnostic
CREATE POLICY "setup_diagnostic_select" ON public.setup_diagnostic
    FOR SELECT USING (has_law_firm_access(law_firm_id));
CREATE POLICY "setup_diagnostic_insert" ON public.setup_diagnostic
    FOR INSERT WITH CHECK (has_law_firm_access(law_firm_id));
CREATE POLICY "setup_diagnostic_update" ON public.setup_diagnostic
    FOR UPDATE USING (has_law_firm_access(law_firm_id));
CREATE POLICY "setup_diagnostic_delete" ON public.setup_diagnostic
    FOR DELETE USING (has_law_firm_access(law_firm_id));

-- Policies: client_update_schedules
CREATE POLICY "client_update_schedules_select" ON public.client_update_schedules
    FOR SELECT USING (has_law_firm_access(law_firm_id));
CREATE POLICY "client_update_schedules_insert" ON public.client_update_schedules
    FOR INSERT WITH CHECK (has_law_firm_access(law_firm_id));
CREATE POLICY "client_update_schedules_update" ON public.client_update_schedules
    FOR UPDATE USING (has_law_firm_access(law_firm_id));
CREATE POLICY "client_update_schedules_delete" ON public.client_update_schedules
    FOR DELETE USING (has_law_firm_access(law_firm_id));

-- =============================================================================
-- PART 5: Seed operational rules (as platform global defaults)
-- Use law_firm_id = NULL for global defaults; RLS policy allows SELECT when NULL.
-- =============================================================================

INSERT INTO public.operational_rules (law_firm_id, rule_key, rule_type, title, description, priority, enabled) VALUES
(NULL, 'leads_without_return', 'clientes', 'Leads sem retorno', 'Leads sem resposta há mais de 2 dias.', 'atencao', true),
(NULL, 'proposals_expiring_soon', 'propostas', 'Propostas prestes a vencer', 'Propostas de honorários com vencimento próximo ou já vencidas.', 'importante', true),
(NULL, 'cases_without_next_action', 'juridico', 'Processos sem próxima ação', 'Casos ativos que não possuem próxima ação ou prazo definido.', 'importante', true),
(NULL, 'overdue_installments_no_charge', 'financeiro', 'Parcelas atrasadas sem cobrança', 'Existem parcelas atrasadas sem registro de cobrança.', 'critica', true),
(NULL, 'monthly_recovery_insufficient', 'financeiro', 'Baixa recebimento mensal', 'O valor recebido no mês está abaixo do esperado.', 'atencao', true),
(NULL, 'referral_clients_this_quarter', 'clientes', 'Clientes por indicação', 'Você recebeu clientes por indicação neste trimestre.', 'informativa', true),
(NULL, 'pending_documents_audience', 'juridico', 'Documentos pendentes para audiência', 'Existem documentos pendentes para audiência da próxima semana.', 'importante', true),
(NULL, 'tasks_over_capacity', 'produtividade', 'Tarefas acima da capacidade', 'Você está com mais tarefas previstas do que sua capacidade diária.', 'importante', true),
(NULL, 'client_no_update_30days', 'clientes', 'Cliente sem atualização há 30 dias', 'O cliente não recebe uma atualização há 30 dias.', 'atencao', true),
(NULL, 'contract_active_no_installment', 'financeiro', 'Contrato ativo sem parcela gerada', 'O contrato está ativo, mas ainda não há parcela gerada.', 'importante', true),
(NULL, 'deadline_without_review', 'juridico', 'Prazo cadastrado sem revisão', 'Existe prazo cadastrado sem revisão.', 'atencao', true),
(NULL, 'proposal_template_not_configured', 'configuracao', 'Modelo de proposta não configurado', 'Você ainda não configurou um modelo de proposta.', 'informativa', true)
ON CONFLICT DO NOTHING;

-- =============================================================================
-- PART 6: Seed setup diagnostic questions (platform defaults)
-- =============================================================================

INSERT INTO public.setup_diagnostic (law_firm_id, question_key, question_text, answer_options, order_index) VALUES
(NULL, 'practice_areas', 'Em quais áreas atua?', '["trabalhista", "previdenciario", "familia", "consumidor", "civel", "criminal", "imobiliario", "empresarial", "tributario", "administrativo"]', 1),
(NULL, 'has_clients', 'Já possui clientes?', '["sim", "nao"]', 2),
(NULL, 'has_cases', 'Já possui processos?', '["sim", "nao"]', 3),
(NULL, 'practice_type', 'Trabalha somente com atendimento particular?', '["sim", "nao", "parcialmente"]', 4),
(NULL, 'charging_model', 'Cobrar valor fixo, parcelas, êxito ou mensalidade?', '["fixo", "parcelas", "exito", "mensalidade", "misto"]', 5),
(NULL, 'has_recurring_expenses', 'Possui despesas recorrentes?', '["sim", "nao"]', 6),
(NULL, 'uses_spreadsheet', 'Usa planilhas?', '["sim", "nao", "pretendo usar"]', 7),
(NULL, 'uses_external_calendar', 'Usa agenda externa?', '["sim", "nao", "pretendo usar"]', 8),
(NULL, 'has_website', 'Possui site?', '["sim", "nao", "pretendo criar"]', 9),
(NULL, 'receives_referrals', 'Recebe clientes por indicação?', '["sim", "nao", "parcialmente"]', 10),
(NULL, 'work_location', 'Trabalha em casa, coworking ou escritório?', '["casa", "coworking", "escritorio"]', 11),
(NULL, 'intends_hire', 'Pretende contratar alguém?', '["sim", "nao", "futuramente"]', 12),
(NULL, 'hours_per_week', 'Quantas horas por semana pretende trabalhar?', '["20", "30", "40", "50", "60"]', 13),
(NULL, 'monthly_revenue_goal', 'Qual é sua meta mensal de receita?', '["ate_5000", "5000_10000", "10000_20000", "20000_30000", "acima_30000"]', 14),
(NULL, 'new_clients_goal', 'Qual é sua meta de novos clientes?', '["ate_2", "3_5", "6_10", "acima_10"]', 15),
(NULL, 'biggest_problem', 'Qual é seu maior problema atual?', '["falta_clientes", "perda_prazos", "falta_cobranca", "desorganizacao", "falta_tempo", "falta_documento"]', 16)
ON CONFLICT DO NOTHING;

-- =============================================================================
-- PART 7: RPC — calculate_office_health_score
-- =============================================================================

CREATE OR REPLACE FUNCTION public.calculate_office_health_score(
    p_law_firm_id UUID
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_score INTEGER := 100;
    v_overdue_deadlines INTEGER;
    v_overdue_installments INTEGER;
    v_pending_follow_ups INTEGER;
    v_pending_tasks INTEGER;
    v_proposals_pending INTEGER;
    v_active_cases INTEGER;
BEGIN
    -- Deduct for overdue deadlines (critical, max 25)
    SELECT COUNT(*) INTO v_overdue_deadlines
    FROM public.deadlines
    WHERE law_firm_id = p_law_firm_id
    AND status IN ('pendente', 'em_andamento')
    AND due_date < CURRENT_DATE;
    v_score := v_score - LEAST(v_overdue_deadlines * 5, 25);

    -- Deduct for overdue installments (critical, max 20)
    SELECT COUNT(*) INTO v_overdue_installments
    FROM public.installments
    WHERE law_firm_id = p_law_firm_id
    AND status IN ('pendente', 'vencendo', 'atrasada', 'parcialmente_paga')
    AND due_date < CURRENT_DATE;
    v_score := v_score - LEAST(v_overdue_installments * 5, 20);

    -- Deduct for pending follow-ups (attention, max 15)
    SELECT COUNT(*) INTO v_pending_follow_ups
    FROM public.follow_ups
    WHERE law_firm_id = p_law_firm_id
    AND status = 'pendente'
    AND scheduled_date <= CURRENT_DATE;
    v_score := v_score - LEAST(v_pending_follow_ups * 3, 15);

    -- Deduct for pending tasks (attention, max 15)
    SELECT COUNT(*) INTO v_pending_tasks
    FROM public.tasks
    WHERE law_firm_id = p_law_firm_id
    AND status IN ('pendente', 'em_andamento')
    AND (due_at IS NULL OR due_at <= CURRENT_DATE + INTERVAL '3 days');
    v_score := v_score - LEAST(v_pending_tasks * 2, 15);

    -- Deduct for pending proposals (important, max 15)
    SELECT COUNT(*) INTO v_proposals_pending
    FROM public.fee_proposals
    WHERE law_firm_id = p_law_firm_id
    AND status = 'rascunho';
    v_score := v_score - LEAST(v_proposals_pending * 3, 15);

    -- Add bonus for active cases (max 5)
    SELECT COUNT(*) INTO v_active_cases
    FROM public.legal_cases
    WHERE law_firm_id = p_law_firm_id
    AND status IN ('em_andamento', 'ativo');
    IF v_active_cases > 5 THEN
        v_score := v_score + 5;
    END IF;

    v_score := GREATEST(0, LEAST(100, v_score));
    RETURN v_score;
END;
$$;

-- =============================================================================
-- PART 8: RPC — generate_office_health_snapshot (idempotent)
-- =============================================================================

CREATE OR REPLACE FUNCTION public.generate_office_health_snapshot(
    p_law_firm_id UUID,
    p_snapshot_date DATE DEFAULT CURRENT_DATE
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_clients_total INTEGER;
    v_clients_active INTEGER;
    v_clients_inactive INTEGER;
    v_cases_active INTEGER;
    v_proposals_pending INTEGER;
    v_proposals_expired INTEGER;
    v_follow_ups_pending INTEGER;
    v_follow_ups_overdue INTEGER;
    v_tasks_pending INTEGER;
    v_tasks_overdue INTEGER;
    v_deadlines_upcoming INTEGER;
    v_deadlines_overdue INTEGER;
    v_revenue_month_cents INTEGER;
    v_received_month_cents INTEGER;
    v_overdue_amount_cents INTEGER;
    v_expenses_month_cents INTEGER;
    v_recommendations_active INTEGER;
    v_recommendations_critical INTEGER;
    v_score INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_clients_total FROM public.clients WHERE law_firm_id = p_law_firm_id;
    SELECT COUNT(*) INTO v_clients_active FROM public.clients WHERE law_firm_id = p_law_firm_id AND status = 'ativo';
    v_clients_inactive := v_clients_total - v_clients_active;

    SELECT COUNT(*) INTO v_cases_active FROM public.legal_cases WHERE law_firm_id = p_law_firm_id AND status IN ('em_andamento', 'ativo');

    SELECT COUNT(*) INTO v_proposals_pending FROM public.fee_proposals WHERE law_firm_id = p_law_firm_id AND status = 'rascunho';
    SELECT COUNT(*) INTO v_proposals_expired FROM public.fee_proposals WHERE law_firm_id = p_law_firm_id AND status = 'enviada' AND created_at < CURRENT_DATE - INTERVAL '15 days';

    SELECT COUNT(*) INTO v_follow_ups_pending FROM public.follow_ups WHERE law_firm_id = p_law_firm_id AND status = 'pendente';
    SELECT COUNT(*) INTO v_follow_ups_overdue FROM public.follow_ups WHERE law_firm_id = p_law_firm_id AND status = 'pendente' AND scheduled_date < CURRENT_DATE;

    SELECT COUNT(*) INTO v_tasks_pending FROM public.tasks WHERE law_firm_id = p_law_firm_id AND status IN ('pendente', 'em_andamento');
    SELECT COUNT(*) INTO v_tasks_overdue FROM public.tasks WHERE law_firm_id = p_law_firm_id AND status IN ('pendente', 'em_andamento') AND due_at < CURRENT_DATE;

    SELECT COUNT(*) INTO v_deadlines_upcoming FROM public.deadlines WHERE law_firm_id = p_law_firm_id AND status IN ('pendente', 'em_andamento') AND due_date BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL '7 days';
    SELECT COUNT(*) INTO v_deadlines_overdue FROM public.deadlines WHERE law_firm_id = p_law_firm_id AND status IN ('pendente', 'em_andamento') AND due_date < CURRENT_DATE;

    SELECT COALESCE(SUM(final_amount_cents), 0) INTO v_revenue_month_cents FROM public.installments WHERE law_firm_id = p_law_firm_id AND due_date >= DATE_TRUNC('month', CURRENT_DATE) AND due_date <= DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month' - INTERVAL '1 day';
    SELECT COALESCE(SUM(amount_cents), 0) INTO v_received_month_cents FROM public.payments WHERE law_firm_id = p_law_firm_id AND paid_at >= DATE_TRUNC('month', CURRENT_DATE) AND paid_at <= DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month' - INTERVAL '1 day';
    SELECT COALESCE(SUM(final_amount_cents - COALESCE(paid_amount_cents, 0)), 0) INTO v_overdue_amount_cents FROM public.installments WHERE law_firm_id = p_law_firm_id AND due_date < CURRENT_DATE AND status IN ('pendente', 'atrasada', 'parcialmente_paga');
    SELECT COALESCE(SUM(amount_cents), 0) INTO v_expenses_month_cents FROM public.expenses WHERE law_firm_id = p_law_firm_id AND due_date >= DATE_TRUNC('month', CURRENT_DATE) AND due_date <= DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month' - INTERVAL '1 day';

    SELECT COUNT(*) INTO v_recommendations_active FROM public.operational_recommendations WHERE law_firm_id = p_law_firm_id AND status = 'ativa';
    SELECT COUNT(*) INTO v_recommendations_critical FROM public.operational_recommendations WHERE law_firm_id = p_law_firm_id AND status = 'ativa' AND priority = 'critica';

    v_score := public.calculate_office_health_score(p_law_firm_id);

    INSERT INTO public.office_health_snapshots (
        law_firm_id, snapshot_type, snapshot_date, clients_total, clients_active, clients_inactive,
        cases_active, proposals_pending, proposals_expired,
        follow_ups_pending, follow_ups_overdue, tasks_pending, tasks_overdue,
        deadlines_upcoming, deadlines_overdue, revenue_month_cents, received_month_cents,
        overdue_amount_cents, expenses_month_cents, recommendations_active, recommendations_critical,
        score_number
    ) VALUES (
        p_law_firm_id, 'daily', p_snapshot_date, v_clients_total, v_clients_active, v_clients_inactive,
        v_cases_active, v_proposals_pending, v_proposals_expired,
        v_follow_ups_pending, v_follow_ups_overdue, v_tasks_pending, v_tasks_overdue,
        v_deadlines_upcoming, v_deadlines_overdue, v_revenue_month_cents, v_received_month_cents,
        v_overdue_amount_cents, v_expenses_month_cents, v_recommendations_active, v_recommendations_critical,
        v_score
    )
    ON CONFLICT (law_firm_id, snapshot_date) DO UPDATE SET
        clients_total = v_clients_total,
        clients_active = v_clients_active,
        clients_inactive = v_clients_inactive,
        cases_active = v_cases_active,
        proposals_pending = v_proposals_pending,
        proposals_expired = v_proposals_expired,
        follow_ups_pending = v_follow_ups_pending,
        follow_ups_overdue = v_follow_ups_overdue,
        tasks_pending = v_tasks_pending,
        tasks_overdue = v_tasks_overdue,
        deadlines_upcoming = v_deadlines_upcoming,
        deadlines_overdue = v_deadlines_overdue,
        revenue_month_cents = v_revenue_month_cents,
        received_month_cents = v_received_month_cents,
        overdue_amount_cents = v_overdue_amount_cents,
        expenses_month_cents = v_expenses_month_cents,
        recommendations_active = v_recommendations_active,
        recommendations_critical = v_recommendations_critical,
        score_number = v_score,
        updated_at = now();
END;
$$;

-- =============================================================================
-- PART 9: RPC — generate_operational_recommendations (idempotent, safe)
-- =============================================================================

CREATE OR REPLACE FUNCTION public.generate_operational_recommendations(
    p_law_firm_id UUID
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_rule RECORD;
    v_count INTEGER := 0;
    v_condition_met BOOLEAN;
    v_muted BOOLEAN;
    v_count_val INTEGER;
    v_last_generated TIMESTAMPTZ;
BEGIN
    FOR v_rule IN
        SELECT * FROM public.operational_rules
        WHERE (law_firm_id = p_law_firm_id OR law_firm_id IS NULL)
        AND enabled = true
        ORDER BY priority, created_at
    LOOP
        SELECT muted INTO v_muted FROM public.recommendation_preferences
        WHERE law_firm_id = p_law_firm_id AND rule_key = v_rule.rule_key;

        IF v_muted = true THEN CONTINUE; END IF;

        v_condition_met := false;
        v_count_val := 0;

        CASE v_rule.rule_key
            WHEN 'leads_without_return' THEN
                SELECT COUNT(*) INTO v_count_val FROM public.leads
                WHERE law_firm_id = p_law_firm_id
                AND status IN ('novo', 'aguardando_retorno')
                AND created_at < CURRENT_DATE - INTERVAL '2 days';
                v_condition_met := v_count_val > 0;
            WHEN 'proposals_expiring_soon' THEN
                SELECT COUNT(*) INTO v_count_val FROM public.fee_proposals
                WHERE law_firm_id = p_law_firm_id
                AND status = 'enviada'
                AND created_at + (validity_days || ' days')::INTERVAL < CURRENT_DATE + INTERVAL '2 days';
                v_condition_met := v_count_val > 0;
            WHEN 'cases_without_next_action' THEN
                SELECT COUNT(*) INTO v_count_val FROM public.legal_cases
                WHERE law_firm_id = p_law_firm_id
                AND status IN ('em_andamento', 'ativo')
                AND updated_at < CURRENT_DATE - INTERVAL '30 days';
                v_condition_met := v_count_val > 0;
            WHEN 'overdue_installments_no_charge' THEN
                SELECT COUNT(*) INTO v_count_val FROM public.installments
                WHERE law_firm_id = p_law_firm_id
                AND status IN ('pendente', 'atrasada', 'parcialmente_paga')
                AND due_date < CURRENT_DATE
                AND (paid_amount_cents IS NULL OR paid_amount_cents = 0);
                v_condition_met := v_count_val > 0;
            WHEN 'referral_clients_this_quarter' THEN
                SELECT COUNT(*) INTO v_count_val FROM public.clients
                WHERE law_firm_id = p_law_firm_id
                AND source = 'indicacao'
                AND created_at >= DATE_TRUNC('quarter', CURRENT_DATE);
                v_condition_met := v_count_val > 0;
            WHEN 'pending_documents_audience' THEN
                SELECT COUNT(*) INTO v_count_val FROM public.deadlines
                WHERE law_firm_id = p_law_firm_id
                AND title ILIKE '%audiência%'
                AND due_date BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL '7 days'
                AND status IN ('pendente', 'em_andamento');
                v_condition_met := v_count_val > 0;
            WHEN 'tasks_over_capacity' THEN
                SELECT COUNT(*) INTO v_count_val FROM public.tasks
                WHERE law_firm_id = p_law_firm_id
                AND status IN ('pendente', 'em_andamento');
                v_condition_met := v_count_val > 20;
            WHEN 'client_no_update_30days' THEN
                SELECT COUNT(*) INTO v_count_val FROM public.clients
                WHERE law_firm_id = p_law_firm_id
                AND status = 'ativo'
                AND updated_at < CURRENT_DATE - INTERVAL '30 days';
                v_condition_met := v_count_val > 0;
            WHEN 'contract_active_no_installment' THEN
                SELECT COUNT(*) INTO v_count_val FROM public.contracts c
                WHERE c.law_firm_id = p_law_firm_id
                AND c.status = 'ativo'
                AND NOT EXISTS (
                    SELECT 1 FROM public.installments i WHERE i.contract_id = c.id
                );
                v_condition_met := v_count_val > 0;
            WHEN 'deadline_without_review' THEN
                SELECT COUNT(*) INTO v_count_val FROM public.deadlines
                WHERE law_firm_id = p_law_firm_id
                AND status = 'pendente'
                AND due_date > CURRENT_DATE + INTERVAL '30 days';
                v_condition_met := v_count_val > 0;
            WHEN 'proposal_template_not_configured' THEN
                SELECT COUNT(*) INTO v_count_val FROM public.fee_proposals
                WHERE law_firm_id = p_law_firm_id;
                v_condition_met := v_count_val = 0;
            ELSE
                v_condition_met := false;
        END CASE;

        IF v_condition_met THEN
            IF NOT EXISTS (
                SELECT 1 FROM public.operational_recommendations
                WHERE law_firm_id = p_law_firm_id
                AND rule_key = v_rule.rule_key
                AND status IN ('ativa', 'visualizada')
            ) THEN
                INSERT INTO public.operational_recommendations (
                    law_firm_id, rule_id, rule_key, recommendation_type, title, description,
                    priority, action_label, action_url, status
                ) VALUES (
                    p_law_firm_id, v_rule.id, v_rule.rule_key, v_rule.rule_type, v_rule.title, v_rule.description,
                    v_rule.priority, 'Ver detalhes', '/meu-escritorio', 'ativa'
                );
                v_count := v_count + 1;
            END IF;
        ELSE
            UPDATE public.operational_recommendations
            SET status = 'concluida', completed_at = now(), updated_at = now()
            WHERE law_firm_id = p_law_firm_id
            AND rule_key = v_rule.rule_key
            AND status IN ('ativa', 'visualizada');
        END IF;
    END LOOP;

    RETURN v_count;
END;
$$;

-- =============================================================================
-- PART 10: RPC — save_setup_diagnostic_answers (safe, tenant-isolated)
-- =============================================================================

CREATE OR REPLACE FUNCTION public.save_setup_diagnostic_answers(
    p_law_firm_id UUID,
    p_answers JSONB
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    UPDATE public.law_firms
    SET setup_diagnostic_answers = p_answers,
        setup_diagnostic_completed_at = now(),
        updated_at = now()
    WHERE id = p_law_firm_id;

    DELETE FROM public.setup_diagnostic WHERE law_firm_id = p_law_firm_id;

    INSERT INTO public.setup_diagnostic (law_firm_id, question_key, answer_value, completed)
    SELECT p_law_firm_id, key::text, value::text, true
    FROM jsonb_each_text(p_answers);
END;
$$;

-- =============================================================================
-- PART 11: View — office_health_summary
-- =============================================================================

CREATE OR REPLACE VIEW public.office_health_summary AS
SELECT
    oh.law_firm_id,
    oh.snapshot_date,
    oh.score_number,
    oh.cases_active,
    oh.follow_ups_pending,
    oh.follow_ups_overdue,
    oh.tasks_overdue,
    oh.deadlines_overdue,
    oh.received_month_cents,
    oh.overdue_amount_cents,
    oh.recommendations_critical,
    oh.created_at,
    lf.name as firm_name
FROM public.office_health_snapshots oh
JOIN public.law_firms lf ON lf.id = oh.law_firm_id
WHERE oh.snapshot_date = CURRENT_DATE
ORDER BY oh.created_at DESC;

-- =============================================================================
-- DONE
-- =============================================================================

COMMIT;