import type { ProposalEventType, ProposalOriginType, ProposalStatus } from "./status";
export interface ProposalCommercialSummary { currency: string; subtotalCents: number; discountCents: number; totalCents: number; entryAmountCents: number; installmentCount: number; installmentAmountCents: number; recurringAmountCents: number; recurringMonths: number; successFeeBps: number; }
export interface ProposalPaymentTerms extends Record<string, unknown> { description?: string; installments?: number; dueDay?: number; methods?: string[]; }
export interface ProposalPricingSnapshot { pricingScenarioId: string; pricingVersionId: string; pricingVersionNumber: number; pricingEngineVersion?: string; pricingSchemaVersion?: number; serviceId?: string; serviceName?: string; scenarioType: string; currency: string; summary: ProposalCommercialSummary; items: Array<{ itemType: string; description: string; quantity: number; unitAmountCents: number; totalAmountCents: number }>; snapshotAt: string; sourceVersionHash?: string; }
export interface CommercialProposal { id: string; lawFirmId: string; title: string; status: ProposalStatus; originType: ProposalOriginType; currency: string; activeVersionId: string | null; validUntil: string | null; createdAt: string; updatedAt: string; }
export interface CommercialProposalVersion { id: string; proposalId: string; versionNumber: number; schemaVersion: number; title: string; currency: string; commercialSummary: ProposalCommercialSummary; paymentTerms: ProposalPaymentTerms; contentHash: string; pricingSnapshot?: ProposalPricingSnapshot; createdAt: string; }
export interface CommercialProposalSection { id: string; proposalVersionId: string; sectionType: string; title: string | null; bodyMarkdown: string | null; orderIndex: number; isRequired: boolean; }
export interface CommercialProposalItem { id: string; proposalVersionId: string; itemType: string; description: string; quantity: number; unitAmountCents: number; totalAmountCents: number; isOptional: boolean; isIncluded: boolean; orderIndex: number; metadata?: Record<string, unknown>; }
export interface CommercialProposalRecipient { id: string; proposalId: string; recipientType: string; name: string; email?: string; phone?: string; companyName?: string; isPrimary: boolean; }
export interface CommercialProposalEvent { id: string; proposalId: string; proposalVersionId?: string; actorId?: string; eventType: ProposalEventType; metadata: Record<string, unknown>; createdAt: string; }
