"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Check, ChevronDown, ChevronUp, CirclePlus, Save, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { createProposalVersionAction, transitionProposalStatusAction, upsertProposalRecipientAction } from "@/lib/proposals/application/actions";
import type { ProposalVersionDraftDTO } from "@/lib/proposals/application/dto";

type BuilderProps = { proposalId: string; expectedUpdatedAt: string; draft: ProposalVersionDraftDTO; canWrite: boolean; activeVersionId?: string | null };
const labels: Record<string, string> = { introduction: "Introdução", scope: "Escopo", deliverables: "Entregáveis", exclusions: "Exclusões", responsibilities: "Responsabilidades", schedule: "Cronograma", fees: "Honorários", payment_terms: "Condições de pagamento", success_fee: "Êxito", validity: "Validade", confidentiality: "Confidencialidade", observations: "Observações", conclusion: "Conclusão" };
const normalizeUpdatedAt = (value: string) => { const normalized = value.trim().replace(" ", "T"); if (normalized.endsWith("Z")) return normalized; if (normalized.endsWith("+00:00")) return `${normalized.slice(0, -6)}Z`; if (normalized.endsWith("+00")) return `${normalized.slice(0, -3)}Z`; const date = new Date(normalized); return Number.isNaN(date.getTime()) ? value : date.toISOString(); };

export function ProposalBuilder({ proposalId, expectedUpdatedAt, draft: initialDraft, canWrite, activeVersionId }: BuilderProps) {
  const router = useRouter(); const [draft, setDraft] = useState(initialDraft); const [updatedAt, setUpdatedAt] = useState(expectedUpdatedAt); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null); const [recipient, setRecipient] = useState({ name: "", email: "", phone: "" });
  const readiness = useMemo(() => { const pending: string[] = []; if (!draft.title.trim()) pending.push("title"); if (!activeVersionId) pending.push("activeVersion"); if (!draft.sections.some((s) => s.sectionType === "fees")) pending.push("feesSection"); if (!draft.sections.some((s) => s.sectionType === "validity")) pending.push("validitySection"); if (!draft.items.some((i) => i.isIncluded && i.description.trim())) pending.push("items"); if (draft.summary.totalCents <= 0) pending.push("total"); if (!draft.currency) pending.push("currency"); return pending; }, [draft, activeVersionId]);
  const set = (patch: Partial<ProposalVersionDraftDTO>) => setDraft((value) => ({ ...value, ...patch }));
  const updateSection = (index: number, patch: Record<string, unknown>) => set({ sections: draft.sections.map((section, i) => i === index ? { ...section, ...patch } : section) });
  const updateItem = (index: number, patch: Record<string, unknown>) => {
    const items = draft.items.map((item, i) => i === index ? { ...item, ...patch } : item);
    const subtotalCents = items.filter((item) => item.isIncluded).reduce((total, item) => total + item.totalAmountCents, 0);
    set({ items, summary: { ...draft.summary, subtotalCents, totalCents: subtotalCents - draft.summary.discountCents } });
  };
  async function save() { setSaving(true); setMessage(null); const result = await createProposalVersionAction({ proposalId, expectedUpdatedAt: normalizeUpdatedAt(updatedAt), draft: { ...draft, summary: { ...draft.summary, currency: draft.currency } } as never }); setSaving(false); if (!("data" in result) || !result.data) { setMessage(result.error?.message ?? "Não foi possível salvar."); return; } setUpdatedAt(normalizeUpdatedAt(result.data.updatedAt)); setMessage("Nova versão salva com segurança."); router.refresh(); }
  async function markReady() { setMessage(null); const result = await transitionProposalStatusAction({ proposalId, to: "ready", expectedUpdatedAt: updatedAt }); if (!("data" in result) || !result.data) setMessage(result.error?.message ?? "Não foi possível alterar o status."); else { setUpdatedAt(result.data.updatedAt); setMessage("Proposta marcada como pronta."); router.refresh(); } }
  async function addRecipient() { if (!recipient.name.trim()) return; const result = await upsertProposalRecipientAction({ proposalId, recipientType: "other", name: recipient.name, email: recipient.email || null, phone: recipient.phone || null, isPrimary: true }); if (!("data" in result) || !result.data) setMessage(result.error?.message ?? "Não foi possível adicionar."); else { setRecipient({ name: "", email: "", phone: "" }); setMessage("Destinatário adicionado."); router.refresh(); } }
  return <div data-testid="proposal-builder" data-expected-updated-at={updatedAt} className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
    <div className="space-y-5">
      <Card><CardHeader><CardTitle>Identificação comercial</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><label className="space-y-1 sm:col-span-2"><span className="text-xs font-medium">Título</span><Input value={draft.title} disabled={!canWrite} onChange={(e) => set({ title: e.target.value })} /></label><label className="space-y-1"><span className="text-xs font-medium">Moeda</span><Input value={draft.currency} maxLength={3} disabled={!canWrite} onChange={(e) => set({ currency: e.target.value.toUpperCase() })} /></label><label className="space-y-1"><span className="text-xs font-medium">Validade em dias</span><Input type="number" value={draft.validityDays ?? ""} disabled={!canWrite} onChange={(e) => set({ validityDays: e.target.value ? Number(e.target.value) : null })} /></label></CardContent></Card>
      <Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Conteúdo por blocos</CardTitle>{canWrite && <Button variant="outline" onClick={() => set({ sections: [...draft.sections, { sectionType: "observations", title: "Observações", bodyMarkdown: "", orderIndex: draft.sections.length, isRequired: false }] })}><CirclePlus /> Seção</Button>}</div></CardHeader><CardContent className="space-y-3">{draft.sections.map((section, index) => <div key={`${section.sectionType}-${index}`} className="rounded-lg border p-3"><div className="flex items-center gap-2"><Input className="font-medium" value={section.title ?? labels[section.sectionType] ?? section.sectionType} disabled={!canWrite} onChange={(e) => updateSection(index, { title: e.target.value })} /><span className="text-xs text-muted-foreground">{labels[section.sectionType] ?? "Personalizada"}</span>{canWrite && <><Button size="icon-sm" variant="ghost" aria-label="Subir seção" disabled={index === 0} onClick={() => { const sections = [...draft.sections]; [sections[index - 1], sections[index]] = [sections[index], sections[index - 1]]; set({ sections }); }}><ChevronUp /></Button><Button size="icon-sm" variant="ghost" aria-label="Descer seção" disabled={index === draft.sections.length - 1} onClick={() => { const sections = [...draft.sections]; [sections[index], sections[index + 1]] = [sections[index + 1], sections[index]]; set({ sections }); }}><ChevronDown /></Button><Button size="icon-sm" variant="ghost" aria-label="Remover seção" onClick={() => set({ sections: draft.sections.filter((_, i) => i !== index) })}><Trash2 /></Button></>}</div><textarea className="mt-3 min-h-24 w-full rounded-lg border bg-transparent p-2.5 text-sm outline-none focus-visible:ring-3 focus-visible:ring-ring/50" value={section.bodyMarkdown ?? ""} disabled={!canWrite} onChange={(e) => updateSection(index, { bodyMarkdown: e.target.value })} placeholder="Escreva em Markdown..." /></div>)}</CardContent></Card>
      <Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Itens comerciais</CardTitle>{canWrite && <Button variant="outline" onClick={() => set({ items: [...draft.items, { itemType: "service", description: "", quantity: 1, unitAmountCents: 0, totalAmountCents: 0, isOptional: false, isIncluded: true, orderIndex: draft.items.length, metadata: {} }] })}><CirclePlus /> Item</Button>}</div></CardHeader><CardContent className="space-y-3">{draft.items.map((item, index) => <div key={`${item.itemType}-${index}`} className="grid gap-2 rounded-lg border p-3 sm:grid-cols-[1fr_110px_140px_auto]"><Input className="sm:col-span-2" placeholder="Descrição" value={item.description} disabled={!canWrite} onChange={(e) => updateItem(index, { description: e.target.value })} /><Input type="number" placeholder="Quantidade" value={item.quantity} disabled={!canWrite} onChange={(e) => { const quantity = Number(e.target.value); updateItem(index, { quantity, totalAmountCents: Math.round(quantity * item.unitAmountCents) }); }} /><Input type="number" placeholder="Valor em centavos" value={item.unitAmountCents} disabled={!canWrite} onChange={(e) => { const unitAmountCents = Number(e.target.value); updateItem(index, { unitAmountCents, totalAmountCents: Math.round(unitAmountCents * item.quantity) }); }} />{canWrite && <Button size="icon" variant="ghost" aria-label="Remover item" onClick={() => set({ items: draft.items.filter((_, i) => i !== index) })}><Trash2 /></Button>}</div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Destinatário principal</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3"><Input placeholder="Nome" value={recipient.name} disabled={!canWrite} onChange={(e) => setRecipient({ ...recipient, name: e.target.value })} /><Input placeholder="E-mail" type="email" value={recipient.email} disabled={!canWrite} onChange={(e) => setRecipient({ ...recipient, email: e.target.value })} /><div className="flex gap-2"><Input placeholder="Telefone" value={recipient.phone} disabled={!canWrite} onChange={(e) => setRecipient({ ...recipient, phone: e.target.value })} />{canWrite && <Button size="icon" aria-label="Adicionar destinatário" onClick={addRecipient}><CirclePlus /></Button>}</div></CardContent></Card>
    </div>
    <aside className="space-y-5 xl:sticky xl:top-6 xl:self-start"><Card><CardHeader><CardTitle>Prontidão da proposta</CardTitle></CardHeader><CardContent className="space-y-3">{readiness.length === 0 ? <p className="flex items-center gap-2 text-sm text-emerald-600"><Check /> Pronta para ativação.</p> : <ul className="space-y-2 text-sm text-muted-foreground">{readiness.map((item) => <li key={item}>• {({ title: "Informe o título", activeVersion: "Ative uma versão", feesSection: "Inclua Honorários", validitySection: "Inclua Validade", items: "Adicione um item incluído", total: "Informe um total maior que zero", currency: "Informe a moeda" } as Record<string, string>)[item] ?? item}</li>)}</ul>}{canWrite && <Button className="w-full" disabled={saving || readiness.length > 0} onClick={markReady}>Marcar como pronta</Button>}</CardContent></Card><Card><CardHeader><CardTitle>Resumo financeiro</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><div className="flex justify-between"><span>Subtotal</span><strong>R$ {(draft.summary.subtotalCents / 100).toFixed(2).replace(".", ",")}</strong></div><div className="flex justify-between"><span>Desconto</span><strong>R$ {(draft.summary.discountCents / 100).toFixed(2).replace(".", ",")}</strong></div><div className="flex justify-between border-t pt-2 text-base"><span>Total</span><strong>R$ {(draft.summary.totalCents / 100).toFixed(2).replace(".", ",")}</strong></div>{canWrite && <Button className="mt-3 w-full" onClick={save} disabled={saving}><Save /> {saving ? "Salvando..." : "Salvar nova versão"}</Button>}{message && <p role="status" aria-live="polite" className="text-xs text-muted-foreground">{message}</p>}</CardContent></Card></aside>
  </div>;
}
