"use client";
import Link from "next/link";
import { Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import type { ProposalListDTO } from "@/lib/proposals/application/dto";
const statusLabels: Record<string, string> = { draft: "Rascunho", ready: "Pronta", sent: "Enviada", viewed: "Visualizada", accepted: "Aceita", rejected: "Recusada", expired: "Expirada", cancelled: "Cancelada", superseded: "Substituída", archived: "Arquivada" };
export function ProposalsList({ proposals }: { proposals: ProposalListDTO[] }) { const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const filtered = useMemo(() => proposals.filter((p) => (!query || p.title.toLowerCase().includes(query.toLowerCase())) && (status === "all" || p.status === status)), [proposals, query, status]); return <Card><CardContent className="space-y-4 p-4"><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-2.5 top-2 size-4 text-muted-foreground" /><Input className="pl-8" placeholder="Buscar por título" value={query} onChange={(e) => setQuery(e.target.value)} /></div><select className="h-8 rounded-lg border bg-background px-2 text-sm" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">Todos os status</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>{filtered.length === 0 ? <div className="rounded-lg border border-dashed p-10 text-center text-sm text-muted-foreground">{proposals.length ? "Nenhuma proposta corresponde aos filtros." : "Nenhuma proposta criada ainda."}</div> : <div className="divide-y">{filtered.map((proposal) => <Link key={proposal.id} href={`/propostas/${proposal.id}`} className="grid gap-2 py-4 transition hover:bg-muted/40 sm:grid-cols-[minmax(0,1fr)_120px_120px_160px] sm:items-center"><div><p className="font-medium">{proposal.title}</p><p className="text-xs text-muted-foreground">Origem: {proposal.originType === "pricing_scenario" ? "Simulador" : proposal.originType === "duplicated" ? "Duplicada" : "Manual"}</p></div><span className="text-sm">{statusLabels[proposal.status]}</span><span className="text-sm">Versão {proposal.activeVersionId ? "ativa" : "-"}</span><span className="text-xs text-muted-foreground">Atualizada em {new Date(proposal.updatedAt).toLocaleDateString("pt-BR")}</span></Link>)}</div>}</CardContent></Card>; }
