"use client";

import { useState } from "react";
import { Check, Copy, Link2, RefreshCw, ShieldOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogClose, DialogDescription, DialogPopup, DialogTitle } from "@/components/ui/dialog";
import { ConfirmDialog } from "@/components/confirm-dialog";
import { createProposalPublicLinkAction, revokeProposalPublicLinkAction, rotateProposalPublicLinkAction } from "@/lib/proposals/public-link-actions";

type LinkStatus = { linkId: string; proposalId: string; proposalVersionId: string; status: string; expiresAt: string | null; activatedAt: string; revokedAt: string | null; createdAt: string; firstViewedAt: string | null; lastViewedAt: string | null; viewCount: number } | null;
const labels: Record<string, string> = { active: "Ativo", revoked: "Revogado", expired: "Expirado", rotated: "Rotacionado" };
const date = (value: string | null) => value ? new Date(value).toLocaleString("pt-BR") : "Ainda não";

export function ProposalPublicLinkPanel({ proposalId, proposalVersionId, proposalStatus, status: initialStatus }: { proposalId: string; proposalVersionId: string | null; proposalStatus: string; status: LinkStatus }) {
  const [status, setStatus] = useState(initialStatus); const [expiresAt, setExpiresAt] = useState(""); const [url, setUrl] = useState<string | null>(null); const [open, setOpen] = useState(false); const [confirmRevoke, setConfirmRevoke] = useState(false); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const canCreate = proposalStatus === "ready" && !status;
  const canRotate = Boolean(status) && status?.status !== "active" || proposalStatus === "sent" || proposalStatus === "viewed";
  const expiration = expiresAt ? new Date(expiresAt).toISOString() : null;
  async function generate(rotate: boolean) { setBusy(true); setMessage(null); const input = { proposalId, proposalVersionId, expiresAt: expiration, idempotencyKey: `${rotate ? "rotate" : "create"}-${crypto.randomUUID()}` }; const result = rotate ? await rotateProposalPublicLinkAction(input) : await createProposalPublicLinkAction(input); setBusy(false); if (!("data" in result) || !result.data) { setMessage(result.error?.message ?? "Não foi possível gerar o link."); return; } setUrl(result.data.url); setOpen(Boolean(result.data.url)); setMessage(result.data.url ? "Link criado. Ele será exibido somente agora." : "A operação já havia sido processada. Gere um novo link para obter uma URL."); setStatus({ ...(status ?? { linkId: result.data.linkId, proposalId, proposalVersionId: result.data.proposalVersionId, status: "active", activatedAt: new Date().toISOString(), revokedAt: null, createdAt: new Date().toISOString(), firstViewedAt: null, lastViewedAt: null, viewCount: 0 }), linkId: result.data.linkId, status: "active", expiresAt: result.data.expiresAt }); }
  async function revoke() { if (!status) return; setBusy(true); const result = await revokeProposalPublicLinkAction({ linkId: status.linkId, proposalId }); setBusy(false); setConfirmRevoke(false); if (!("data" in result) || !result.data) { setMessage(result.error?.message ?? "Não foi possível revogar."); return; } setStatus({ ...status, status: result.data.status, revokedAt: new Date().toISOString() }); setMessage("Link revogado."); }
  return <Card data-testid="public-link-panel"><CardHeader><CardTitle className="flex items-center gap-2"><Link2 className="size-4" /> Compartilhamento público</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><p className="text-muted-foreground">O link público mostra apenas a versão autorizada da proposta. O endereço completo não é salvo nem reaparece após recarregar.</p>{status ? <div className="grid gap-2 sm:grid-cols-2"><p>Status: <strong>{labels[status.status] ?? status.status}</strong></p><p>Versão compartilhada: <strong>v{status.proposalVersionId ? "ativa" : "-"}</strong></p><p>Criado em: {date(status.createdAt)}</p><p>Expira em: {date(status.expiresAt)}</p><p>Primeira visualização: {date(status.firstViewedAt)}</p><p>Última visualização: {date(status.lastViewedAt)}</p><p>Visualizações: <strong>{status.viewCount}</strong></p></div> : <p className="text-muted-foreground">Nenhum link público gerado.</p>}<label className="block space-y-1"><span className="text-xs font-medium">Validade opcional</span><input aria-label="Validade do link" type="datetime-local" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} className="h-9 w-full rounded-lg border bg-background px-2" /></label><div className="flex flex-wrap gap-2">{canCreate && <Button onClick={() => generate(false)} disabled={busy}><Link2 /> Gerar link</Button>}{canRotate && <Button variant="outline" onClick={() => generate(true)} disabled={busy}><RefreshCw /> Gerar novo link</Button>}{status?.status === "active" && <Button variant="outline" onClick={() => setConfirmRevoke(true)} disabled={busy}><ShieldOff /> Revogar</Button>}</div>{message && <p role="status" aria-live="polite" className="text-muted-foreground">{message}</p>}<ConfirmDialog open={confirmRevoke} onOpenChange={setConfirmRevoke} title="Revogar link público" description="O endereço deixará de funcionar imediatamente. Esta ação não altera a proposta." confirmLabel="Revogar" variant="destructive" onConfirm={revoke} /><Dialog open={open} onOpenChange={(next) => { setOpen(next); if (!next) setUrl(null); }}><DialogPopup><DialogTitle>Link público criado</DialogTitle><DialogDescription className="mt-2">Copie agora. Por segurança, o endereço completo não será recuperado depois.</DialogDescription><div className="mt-4 flex gap-2"><input aria-label="Link público" readOnly value={url ?? ""} className="min-w-0 flex-1 rounded-lg border bg-muted px-2 text-xs" /><Button aria-label="Copiar link público" onClick={() => url && navigator.clipboard.writeText(url)}><Copy /> Copiar</Button></div><div className="mt-5 flex justify-end"><DialogClose render={<Button variant="outline" />}><Check /> Fechar</DialogClose></div></DialogPopup></Dialog></CardContent></Card>;
}
