"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";

import { getAppContext } from "@/lib/auth/context";
import { can } from "@/lib/auth/permissions";
import { buildContractVersionPayload, CONTRACT_CLAUSE_TYPES } from "@/lib/contracts/editor";
import { activateContractVersionService, createContractVersionService, transitionContractService } from "@/lib/contracts/editor-service";
import { getSupabaseServerClient } from "@/lib/supabase/server";

const nullableText=(length:number)=>z.string().max(length).nullish().transform((value)=>value??undefined);
const draftSchema=z.object({title:z.string().min(3).max(500),content:z.string().max(100000),parties:z.object({contractor:z.record(z.string(),z.string().max(1000).optional()),client:z.record(z.string(),z.string().max(1000).optional())}),clauses:z.array(z.object({id:z.string().optional(),title:z.string().min(1).max(500),content:z.string().max(50000),order:z.number().int().nonnegative(),type:z.enum(CONTRACT_CLAUSE_TYPES),required:z.boolean(),enabled:z.boolean()})).max(100),terms:z.object({currency:z.string().max(8),subtotalCents:z.number().int().nonnegative(),discountCents:z.number().int().nonnegative(),totalCents:z.number().int().nonnegative(),entryAmountCents:z.number().int().nonnegative(),installmentCount:z.number().int().positive().max(120),installmentAmountCents:z.number().int().nonnegative(),recurrence:nullableText(80),successFeeBps:z.number().int().nonnegative().max(10000).optional(),externalExpensesCents:z.number().int().nonnegative().optional()}),metadata:z.object({reference:nullableText(200),effectiveFrom:nullableText(20),effectiveUntil:nullableText(20),jurisdiction:nullableText(500),language:nullableText(20),notes:nullableText(10000)}),schemaVersion:z.number().int()});
const mutationSchema=z.object({contractId:z.string().uuid(),expectedUpdatedAt:z.string().min(20).max(64),idempotencyKey:z.string().min(1).max(256)});
async function editorContext(){const context=await getAppContext(); if(context.status!=="ready"||!context.member||!context.lawFirm) throw new Error("AUTH_REQUIRED"); if(!["proprietario","administrador","advogado"].includes(context.member.role)||!can(context.member.role,"contratos.gerenciar")) throw new Error("CONTRACT_EDITOR_PERMISSION_DENIED"); const supabase=await getSupabaseServerClient(); if(!supabase) throw new Error("SUPABASE_UNAVAILABLE"); return supabase;}
function result<T>(work:()=>Promise<T>){return work().then((data)=>({ok:true as const,data})).catch((error:unknown)=>({ok:false as const,error:error instanceof Error?error.message:"CONTRACT_EDITOR_ERROR"}));}
function invalidate(contractId:string){revalidatePath("/contratos");revalidatePath(`/contratos/${contractId}`);revalidatePath(`/contratos/${contractId}/editar`);revalidatePath(`/contratos/${contractId}/comparar`);}
export async function createContractVersionAction(input:unknown){return result(async()=>{const parsed=mutationSchema.extend({draft:draftSchema,activate:z.boolean()}).parse(input);const client=await editorContext();const data=await createContractVersionService(client,parsed);invalidate(parsed.contractId);return data;});}
export async function activateContractVersionAction(input:unknown){return result(async()=>{const parsed=mutationSchema.extend({versionId:z.string().uuid()}).parse(input);const data=await activateContractVersionService(await editorContext(),parsed.contractId,parsed.versionId,parsed.expectedUpdatedAt);invalidate(parsed.contractId);return data;});}
export async function markContractReadyAction(input:unknown){return result(async()=>{const parsed=mutationSchema.extend({draft:draftSchema}).parse(input);const readiness=buildContractVersionPayload(parsed.draft).readiness;const data=await transitionContractService(await editorContext(),parsed.contractId,"ready",parsed.expectedUpdatedAt,readiness);invalidate(parsed.contractId);return data;});}
export async function returnContractToDraftAction(input:unknown){return result(async()=>{const parsed=mutationSchema.parse(input);const data=await transitionContractService(await editorContext(),parsed.contractId,"draft",parsed.expectedUpdatedAt);invalidate(parsed.contractId);return data;});}
export async function archiveContractAction(input:unknown){return result(async()=>{const parsed=mutationSchema.parse(input);const data=await transitionContractService(await editorContext(),parsed.contractId,"archive",parsed.expectedUpdatedAt);invalidate(parsed.contractId);return data;});}
export async function restoreContractAction(input:unknown){return result(async()=>{const parsed=mutationSchema.parse(input);const data=await transitionContractService(await editorContext(),parsed.contractId,"restore",parsed.expectedUpdatedAt);invalidate(parsed.contractId);return data;});}
