"use server";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { getAppContext } from "@/lib/auth/context";
import { SupabaseProposalOperationRepository } from "../persistence/supabase-rpc";
import { SupabaseProposalVersionRepository } from "../persistence/supabase-rpc";
import { SupabaseProposalRepository } from "../persistence/supabase-repository";
import { createManualProposalService, createPricingProposalService, duplicateProposalService, updateProposalMetadataService } from "./services";
import { activateProposalVersionService, createProposalVersionService, transitionProposalService, upsertProposalRecipientService } from "./version-services";
import { getProposalDetailService, listProposalEventsService, listProposalsService } from "./query-services";
import { toSafeProposalError } from "./errors";
import type { ProposalActivationInput, ProposalDuplicateInput, ProposalManualInput, ProposalMetadataInput, ProposalPricingInput, ProposalRecipientInput, ProposalTransitionInput, ProposalVersionInput } from "./schemas";
async function operationContext() { const context = await getAppContext(); if (context.status !== "ready" || !context.member) return { error: { code: "PROPOSAL_PERMISSION_DENIED", message: "Acesso não autorizado." } } as const; const client = await getSupabaseServerClient(); if (!client) return { error: { code: "PROPOSAL_PERSISTENCE_ERROR", message: "Serviço indisponível." } } as const; return { client, actor: { role: context.member.role, assisted: false } } as const; }
export async function createManualProposalAction(input: ProposalManualInput) { try { const ctx = await operationContext(); if ("error" in ctx) return ctx; return { data: await createManualProposalService(new SupabaseProposalOperationRepository(ctx.client), ctx.actor, input) }; } catch (error) { return { error: toSafeProposalError(error) }; } }
export async function createPricingProposalAction(input: ProposalPricingInput) { try { const ctx = await operationContext(); if ("error" in ctx) return ctx; return { data: await createPricingProposalService(new SupabaseProposalOperationRepository(ctx.client), ctx.actor, input) }; } catch (error) { return { error: toSafeProposalError(error) }; } }
export async function duplicateProposalAction(input: ProposalDuplicateInput) { try { const ctx = await operationContext(); if ("error" in ctx) return ctx; return { data: await duplicateProposalService(new SupabaseProposalOperationRepository(ctx.client), ctx.actor, input) }; } catch (error) { return { error: toSafeProposalError(error) }; } }
export async function updateProposalMetadataAction(input: ProposalMetadataInput) { try { const ctx = await operationContext(); if ("error" in ctx) return ctx; return { data: await updateProposalMetadataService(new SupabaseProposalOperationRepository(ctx.client), ctx.actor, input) }; } catch (error) { return { error: toSafeProposalError(error) }; } }
export async function createProposalVersionAction(input: ProposalVersionInput) { try { const ctx = await operationContext(); if ("error" in ctx) return ctx; return { data: await createProposalVersionService(new SupabaseProposalVersionRepository(ctx.client), ctx.actor, input) }; } catch (error) { console.error(JSON.stringify({ event: "proposal_action_failed", action: "createProposalVersion", code: error instanceof Error && "code" in error ? String((error as Error & { code?: unknown }).code) : "UNMAPPED", message: error instanceof Error ? error.message : String(error) })); return { error: toSafeProposalError(error) }; } }
export async function activateProposalVersionAction(input: ProposalActivationInput) { try { const ctx = await operationContext(); if ("error" in ctx) return ctx; return { data: await activateProposalVersionService(new SupabaseProposalVersionRepository(ctx.client), ctx.actor, input) }; } catch (error) { return { error: toSafeProposalError(error) }; } }
export async function transitionProposalAction(input: ProposalTransitionInput) { try { const ctx = await operationContext(); if ("error" in ctx) return ctx; return { data: await transitionProposalService(new SupabaseProposalVersionRepository(ctx.client), ctx.actor, input) }; } catch (error) { return { error: toSafeProposalError(error) }; } }
export async function upsertProposalRecipientAction(input: ProposalRecipientInput) { try { const ctx = await operationContext(); if ("error" in ctx) return ctx; return { data: await upsertProposalRecipientService(new SupabaseProposalVersionRepository(ctx.client), ctx.actor, input) }; } catch (error) { return { error: toSafeProposalError(error) }; } }
export const createProposalFromPricingAction = createPricingProposalAction;
export const transitionProposalStatusAction = transitionProposalAction;
export const archiveProposalAction = async (input: Omit<ProposalTransitionInput, "to">) => transitionProposalAction({ ...input, to: "archived" });
export const restoreProposalAction = async (input: Omit<ProposalTransitionInput, "to">) => transitionProposalAction({ ...input, to: "draft" });
export const addProposalRecipientAction = upsertProposalRecipientAction;
export const updateProposalRecipientAction = upsertProposalRecipientAction;
function readRole(role: string) { return role === "proprietario" ? "owner" : ["assistente", "secretaria"].includes(role) ? "restricted" : "lawyer"; }
export async function listProposalsAction(status?: string) { try { const ctx = await operationContext(); if ("error" in ctx) return ctx; return { data: await listProposalsService(new SupabaseProposalRepository(ctx.client, readRole(ctx.actor.role)), status) }; } catch (error) { return { error: toSafeProposalError(error) }; } }
export async function getProposalDetailAction(proposalId: string) { try { const ctx = await operationContext(); if ("error" in ctx) return ctx; return { data: await getProposalDetailService(new SupabaseProposalRepository(ctx.client, readRole(ctx.actor.role)), proposalId) }; } catch (error) { return { error: toSafeProposalError(error) }; } }
export async function listProposalEventsAction(proposalId: string) { try { const ctx = await operationContext(); if ("error" in ctx) return ctx; return { data: await listProposalEventsService(new SupabaseProposalRepository(ctx.client, readRole(ctx.actor.role)), proposalId) }; } catch (error) { return { error: toSafeProposalError(error) }; } }
