import type { CommercialProposal, CommercialProposalEvent, CommercialProposalItem, CommercialProposalRecipient, CommercialProposalSection, CommercialProposalVersion, ProposalCommercialSummary, ProposalPaymentTerms, ProposalPricingSnapshot } from "../domain/types";
import type { ProposalOriginType, ProposalStatus } from "../domain/status";

export type ProposalOwnerDTO = CommercialProposal & { internalReference: string | null; internalNotes: string | null; sourcePricingScenarioId: string | null; sourcePricingVersionId: string | null };
export type ProposalLawyerDTO = Omit<ProposalOwnerDTO, "internalNotes">;
export type ProposalRestrictedDTO = Omit<ProposalLawyerDTO, "sourcePricingScenarioId" | "sourcePricingVersionId" | "internalReference">;
export interface ProposalDetailDTO { proposal: ProposalOwnerDTO | ProposalLawyerDTO | ProposalRestrictedDTO; activeVersion: CommercialProposalVersion | null; sections: CommercialProposalSection[]; items: CommercialProposalItem[]; recipients: CommercialProposalRecipient[]; }
export interface ProposalVersionDraftDTO { title: string; introduction?: string | null; conclusion?: string | null; currency: string; validityDays?: number | null; summary: ProposalCommercialSummary; paymentTerms: ProposalPaymentTerms; sections: Array<Omit<CommercialProposalSection, "id" | "proposalVersionId">>; items: Array<Omit<CommercialProposalItem, "id" | "proposalVersionId">>; pricingSnapshot?: ProposalPricingSnapshot | null; }
export interface ProposalListDTO { id: string; title: string; status: ProposalStatus; originType: ProposalOriginType; currency: string; activeVersionId: string | null; validUntil: string | null; createdAt: string; updatedAt: string; }
export interface ProposalEventDTO { id: string; proposalId: string; proposalVersionId: string | null; eventType: CommercialProposalEvent["eventType"]; metadata: Record<string, unknown>; createdAt: string; }
export type ProposalDecisionType = "accepted" | "rejected";
export interface PublicProposalDecisionDTO { decisionType: ProposalDecisionType; decidedAt: string; signerName: string; message: string; idempotent: boolean; alreadyDecided: boolean; }
export interface InternalProposalDecisionDTO { decisionId: string; proposalId: string; proposalVersionId: string; publicLinkId: string; decisionType: ProposalDecisionType; signerName: string; signerEmail: string | null; signerDocumentLast4: string | null; signerRole: string | null; companyName: string | null; rejectionReason: string | null; consentTextVersion: string; consentTextSnapshot: string; proposalContentHash: string; publicPayloadHash: string; decisionPayloadHash: string; decidedAt: string; createdAt: string; metadata: Record<string, unknown>; memberRole: string; }
export interface RestrictedProposalDecisionDTO extends Omit<InternalProposalDecisionDTO, "signerEmail" | "signerDocumentLast4" | "signerRole" | "companyName" | "rejectionReason"> { signerEmail: null; signerDocumentLast4: null; signerRole: null; companyName: null; rejectionReason: null; }
export interface ProposalDecisionReceiptDTO { decisionId: string; proposalId: string; proposalVersionId: string; publicLinkId: string; decisionType: ProposalDecisionType; proposalTitle: string; currency: string; totalCents: number; entryAmountCents: number; installmentCount: number; installmentAmountCents: number; recurringAmountCents: number; recurringMonths: number; successFeeBps: number; validUntil: string | null; signerName: string; signerEmail: string | null; signerDocumentLast4: string | null; signerRole: string | null; companyName: string | null; rejectionReason: string | null; consentTextVersion: string; consentTextSnapshot: string; proposalContentHash: string; publicPayloadHash: string; decisionPayloadHash: string; decidedAt: string; linkStatus: string; }
