import { z } from "zod";
export const proposalCurrencySchema = z.string().regex(/^[A-Z]{3}$/, "Moeda ISO 4217 inválida");
export const proposalTitleSchema = z.string().trim().min(1).max(500);
export const idempotencyKeySchema = z.string().trim().min(1).max(256).regex(/^[A-Za-z0-9:_-]+$/);
export const proposalManualInputSchema = z.object({ title: proposalTitleSchema, currency: proposalCurrencySchema.default("BRL"), validityDays: z.number().int().min(1).max(3650).nullable().optional(), idempotencyKey: idempotencyKeySchema });
export const proposalPricingInputSchema = z.object({ pricingScenarioId: z.string().uuid(), pricingVersionId: z.string().uuid(), title: proposalTitleSchema, clientId: z.string().uuid().nullable().optional(), contactId: z.string().uuid().nullable().optional(), validityDays: z.number().int().min(1).max(3650).nullable().optional(), idempotencyKey: idempotencyKeySchema, inputHash: z.string().regex(/^[0-9a-f]{64}$/) });
export const proposalDuplicateInputSchema = z.object({ sourceProposalId: z.string().uuid(), title: proposalTitleSchema.nullable().optional(), copyRecipients: z.boolean().default(false), idempotencyKey: idempotencyKeySchema, inputHash: z.string().regex(/^[0-9a-f]{64}$/) });
export const proposalMetadataInputSchema = z.object({ proposalId: z.string().uuid(), expectedUpdatedAt: z.string().datetime(), title: proposalTitleSchema.nullable().optional(), internalReference: z.string().max(200).nullable().optional(), validUntil: z.string().datetime().nullable().optional(), internalNotes: z.string().max(10000).nullable().optional() });
export const proposalSummarySchema = z.object({ currency: proposalCurrencySchema, subtotalCents: z.number().int().nonnegative(), discountCents: z.number().int().nonnegative(), totalCents: z.number().int().nonnegative(), entryAmountCents: z.number().int().nonnegative(), installmentCount: z.number().int().min(0).max(1200), installmentAmountCents: z.number().int().nonnegative(), recurringAmountCents: z.number().int().nonnegative(), recurringMonths: z.number().int().min(0).max(1200), successFeeBps: z.number().int().min(0).max(10000) });
export const proposalVersionDraftSchema = z.object({ title: proposalTitleSchema, introduction: z.string().max(20000).nullable().optional(), conclusion: z.string().max(20000).nullable().optional(), currency: proposalCurrencySchema, validityDays: z.number().int().min(1).max(3650).nullable().optional(), summary: proposalSummarySchema, paymentTerms: z.record(z.string(), z.unknown()), sections: z.array(z.object({ sectionType: z.string().min(1), title: z.string().max(500).nullable().optional(), bodyMarkdown: z.string().max(20000).nullable().optional(), orderIndex: z.number().int().nonnegative(), isRequired: z.boolean() })), items: z.array(z.object({ itemType: z.string().min(1), description: z.string().trim().min(1).max(1000), quantity: z.number().nonnegative(), unitAmountCents: z.number().int().nonnegative(), totalAmountCents: z.number().int().nonnegative(), isOptional: z.boolean(), isIncluded: z.boolean(), orderIndex: z.number().int().nonnegative(), metadata: z.record(z.string(), z.unknown()) })), pricingSnapshot: z.unknown().nullable().optional() });
export const proposalTransitionSchema = z.object({ proposalId: z.string().uuid(), to: z.enum(["draft", "ready", "sent", "viewed", "accepted", "rejected", "expired", "cancelled", "superseded", "archived"]), expectedUpdatedAt: z.string().datetime() });
export const proposalActivationSchema = z.object({ proposalId: z.string().uuid(), versionId: z.string().uuid(), expectedUpdatedAt: z.string().datetime() });
export const proposalVersionInputSchema = z.object({ proposalId: z.string().uuid(), expectedUpdatedAt: z.string().datetime(), draft: proposalVersionDraftSchema });
export const proposalRecipientSchema = z.object({ id: z.string().uuid().nullable().optional(), proposalId: z.string().uuid(), clientId: z.string().uuid().nullable().optional(), contactId: z.string().uuid().nullable().optional(), recipientType: z.enum(["client", "contact", "representative", "decision_maker", "billing", "other"]), name: z.string().trim().min(1).max(500), email: z.string().email().nullable().optional(), phone: z.string().max(100).nullable().optional(), companyName: z.string().max(500).nullable().optional(), isPrimary: z.boolean().default(false) });
export const proposalDecisionConsentVersion = "2026-07-31.v1" as const;
export const proposalDecisionConsentText = {
  accepted: "Declaro que li e compreendi esta proposta comercial e confirmo minha decisao em relacao a versao apresentada. Concordo com os servicos, valores e condicoes comerciais apresentados.",
  rejected: "Declaro que li e compreendi esta proposta comercial e confirmo minha decisao em relacao a versao apresentada. Confirmo que nao desejo aceitar esta proposta nas condicoes apresentadas.",
} as const;
export const proposalDecisionInputSchema = z.object({ token: z.string().regex(/^[A-Za-z0-9_-]{43,}$/), decisionType: z.enum(["accepted", "rejected"]), signerName: z.string().trim().min(1).max(500), signerEmail: z.string().trim().email().max(320).optional().or(z.literal("")), signerDocumentLast4: z.string().regex(/^\d{4}$/).optional().or(z.literal("")), signerRole: z.string().trim().max(200).optional().or(z.literal("")), companyName: z.string().trim().max(500).optional().or(z.literal("")), rejectionReason: z.string().trim().max(1000).optional().or(z.literal("")), consentTextVersion: z.literal(proposalDecisionConsentVersion), consentTextSnapshot: z.string().min(1).max(2000), idempotencyKey: idempotencyKeySchema });
export type ProposalDecisionInput = z.infer<typeof proposalDecisionInputSchema>;
export type ProposalManualInput = z.infer<typeof proposalManualInputSchema>;
export type ProposalPricingInput = z.infer<typeof proposalPricingInputSchema>;
export type ProposalDuplicateInput = z.infer<typeof proposalDuplicateInputSchema>;
export type ProposalMetadataInput = z.infer<typeof proposalMetadataInputSchema>;
export type ProposalTransitionInput = z.infer<typeof proposalTransitionSchema>;
export type ProposalActivationInput = z.infer<typeof proposalActivationSchema>;
export type ProposalVersionInput = z.infer<typeof proposalVersionInputSchema>;
export type ProposalRecipientInput = z.infer<typeof proposalRecipientSchema>;
