import "server-only";
import { createHash } from "node:crypto";
import { decryptProviderCredentials, encryptProviderCredentials, credentialsKeyVersion } from "./encryption";
import { toProviderConfigurationDto } from "./dto";
import { ProviderConfigurationError } from "./errors";
import { createProviderConfigurationSchema, configurationOperationSchema, replaceCredentialsSchema, updateProviderConfigurationSchema } from "./schemas";
import { getProviderConfiguration, getProviderConfigurationAdminClient, listProviderConfigurations, recordConfigurationEvent } from "./repository";

type Context = { lawFirmId: string; userId: string; role: string; productionConfirmation?: boolean };
const authorized = (context: Context) => { if (!['proprietario', 'administrador'].includes(context.role)) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_CONFIGURATION_PERMISSION_DENIED"); };
const safeError = (error: unknown) => String((error as { code?: string })?.code ?? "SIGNATURE_PROVIDER_OPERATION_FAILED").replace(/[^A-Z0-9_.:-]/gi, "_").slice(0, 100);
const fingerprint = (value: unknown) => createHash("sha256").update(JSON.stringify(value), "utf8").digest("hex");
const assertProduction = (environment: string, context: Context) => { if (environment === "production" && !context.productionConfirmation) throw new ProviderConfigurationError("SIGNATURE_PRODUCTION_CONFIRMATION_REQUIRED"); };
const resultDto = (row: Record<string, unknown>) => toProviderConfigurationDto(row);

export async function listConfigurations(context: Context) { authorized(context); return (await listProviderConfigurations(context.lawFirmId)).map(resultDto); }
export async function createProviderConfiguration(context: Context, input: unknown) { authorized(context); const parsed = createProviderConfigurationSchema.parse(input); assertProduction(parsed.environment, context); const db = getProviderConfigurationAdminClient(); const encrypted = parsed.credentials ? encryptProviderCredentials(parsed.credentials, { lawFirmId: context.lawFirmId, provider: parsed.provider, environment: parsed.environment }) : null; const insert = await db.from("contract_signature_provider_configurations").insert({ law_firm_id: context.lawFirmId, provider: parsed.provider, environment: parsed.environment, display_name: parsed.displayName, public_configuration_json: parsed.publicConfiguration, encrypted_credentials: encrypted, credentials_key_version: encrypted ? credentialsKeyVersion : null, created_by: context.userId, updated_by: context.userId }).select("*").single(); if (insert.error) throw new ProviderConfigurationError(insert.error.code === "23505" ? "SIGNATURE_PROVIDER_IDEMPOTENCY_CONFLICT" : "SIGNATURE_PROVIDER_CREATE_FAILED"); await recordConfigurationEvent(context.lawFirmId, null, context.userId, "signature_provider_configuration_created", `provider-config-created:${insert.data.id}:${parsed.idempotencyKey}`, { provider: parsed.provider, environment: parsed.environment }); return resultDto(insert.data); }
export async function updateProviderConfiguration(context: Context, input: unknown) { authorized(context); const parsed = updateProviderConfigurationSchema.parse(input); const current = await getProviderConfiguration(context.lawFirmId, parsed.id); if (!current) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_NOT_FOUND"); const update = await getProviderConfigurationAdminClient().from("contract_signature_provider_configurations").update({ ...(parsed.displayName === undefined ? {} : { display_name: parsed.displayName }), ...(parsed.publicConfiguration === undefined ? {} : { public_configuration_json: parsed.publicConfiguration }), updated_by: context.userId, lock_version: parsed.lockVersion + 1 }).eq("id", parsed.id).eq("law_firm_id", context.lawFirmId).eq("lock_version", parsed.lockVersion).select("*").maybeSingle(); if (update.error || !update.data) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_STALE_LOCK"); return resultDto(update.data); }
export async function replaceProviderCredentials(context: Context, input: unknown) { authorized(context); const parsed = replaceCredentialsSchema.parse(input); const current = await getProviderConfiguration(context.lawFirmId, parsed.id); if (!current) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_NOT_FOUND"); const encrypted = encryptProviderCredentials(parsed.credentials, { lawFirmId: context.lawFirmId, provider: current.provider, environment: current.environment }); const update = await getProviderConfigurationAdminClient().from("contract_signature_provider_configurations").update({ encrypted_credentials: encrypted, credentials_key_version: credentialsKeyVersion, status: "draft", last_connection_test_at: null, last_connection_test_status: null, last_connection_error_code: null, updated_by: context.userId, lock_version: parsed.lockVersion + 1 }).eq("id", parsed.id).eq("law_firm_id", context.lawFirmId).eq("lock_version", parsed.lockVersion).select("*").maybeSingle(); if (update.error || !update.data) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_STALE_LOCK"); await recordConfigurationEvent(context.lawFirmId, null, context.userId, "signature_provider_credentials_replaced", `provider-config-credentials:${parsed.id}:${parsed.idempotencyKey}`, { provider: current.provider, environment: current.environment }); return resultDto(update.data); }
export async function testProviderConnection(context: Context, input: unknown) { authorized(context); const parsed = configurationOperationSchema.parse(input); const current = await getProviderConfiguration(context.lawFirmId, parsed.id); if (!current) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_NOT_FOUND"); const started = Date.now(); let status: "passed" | "failed" | "not_implemented" = "passed"; let errorCode: string | null = null; try { if (!current.encrypted_credentials) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_CREDENTIALS_REQUIRED"); decryptProviderCredentials(current.encrypted_credentials, { lawFirmId: context.lawFirmId, provider: current.provider, environment: current.environment }); if (current.provider === "reserved_external") { status = "not_implemented"; errorCode = "PROVIDER_NOT_IMPLEMENTED"; } } catch (error) { status = "failed"; errorCode = safeError(error); } const update = await getProviderConfigurationAdminClient().from("contract_signature_provider_configurations").update({ last_connection_test_at: new Date().toISOString(), last_connection_test_status: status, last_connection_error_code: errorCode, status: status === "passed" ? "valid" : "invalid", updated_by: context.userId, lock_version: current.lock_version + 1 }).eq("id", parsed.id).eq("law_firm_id", context.lawFirmId).eq("lock_version", parsed.lockVersion).select("*").maybeSingle(); if (update.error || !update.data) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_STALE_LOCK"); await recordConfigurationEvent(context.lawFirmId, null, context.userId, "signature_provider_connection_tested", `provider-config-test:${parsed.id}:${fingerprint({ key: parsed.idempotencyKey, duration: Date.now() - started })}`, { provider: current.provider, environment: current.environment, status }); return resultDto(update.data); }
export async function enableProviderConfiguration(context: Context, input: unknown) { authorized(context); const parsed = configurationOperationSchema.parse(input); const current = await getProviderConfiguration(context.lawFirmId, parsed.id); if (!current) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_NOT_FOUND"); assertProduction(current.environment, context); if (current.provider === "reserved_external") throw new ProviderConfigurationError("PROVIDER_NOT_IMPLEMENTED"); if (!current.encrypted_credentials || current.last_connection_test_status !== "passed") throw new ProviderConfigurationError("SIGNATURE_PROVIDER_REQUIRES_SUCCESSFUL_TEST"); const update = await getProviderConfigurationAdminClient().from("contract_signature_provider_configurations").update({ status: "valid", enabled_at: new Date().toISOString(), disabled_at: null, updated_by: context.userId, lock_version: parsed.lockVersion + 1 }).eq("id", parsed.id).eq("law_firm_id", context.lawFirmId).eq("lock_version", parsed.lockVersion).select("*").maybeSingle(); if (update.error || !update.data) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_STALE_LOCK"); await recordConfigurationEvent(context.lawFirmId, null, context.userId, "signature_provider_enabled", `provider-config-enabled:${parsed.id}:${parsed.idempotencyKey}`, { provider: current.provider, environment: current.environment }); return resultDto(update.data); }
export async function disableProviderConfiguration(context: Context, input: unknown) { authorized(context); const parsed = configurationOperationSchema.parse(input); const current = await getProviderConfiguration(context.lawFirmId, parsed.id); if (!current) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_NOT_FOUND"); const update = await getProviderConfigurationAdminClient().from("contract_signature_provider_configurations").update({ status: "disabled", is_default: false, disabled_at: new Date().toISOString(), updated_by: context.userId, lock_version: parsed.lockVersion + 1 }).eq("id", parsed.id).eq("law_firm_id", context.lawFirmId).eq("lock_version", parsed.lockVersion).select("*").maybeSingle(); if (update.error || !update.data) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_STALE_LOCK"); await recordConfigurationEvent(context.lawFirmId, null, context.userId, "signature_provider_disabled", `provider-config-disabled:${parsed.id}:${parsed.idempotencyKey}`, { provider: current.provider, environment: current.environment }); return resultDto(update.data); }
export async function setDefaultProviderConfiguration(context: Context, input: unknown) { authorized(context); const parsed = configurationOperationSchema.parse(input); const current = await getProviderConfiguration(context.lawFirmId, parsed.id); if (!current || current.status !== "valid") throw new ProviderConfigurationError("SIGNATURE_PROVIDER_DEFAULT_REQUIRES_VALID"); const db = getProviderConfigurationAdminClient(); const clear = await db.from("contract_signature_provider_configurations").update({ is_default: false, updated_by: context.userId }).eq("law_firm_id", context.lawFirmId).eq("environment", current.environment).eq("is_default", true); if (clear.error) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_DEFAULT_FAILED"); const update = await db.from("contract_signature_provider_configurations").update({ is_default: true, updated_by: context.userId, lock_version: parsed.lockVersion + 1 }).eq("id", parsed.id).eq("law_firm_id", context.lawFirmId).eq("lock_version", parsed.lockVersion).select("*").maybeSingle(); if (update.error || !update.data) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_STALE_LOCK"); await recordConfigurationEvent(context.lawFirmId, null, context.userId, "signature_provider_default_changed", `provider-config-default:${current.environment}:${parsed.id}`, { provider: current.provider, environment: current.environment }); return resultDto(update.data); }
export async function deleteDraftProviderConfiguration(context: Context, input: unknown) { authorized(context); const parsed = configurationOperationSchema.parse(input); const current = await getProviderConfiguration(context.lawFirmId, parsed.id); if (!current) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_NOT_FOUND"); if (current.status !== "draft") throw new ProviderConfigurationError("SIGNATURE_PROVIDER_DELETE_DRAFT_ONLY"); const deleted = await getProviderConfigurationAdminClient().from("contract_signature_provider_configurations").delete().eq("id", parsed.id).eq("law_firm_id", context.lawFirmId).eq("lock_version", parsed.lockVersion); if (deleted.error) throw new ProviderConfigurationError("SIGNATURE_PROVIDER_DELETE_FAILED"); await recordConfigurationEvent(context.lawFirmId, null, context.userId, "signature_provider_configuration_deleted", `provider-config-deleted:${parsed.id}`, { provider: current.provider, environment: current.environment }); return { deleted: true }; }
