import {
  Banknote,
  Bell,
  BriefcaseBusiness,
  CalendarDays,
  ChartNoAxesCombined,
  CircleGauge,
  Clock3,
  Database,
  Download,
  FileSearch,
  GitBranch,
  FileArchive,
  FileText,
  Handshake,
  Inbox,
  Kanban,
  KeyRound,
  Receipt,
  Scale,
  ScrollText,
  Settings,
  SlidersHorizontal,
  Timer,
  Upload,
  UserRoundCog,
  Users,
  Workflow,
} from "lucide-react";

export const navigationSections = [
  {
    label: "Visão geral",
    items: [{ label: "Dashboard", href: "/dashboard", icon: CircleGauge }],
  },
  {
    label: "CRM",
    items: [
      { label: "Pipeline", href: "/pipeline", icon: Kanban },
      { label: "Leads", href: "/leads", icon: Handshake },
      { label: "Clientes", href: "/clientes", icon: Users },
      { label: "Importar", href: "/importar", icon: Upload },
      { label: "Deduplicação", href: "/deduplicacao", icon: Workflow },
    ],
  },
  {
    label: "Jurídico",
    items: [
      { label: "Processos", href: "/processos", icon: Scale },
      { label: "Solicitações", href: "/solicitacoes", icon: Inbox },
      { label: "Correspondentes", href: "/correspondentes", icon: Users },
      { label: "Conflitos", href: "/conflitos", icon: FileSearch },
      { label: "Conflitos Avan", href: "/conflitos/avancado", icon: FileSearch },
      { label: "Prazos", href: "/prazos", icon: CalendarDays },
      { label: "Agenda", href: "/agenda", icon: Clock3 },
      { label: "Tarefas", href: "/tarefas", icon: BriefcaseBusiness },
      { label: "Workflows", href: "/workflows", icon: GitBranch },
      { label: "Gerar Doc", href: "/documentos/gerar", icon: FileText },
    ],
  },
  {
    label: "Financeiro",
    items: [
      { label: "Contratos", href: "/contratos", icon: FileText },
      { label: "Recebimentos", href: "/recebimentos", icon: Banknote },
      { label: "Despesas", href: "/despesas", icon: Receipt },
      { label: "Horas", href: "/horas", icon: Timer },
      { label: "Relatório Horas", href: "/horas/relatorio", icon: Timer },
      { label: "Relatórios", href: "/relatorios", icon: ChartNoAxesCombined },
      { label: "Exportar", href: "/exportar", icon: Download },
    ],
  },
  {
    label: "Gestão",
    items: [
      { label: "Notificações", href: "/notificacoes", icon: Bell },
      { label: "Documentos", href: "/documentos", icon: FileArchive },
      { label: "Modelos", href: "/documentos/modelos", icon: FileText },
      { label: "Portal do cliente", href: "/portal-cliente", icon: KeyRound },
      { label: "Equipe", href: "/equipe", icon: UserRoundCog },
      { label: "Campos", href: "/configuracoes/campos-personalizados", icon: SlidersHorizontal },
      { label: "Backup", href: "/backup", icon: Database },
      { label: "Auditoria", href: "/auditoria", icon: ScrollText },
      { label: "Configurações", href: "/configuracoes", icon: Settings },
    ],
  },
];
