"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { getAppContext } from "@/lib/auth/context";
import { canManageSignatureEnvelope, createSignatureEnvelope, prepareSignatureEnvelope, cancelSignatureEnvelope, envelopeDraftSchema } from "@/lib/contracts/signatures";
import { cancelSentSignatureEnvelope, reconcileSignatureEnvelopeStatus, retrySignatureDelivery, sendSignatureEnvelope } from "@/lib/contracts/signatures/delivery/service";
import { getSupabaseAdminClient } from "@/lib/supabase/admin";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { archiveSignatureArtifact, retrieveCompletedSignatureArtifacts } from "@/lib/contracts/signatures/artifacts";
const contextForWrite = async () => { const context = await getAppContext(); const member = context.member; const lawFirm = context.lawFirm; if (context.status !== "ready" || !member || !lawFirm || !canManageSignatureEnvelope(member.role)) throw new Error("SIGNATURE_PERMISSION_DENIED"); const client = await getSupabaseServerClient(); if (!client) throw new Error("SUPABASE_UNAVAILABLE"); const { data: { user } } = await client.auth.getUser(); if (!user) throw new Error("SIGNATURE_AUTH_REQUIRED"); return { member, lawFirm, client, user }; };
const adminForDelivery = () => { const admin = getSupabaseAdminClient(); if (!admin) throw new Error("SUPABASE_ADMIN_UNAVAILABLE"); return admin; };
const sanitizeSigners = (signers: unknown) => Array.isArray(signers) ? signers.map((signer) => { const item = signer as Record<string, unknown>; return { signerType: String(item.signerType ?? ""), role: String(item.role ?? ""), namePresent: Boolean(String(item.name ?? "").trim()), emailPresent: Boolean(String(item.email ?? "").trim()), phonePresent: Boolean(String(item.phone ?? "").trim()), signingOrder: item.signingOrder ?? null, keys: Object.keys(item).sort() }; }) : [];
const response = async (work: () => Promise<unknown>) => { try { return { ok: true as const, data: await work() }; } catch (error) { console.error("[signature-action]", error instanceof Error ? error.message : "SIGNATURE_OPERATION_FAILED", error instanceof Error ? error.stack : ""); return { ok: false as const, error: error instanceof Error ? error.message.replace(/\b(path|token|secret|password)\b[^\s]*/gi, "$1=<redacted>") : "SIGNATURE_OPERATION_FAILED" }; } };
export async function createSignatureEnvelopeAction(formData: FormData): Promise<void> { await response(async () => { const { member, lawFirm, client, user } = await contextForWrite(); const rawSigners = String(formData.get("signers") ?? "[]"); const signers = JSON.parse(rawSigners); console.info("[signature-action] signer payload", sanitizeSigners(signers)); const input = envelopeDraftSchema.parse({ contractId: formData.get("contractId"), contractDocumentId: formData.get("contractDocumentId"), contractVersionId: formData.get("contractVersionId"), title: formData.get("title"), consentVersion: formData.get("consentVersion"), expiresAt: formData.get("expiresAt") || null, signingOrderEnabled: true, lockVersion: 1, idempotencyKey: formData.get("idempotencyKey"), signers }); console.info("[signature-action] signer schema", sanitizeSigners(input.signers)); await createSignatureEnvelope(client, { lawFirmId: lawFirm.id, userId: user.id, role: member.role }, input); revalidatePath(`/contratos/${input.contractId}/assinatura`); }); }
export async function prepareSignatureEnvelopeAction(formData: FormData): Promise<void> { await response(async () => { const { member, lawFirm, client, user } = await contextForWrite(); const envelopeId = z.string().uuid().parse(formData.get("envelopeId")); const contractId = z.string().uuid().parse(formData.get("contractId")); await prepareSignatureEnvelope(client, { lawFirmId: lawFirm.id, userId: user.id, role: member.role }, envelopeId, Number(formData.get("lockVersion"))); revalidatePath(`/contratos/${contractId}/assinatura`); }); }
export async function cancelSignatureEnvelopeAction(formData: FormData): Promise<void> { await response(async () => { const { member, lawFirm, client, user } = await contextForWrite(); const envelopeId = z.string().uuid().parse(formData.get("envelopeId")); const contractId = z.string().uuid().parse(formData.get("contractId")); await cancelSignatureEnvelope(client, { lawFirmId: lawFirm.id, userId: user.id, role: member.role }, envelopeId, Number(formData.get("lockVersion")), String(formData.get("reason") ?? "Cancelado internamente")); revalidatePath(`/contratos/${contractId}/assinatura`); }); }
export async function sendSignatureEnvelopeAction(formData: FormData): Promise<void> { await response(async () => { const { member, lawFirm, user } = await contextForWrite(); const envelopeId = z.string().uuid().parse(formData.get("envelopeId")); const contractId = z.string().uuid().parse(formData.get("contractId")); const idempotencyKey = z.string().trim().min(1).max(256).parse(formData.get("idempotencyKey")); await sendSignatureEnvelope(adminForDelivery() as never, { lawFirmId: lawFirm.id, userId: user.id, role: member.role }, envelopeId, "internal_sandbox", idempotencyKey); revalidatePath(`/contratos/${contractId}/assinatura`); }); }
export async function retrySignatureDeliveryAction(formData: FormData): Promise<void> { await response(async () => { const { member, lawFirm, user } = await contextForWrite(); const envelopeId = z.string().uuid().parse(formData.get("envelopeId")); const contractId = z.string().uuid().parse(formData.get("contractId")); const idempotencyKey = z.string().trim().min(1).max(256).parse(formData.get("idempotencyKey")); await retrySignatureDelivery(adminForDelivery() as never, { lawFirmId: lawFirm.id, userId: user.id, role: member.role }, envelopeId, idempotencyKey); revalidatePath(`/contratos/${contractId}/assinatura`); }); }
export async function cancelSentSignatureEnvelopeAction(formData: FormData): Promise<void> { await response(async () => { const { member, lawFirm, user } = await contextForWrite(); const envelopeId = z.string().uuid().parse(formData.get("envelopeId")); const contractId = z.string().uuid().parse(formData.get("contractId")); await cancelSentSignatureEnvelope(adminForDelivery() as never, { lawFirmId: lawFirm.id, userId: user.id, role: member.role }, envelopeId); revalidatePath(`/contratos/${contractId}/assinatura`); }); }
export async function reconcileSignatureEnvelopeAction(formData: FormData): Promise<void> { await response(async () => { const { member, lawFirm, user } = await contextForWrite(); const envelopeId = z.string().uuid().parse(formData.get("envelopeId")); const contractId = z.string().uuid().parse(formData.get("contractId")); await reconcileSignatureEnvelopeStatus(adminForDelivery() as never, { lawFirmId: lawFirm.id, userId: user.id, role: member.role }, envelopeId); revalidatePath(`/contratos/${contractId}/assinatura`); }); }
export async function retrieveCompletedSignatureArtifactsAction(formData: FormData): Promise<void> { await response(async () => { const { member, lawFirm, user } = await contextForWrite(); const envelopeId = z.string().uuid().parse(formData.get("envelopeId")); const contractId = z.string().uuid().parse(formData.get("contractId")); const key = z.string().trim().min(1).max(256).parse(formData.get("idempotencyKey")); await retrieveCompletedSignatureArtifacts(adminForDelivery() as never, { lawFirmId: lawFirm.id, userId: user.id, role: member.role }, envelopeId, key); revalidatePath(`/contratos/${contractId}/assinatura`); }); }
export async function archiveSignatureArtifactAction(formData: FormData): Promise<void> { await response(async () => { const { member, lawFirm, user } = await contextForWrite(); const artifactId = z.string().uuid().parse(formData.get("artifactId")); const contractId = z.string().uuid().parse(formData.get("contractId")); const key = z.string().trim().min(1).max(256).parse(formData.get("idempotencyKey")); await archiveSignatureArtifact(adminForDelivery() as never, { lawFirmId: lawFirm.id, userId: user.id, role: member.role }, artifactId, key); revalidatePath(`/contratos/${contractId}/assinatura`); }); }
