import Link from "next/link";
import { getAppContext } from "@/lib/auth/context";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { evaluateSignatureEnvelopeReadiness, getEnvelope, getSignatureSource, listEnvelopes } from "@/lib/contracts/signatures";
import { createSignatureEnvelopeAction, prepareSignatureEnvelopeAction, cancelSignatureEnvelopeAction } from "./actions";
import { sendSignatureEnvelopeAction, retrySignatureDeliveryAction, cancelSentSignatureEnvelopeAction, reconcileSignatureEnvelopeAction } from "./actions";
import { getSignatureDelivery } from "@/lib/contracts/signatures/delivery/service";
import { SignerEditor } from "./signer-editor";
import { listSignatureArtifacts } from "@/lib/contracts/signatures/artifacts";
import { retrieveCompletedSignatureArtifactsAction } from "./actions";
import { getSupabaseAdminClient } from "@/lib/supabase/admin";

export default async function ContractSignaturePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const context = await getAppContext();
  if (context.status !== "ready" || !context.lawFirm || !context.member) return <main className="p-8"><h1>Autenticação necessária</h1></main>;
  const client = await getSupabaseServerClient();
  if (!client) return <main className="p-8"><h1>Serviço indisponível</h1></main>;
  // A tabela de documentos foi criada depois da última geração dos tipos locais.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const result = await (client as any).from("contract_documents").select("id").eq("contract_id", id).eq("law_firm_id", context.lawFirm.id).eq("status", "completed").order("generated_at", { ascending: false }).limit(1).maybeSingle();
  const source = result.data?.id ? await getSignatureSource(client as never, context.lawFirm.id, result.data.id) : null;
  const envelopes = await listEnvelopes(client as never, context.lawFirm.id, id);
  const active = envelopes[0];
  const activeEnvelope = active ? await getEnvelope(client as never, context.lawFirm.id, active.id) : null;
  const readiness = activeEnvelope ? evaluateSignatureEnvelopeReadiness(source, activeEnvelope.signers, activeEnvelope.consentVersion, activeEnvelope.snapshot) : null;
  const delivery = active ? await getSignatureDelivery(client as never, context.lawFirm.id, active.id) : null;
  const deliveryView = delivery ?? (active?.status === "prepared" ? { status: "pending", attempt_number: 0, last_synced_at: null, last_error_code: null, provider_envelope_id: null } : null);
  const canWrite = ["proprietario", "administrador", "advogado"].includes(context.member.role);
  const artifacts = active?.status === "signed" ? await listSignatureArtifacts((getSupabaseAdminClient() ?? client) as never, context.lawFirm.id, active.id) : [];
  return <main className="mx-auto max-w-5xl space-y-6 p-6">
    {artifacts.length ? <section aria-live="polite" className="rounded-lg border p-5"><h2 className="font-semibold">Downloads dos documentos finais</h2><div className="mt-3 grid gap-2">{artifacts.map((item: Record<string, unknown>) => <Link key={`download-${String(item.id)}`} className="rounded border p-3 text-sm underline" href={`/api/contratos/${id}/assinatura/artifacts/${String(item.id)}`}>{String(item.artifact_type)} · {String(item.status)} · baixar</Link>)}</div></section> : null}
    {active?.status === "signed" ? <section className="rounded-lg border p-5"><h2 className="font-semibold">Documentos finais</h2><p className="mt-2 text-sm text-muted-foreground">Artefatos produzidos pelo ambiente interno de testes. Não representam assinatura comercial real.</p>{canWrite && !artifacts.length ? <form action={retrieveCompletedSignatureArtifactsAction} className="mt-4"><input type="hidden" name="contractId" value={id}/><input type="hidden" name="envelopeId" value={active.id}/><input type="hidden" name="idempotencyKey" value={`artifacts-${active.id}`}/><button className="rounded bg-primary px-4 py-2 text-primary-foreground" type="submit">Recuperar documentos finais</button></form> : null}<ul className="mt-4 grid gap-2">{artifacts.map((item: Record<string, unknown>) => <li key={String(item.id)} className="rounded border p-3 text-sm"><span className="font-medium">{String(item.artifact_type)}</span> · {String(item.status)} · {Number(item.page_count)} página(s) · {Number(item.file_size)} bytes · hash {String(item.file_hash ?? "").slice(0, 12)}...</li>)}</ul></section> : null}
    <Link href={`/contratos/${id}`} className="text-sm underline">Voltar para contrato</Link>
    <header><h1 className="text-2xl font-semibold">Envelope de assinatura</h1><p className="text-sm text-muted-foreground">Preparação interna agnóstica de fornecedor. Nenhuma solicitação será enviada.</p></header>
    {source ? <section className="rounded-lg border p-5"><h2 className="font-semibold">Documento de origem</h2><p className="mt-2 text-sm">{source.title} · versão {source.contractVersionId.slice(0, 8)} · {source.pageCount} página(s) · {source.fileSize} bytes · hash {source.documentHash?.slice(0, 12)}...</p></section> : <p role="alert">Nenhum PDF contratual concluído foi encontrado.</p>}
    {canWrite && source ? <section className="rounded-lg border p-5"><h2 className="font-semibold">Criar envelope</h2><form action={createSignatureEnvelopeAction} className="mt-4 grid gap-3"><input type="hidden" name="contractId" value={id}/><input type="hidden" name="contractDocumentId" value={source.contractDocumentId}/><input type="hidden" name="contractVersionId" value={source.contractVersionId}/><input type="hidden" name="idempotencyKey" value={`signature-${source.contractDocumentId}`}/><label>Título<input required name="title" defaultValue={source.title} className="mt-1 block w-full rounded border p-2"/></label><label>Versão do consentimento<input required name="consentVersion" defaultValue="signature-envelope-v1" className="mt-1 block w-full rounded border p-2"/></label><SignerEditor /><button className="rounded bg-primary px-4 py-2 text-primary-foreground" type="submit">Salvar envelope</button></form></section> : null}
    {active ? <section className="rounded-lg border p-5"><h2 className="font-semibold">Envelope atual: {active.title}</h2><p className="mt-2 text-sm">Status: {active.status} · lock {active.lock_version}</p>{active.status === "draft" ? <form action={prepareSignatureEnvelopeAction} className="mt-3 inline-flex gap-2"><input type="hidden" name="contractId" value={id}/><input type="hidden" name="envelopeId" value={active.id}/><input type="hidden" name="lockVersion" value={active.lock_version}/><button className="rounded bg-primary px-4 py-2 text-primary-foreground" type="submit">Preparar envelope</button></form> : null}{["draft", "prepared"].includes(active.status) ? <form action={cancelSignatureEnvelopeAction} className="mt-3 ml-2 inline-flex gap-2"><input type="hidden" name="contractId" value={id}/><input type="hidden" name="envelopeId" value={active.id}/><input type="hidden" name="lockVersion" value={active.lock_version}/><input type="hidden" name="reason" value="Cancelamento interno"/><button className="rounded border px-4 py-2" type="submit">Cancelar</button></form> : null}<p className="mt-4 text-sm text-muted-foreground">Este envelope está apenas preparado. Nenhuma solicitação de assinatura foi enviada.</p>{readiness ? <p className="mt-2 text-sm">Readiness: {readiness.ready ? "pronto" : readiness.blockers.join(", ")}</p> : null}</section> : null}
    {active && deliveryView ? <section className="rounded-lg border border-dashed p-5"><h2 className="font-semibold">Entrega de assinatura</h2><p className="mt-2 text-sm text-muted-foreground">Ambiente de teste. Nenhuma solicitação real será enviada.</p><dl className="mt-4 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">Provider</dt><dd>Sandbox interno</dd></div><div><dt className="text-muted-foreground">Status</dt><dd>{deliveryView.status}</dd></div><div><dt className="text-muted-foreground">Tentativas</dt><dd>{deliveryView.attempt_number}</dd></div><div><dt className="text-muted-foreground">Última sincronização</dt><dd>{deliveryView.last_synced_at ?? "Ainda não sincronizado"}</dd></div>{deliveryView.last_error_code ? <div><dt className="text-muted-foreground">Erro seguro</dt><dd role="alert">{deliveryView.last_error_code}</dd></div> : null}</dl><div className="mt-4 flex flex-wrap gap-2">{deliveryView.status === "pending" || deliveryView.status === "failed" ? <form action={deliveryView.status === "failed" ? retrySignatureDeliveryAction : sendSignatureEnvelopeAction}><input type="hidden" name="contractId" value={id}/><input type="hidden" name="envelopeId" value={active.id}/><input type="hidden" name="idempotencyKey" value={`delivery-${active.id}-${deliveryView.status}-${deliveryView.attempt_number + 1}`}/><button className="rounded bg-primary px-4 py-2 text-primary-foreground" type="submit">{deliveryView.status === "failed" ? "Tentar novamente" : "Enviar para assinatura"}</button></form> : null}{["sent", "viewed", "partially_signed"].includes(deliveryView.status) ? <form action={cancelSentSignatureEnvelopeAction}><input type="hidden" name="contractId" value={id}/><input type="hidden" name="envelopeId" value={active.id}/><button className="rounded border px-4 py-2" type="submit">Cancelar solicitação</button></form> : null}{deliveryView.provider_envelope_id ? <form action={reconcileSignatureEnvelopeAction}><input type="hidden" name="contractId" value={id}/><input type="hidden" name="envelopeId" value={active.id}/><button className="rounded border px-4 py-2" type="submit">Reconciliar status</button></form> : null}</div></section> : null}
    <section className="rounded-lg border p-5"><h2 className="font-semibold">Histórico de envelopes</h2><ul className="mt-3 space-y-2 text-sm">{envelopes.map((item: { id: string; title: string; status: string; document_hash: string }) => <li key={item.id} className="border-b py-2">{item.title} · {item.status} · {item.document_hash.slice(0, 12)}...</li>)}{!envelopes.length ? <li>Nenhum envelope criado.</li> : null}</ul></section>
  </main>;
}
