import Link from "next/link";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/layout/app-shell";
import { PageHeader } from "@/components/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getAppContext } from "@/lib/auth/context";
import { compareContractVersions, type ContractDraft } from "@/lib/contracts/editor";
import { getContractEditorDetails } from "@/lib/contracts/queries";

function toDraft(version: NonNullable<Awaited<ReturnType<typeof getContractEditorDetails>>>["versions"][number]): ContractDraft { return {title:version.title,content:version.content,parties:version.parties as ContractDraft["parties"],clauses:version.clauses.map((item,index)=>({title:String(item.title??""),content:String(item.content??""),order:index,type:String(item.type??"custom") as ContractDraft["clauses"][number]["type"],required:Boolean(item.required),enabled:item.enabled!==false})),terms:version.terms as ContractDraft["terms"],metadata:version.metadata as ContractDraft["metadata"],schemaVersion:1}; }
export default async function CompareContractPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{a?:string;b?:string}>}){const {id}=await params;const query=await searchParams;const context=await getAppContext();if(context.status!=="ready"||!context.member)redirect("/entrar");const detail=await getContractEditorDetails(id);if(!detail)redirect("/contratos");const a=detail.versions.find((item)=>item.id===query.a)??detail.versions.at(-2)??detail.versions[0];const b=detail.versions.find((item)=>item.id===query.b)??detail.versions.at(-1)??detail.versions[0];const rows=a&&b?compareContractVersions(toDraft(a),toDraft(b)):[];return <AppShell memberName={context.member.name}><div className="space-y-6"><Link href={`/contratos/${id}`} className="text-sm text-muted-foreground">← Voltar para o contrato</Link><PageHeader title="Comparar versões" description="A seleção A e B permanece na URL para revisão compartilhada."/><Card><CardHeader><CardTitle>Versão {a?.number} e versão {b?.number}</CardTitle></CardHeader><CardContent>{rows.length===0?<p className="text-sm text-muted-foreground">Não há diferenças estruturadas entre as versões selecionadas.</p>:<div className="space-y-3">{rows.map((row,index)=><div key={`${row.field}-${index}`} className="grid gap-1 border-b pb-3 text-sm sm:grid-cols-3"><strong>{row.field}</strong><span>Anterior: {String(row.before??"—")}</span><span>Atual: {String(row.after??"—")}{row.deltaCents!==undefined?` (delta: ${row.deltaCents} centavos)`:""}</span><span className="text-muted-foreground">{row.changeType}</span></div>)}</div>}</CardContent></Card></div></AppShell>}
