import { createHash } from "node:crypto";

export const CONTRACT_CLAUSE_TYPES = ["parties", "object", "scope", "firm_obligations", "client_obligations", "fees", "payment_terms", "success_fee", "expenses", "term", "termination", "confidentiality", "data_protection", "jurisdiction", "general_terms", "custom"] as const;
export type ContractClauseType = (typeof CONTRACT_CLAUSE_TYPES)[number];
export type ContractClause = { id?: string; title: string; content: string; order: number; type: ContractClauseType; required: boolean; enabled: boolean };
export type ContractParty = { name?: string; legalName?: string; document?: string; address?: string; email?: string; representative?: string; representativeRole?: string };
export type ContractDraft = { title: string; content: string; parties: { contractor: ContractParty; client: ContractParty }; clauses: ContractClause[]; terms: { currency: string; subtotalCents: number; discountCents: number; totalCents: number; entryAmountCents: number; installmentCount: number; installmentAmountCents: number; recurrence?: string; successFeeBps?: number; externalExpensesCents?: number }; metadata: { reference?: string; effectiveFrom?: string; effectiveUntil?: string; jurisdiction?: string; language?: string; notes?: string }; schemaVersion: number };
export type ReadinessIssue = { code: string; category: string; field: string; severity: "warning" | "error"; message: string; blocking: boolean };

function canonicalize(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonicalize); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => [key, canonicalize(item)])); return value; }
export function normalizeContractDraft(input: ContractDraft): ContractDraft { return { ...input, title: input.title.trim(), content: input.content.trim(), clauses: input.clauses.filter((clause) => clause.enabled || clause.required).map((clause, order) => ({ ...clause, title: clause.title.trim(), content: clause.content.trim(), order, type: CONTRACT_CLAUSE_TYPES.includes(clause.type) ? clause.type : "custom" })), terms: { ...input.terms, currency: input.terms.currency || "BRL", subtotalCents: Math.trunc(input.terms.subtotalCents), discountCents: Math.trunc(input.terms.discountCents), totalCents: Math.trunc(input.terms.totalCents), entryAmountCents: Math.trunc(input.terms.entryAmountCents), installmentCount: Math.max(1, Math.trunc(input.terms.installmentCount)), installmentAmountCents: Math.trunc(input.terms.installmentAmountCents) }, metadata: { ...input.metadata, language: input.metadata.language || "pt-BR" }, schemaVersion: 1 }; }
export function validateContractDraft(input: ContractDraft): ReadinessIssue[] { const draft = normalizeContractDraft(input); const issues: ReadinessIssue[] = []; const add=(code:string,category:string,field:string,message:string,blocking=true)=>issues.push({code,category,field,severity:blocking?"error":"warning",message,blocking}); if (draft.title.length < 3) add("title_required","metadata","title","Informe o título do contrato."); if (!draft.parties.contractor.name) add("contractor_name","parties","contractor.name","Informe a contratada."); if (!draft.parties.client.name) add("client_name","parties","client.name","Informe o contratante."); for (const clause of draft.clauses.filter((item)=>item.required)) if (!clause.content) add("required_clause","clauses",clause.type,`Complete a cláusula obrigatória: ${clause.title}.`); if (!draft.clauses.some((item)=>item.type === "object" && item.content)) add("object_required","clauses","object","Informe o objeto do contrato."); if (!draft.clauses.some((item)=>item.type === "fees" && item.content)) add("fees_required","clauses","fees","Informe os honorários."); if (!draft.clauses.some((item)=>item.type === "term" && item.content)) add("term_required","clauses","term","Informe a vigência."); if (!draft.clauses.some((item)=>item.type === "termination" && item.content)) add("termination_required","clauses","termination","Informe a rescisão."); if (!draft.clauses.some((item)=>item.type === "confidentiality" && item.content)) add("confidentiality_required","clauses","confidentiality","Informe a confidencialidade."); if (!draft.clauses.some((item)=>item.type === "data_protection" && item.content)) add("data_protection_required","clauses","data_protection","Informe a proteção de dados."); if (!draft.metadata.jurisdiction) add("jurisdiction_required","metadata","jurisdiction","Informe o foro."); const terms=draft.terms; if ([terms.subtotalCents,terms.discountCents,terms.totalCents,terms.entryAmountCents,terms.installmentAmountCents].some((value)=>!Number.isSafeInteger(value) || value < 0) || terms.discountCents > terms.subtotalCents || terms.entryAmountCents > terms.totalCents) add("invalid_amounts","commercial","terms","Revise os valores comerciais."); return issues; }
export function buildContractVersionHash(draft: ContractDraft) { const normalized=normalizeContractDraft(draft); return createHash("sha256").update(JSON.stringify(canonicalize({schemaVersion:normalized.schemaVersion,parties:normalized.parties,clauses:normalized.clauses,terms:normalized.terms,metadata:normalized.metadata,content:normalized.content})),"utf8").digest("hex"); }
export function buildContractVersionPayload(draft: ContractDraft) { const normalized=normalizeContractDraft(draft); return { ...normalized, contentHash: buildContractVersionHash(normalized), readiness: validateContractDraft(normalized) }; }
export function compareContractWithAcceptedProposal(draft: ContractDraft, proposal: Record<string, unknown> | null) { if (!proposal) return []; const terms=draft.terms; const rows=[['totalCents',terms.totalCents],['entryAmountCents',terms.entryAmountCents],['installmentCount',terms.installmentCount]] as const; return rows.filter(([key,value])=>Number(proposal[key])!==value).map(([field,value])=>({changeType:"financial",field,before:proposal[field]??null,after:value,blocking:true})); }
export function compareContractVersions(a: ContractDraft,b: ContractDraft) { const diff: Array<{changeType:string;field:string;before:unknown;after:unknown;deltaCents?:number}> = []; if (a.title!==b.title) diff.push({changeType:"textual",field:"title",before:a.title,after:b.title}); if (a.metadata.jurisdiction!==b.metadata.jurisdiction) diff.push({changeType:"term",field:"jurisdiction",before:a.metadata.jurisdiction,after:b.metadata.jurisdiction}); if (a.terms.totalCents!==b.terms.totalCents) diff.push({changeType:"financial",field:"totalCents",before:a.terms.totalCents,after:b.terms.totalCents,deltaCents:b.terms.totalCents-a.terms.totalCents}); for(const clause of b.clauses){const old=a.clauses.find((item)=>item.type===clause.type && item.title===clause.title); if(!old) diff.push({changeType:"clause_added",field:clause.title,before:null,after:clause.content}); else if(old.content!==clause.content) diff.push({changeType:"obligation",field:clause.title,before:old.content,after:clause.content});} for(const clause of a.clauses) if(!b.clauses.some((item)=>item.type===clause.type && item.title===clause.title)) diff.push({changeType:"clause_removed",field:clause.title,before:clause.content,after:null}); return diff; }
export const calculateContractReadiness = validateContractDraft;
