"use server";

import { redirect } from "next/navigation";
import { getAppContext } from "@/lib/auth/context";
import { createProviderConfiguration, deleteDraftProviderConfiguration, disableProviderConfiguration, enableProviderConfiguration, replaceProviderCredentials, setDefaultProviderConfiguration, testProviderConnection, updateProviderConfiguration } from "@/lib/contracts/signatures/providers/credentials";
import { getSupabaseServerClient } from "@/lib/supabase/server";

async function context() { const current = await getAppContext(); if (current.status !== "ready" || !current.member || !current.lawFirm) redirect("/entrar"); const client = await getSupabaseServerClient(); const { data: { user } } = await client!.auth.getUser(); if (!user) redirect("/entrar"); return { lawFirmId: current.lawFirm.id, userId: user.id, role: current.member.role }; }
const value = (form: FormData, name: string) => String(form.get(name) ?? "");
const safeRedirect = (message: string) => redirect(`/configuracoes/assinaturas?mensagem=${encodeURIComponent(message)}`);

export async function providerConfigurationAction(form: FormData) { const c = await context(); const op = value(form, "operation"); const id = value(form, "id"); const lockVersion = Number(value(form, "lockVersion") || 1); const idempotencyKey = value(form, "idempotencyKey") || crypto.randomUUID(); try { if (op === "create") await createProviderConfiguration(c, { provider: value(form, "provider"), environment: value(form, "environment"), displayName: value(form, "displayName"), publicConfiguration: value(form, "publicConfiguration") ? JSON.parse(value(form, "publicConfiguration")) : {}, credentials: value(form, "credential") ? { apiToken: value(form, "credential") } : undefined, idempotencyKey }); else if (op === "replace") await replaceProviderCredentials(c, { id, credentials: { apiToken: value(form, "credential") }, lockVersion, idempotencyKey }); else if (op === "test") await testProviderConnection(c, { id, lockVersion, idempotencyKey }); else if (op === "enable") await enableProviderConfiguration({ ...c, productionConfirmation: value(form, "productionConfirmation") === "CONFIRM_PRODUCTION" }, { id, lockVersion, idempotencyKey, productionConfirmation: value(form, "productionConfirmation") === "CONFIRM_PRODUCTION" ? "CONFIRM_PRODUCTION" : undefined }); else if (op === "disable") await disableProviderConfiguration(c, { id, lockVersion, idempotencyKey }); else if (op === "default") await setDefaultProviderConfiguration(c, { id, lockVersion, idempotencyKey }); else if (op === "delete") await deleteDraftProviderConfiguration(c, { id, lockVersion, idempotencyKey }); else if (op === "update") await updateProviderConfiguration(c, { id, displayName: value(form, "displayName"), lockVersion, idempotencyKey }); safeRedirect("salvo"); } catch (error) { if (String((error as { digest?: string })?.digest ?? "").startsWith("NEXT_REDIRECT")) throw error; const code = String((error as { code?: string })?.code ?? (error as Error)?.message ?? "SIGNATURE_PROVIDER_OPERATION_FAILED").replace(/[^A-Z0-9_.:-]/gi, "_").slice(0, 100); safeRedirect(`erro:${code}`); } }
