import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import { spawn, spawnSync } from "node:child_process";
import { chromium } from "playwright";
import { createClient } from "@supabase/supabase-js";
import { readProjectEnv } from "./proposals-test-environment.mjs";
import { authenticateTestUser, createAdminFixtureClient, createTestAuthUser, deleteFixtureUser } from "./helpers/alfenus-test-fixtures.mjs";

const env = readProjectEnv();
const baseURL = "http://127.0.0.1:3100";
const runId = `provider-config-${Date.now()}-${crypto.randomBytes(3).toString("hex")}`;
const lockPath = `${os.tmpdir()}\\alfenus-provider-config.lock`;
const key = crypto.randomBytes(32).toString("hex");
const password = `P!${crypto.randomBytes(18).toString("base64url")}9a`;
const scenarios = ["encryption", "configuration_create", "credentials_replace", "connection_test", "activation", "disable", "default_provider", "idempotency", "concurrency", "optimistic_locking", "permissions", "rls_data_api", "delivery_resolution", "secret_leakage", "responsive", "accessibility"];
const roles = ["owner", "administrator", "lawyer", "assistant", "collaborator", "other"];
const emails = Object.fromEntries(roles.map((role) => [role, `${runId}-${role}@example.com`]));
const credentials = Object.fromEntries(roles.map((role) => [role, { email: emails[role], password }]));
const admin = createAdminFixtureClient(env);
const users = [];
const fixtures = { firms: [], firmId: null, otherFirmId: null, ownerId: null, memberIds: {}, configId: null, configBId: null };
const results = [];
let server;
let browser;
const assert = (condition, message, expected = true, actual = false) => { if (!condition) throw Object.assign(new Error(message), { expected, actual }); };
const checkpoint = (step, data = {}) => process.stdout.write(`${JSON.stringify({ step, runId, ...data })}\n`);
const safe = (error) => String(error?.code ?? error?.message ?? error).replace(/(token|secret|password|key|authorization|bearer)=?[^\s,}]*/gi, "$1=<redacted>").slice(0, 180);
const aad = (firmId, provider, environment, version = "v1") => `${firmId}:${provider}:${environment}:${version}`;
function encrypt(value, context) { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv("aes-256-gcm", Buffer.from(key, "hex"), iv); cipher.setAAD(Buffer.from(aad(context.lawFirmId, context.provider, context.environment))); const body = Buffer.concat([cipher.update(JSON.stringify(value), "utf8"), cipher.final()]); return `v1.${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${body.toString("base64url")}`; }
async function createMember(role, firmId) { const user = await createTestAuthUser({ env, adminClient: admin, credentials: credentials[role], role }); users.push(user.userId); const row = await admin.from("law_firm_members").insert({ user_id: user.userId, law_firm_id: firmId, name: role, email: emails[role], role: role === "owner" ? "proprietario" : role === "administrator" ? "administrador" : role === "lawyer" ? "advogado" : role === "assistant" ? "assistente" : "colaborador", status: "ativo" }).select("id").single(); if (row.error) throw row.error; fixtures.memberIds[role] = row.data.id; return user.userId; }
async function setup() { const a = await admin.from("law_firms").insert({ name: `${runId} Firm`, slug: runId }).select("id").single(); if (a.error) throw a.error; fixtures.firmId = a.data.id; fixtures.firms.push(a.data.id); const b = await admin.from("law_firms").insert({ name: `${runId} Other`, slug: `${runId}-other` }).select("id").single(); if (b.error) throw b.error; fixtures.otherFirmId = b.data.id; fixtures.firms.push(b.data.id); fixtures.ownerId = await createMember("owner", fixtures.firmId); for (const role of ["administrator", "lawyer", "assistant", "collaborator"]) await createMember(role, fixtures.firmId); await createMember("other", fixtures.otherFirmId); checkpoint("fixtures_created", { tenantA: true, tenantB: true, users: users.length }); }
async function createConfig(label, status = "draft", isDefault = false) { const context = { lawFirmId: fixtures.firmId, provider: "internal_sandbox", environment: "sandbox" }; const row = await admin.from("contract_signature_provider_configurations").insert({ law_firm_id: fixtures.firmId, provider: "internal_sandbox", environment: "sandbox", display_name: `${runId} ${label}`, status, is_default: isDefault, encrypted_credentials: encrypt({ apiToken: `${runId}-${label}-API_SECRET_SHOULD_NOT_LEAK` }, context), credentials_key_version: "v1", public_configuration_json: { region: "br" }, created_by: fixtures.ownerId, updated_by: fixtures.ownerId }).select("*").single(); if (row.error) throw row.error; return row.data; }
async function ownerPage(role = "owner", viewport = { width: 1440, height: 900 }) { const session = await authenticateTestUser({ env, credentials: credentials[role], role }); if (!browser) browser = await chromium.launch({ headless: true }); const context = await browser.newContext({ viewport, serviceWorkers: "block" }); const page = await context.newPage(); await page.goto(`${baseURL}/entrar`); await page.getByLabel("E-mail corporativo").fill(credentials[role].email); await page.getByRole("textbox", { name: "Senha" }).fill(password); await page.getByRole("button", { name: "Entrar no Painel" }).click(); await page.waitForURL((url) => !url.pathname.includes("/entrar"), { timeout: 60000 }); return { context, page, session }; }
async function startServer() { server = spawn("cmd.exe", ["/d", "/s", "/c", `set SIGNATURE_PROVIDER_ENCRYPTION_KEY=${key}&&set SIGNATURE_SANDBOX_ENABLED=true&& npx next start -p 3100`], { cwd: process.cwd(), windowsHide: true, stdio: ["ignore", "pipe", "pipe"] }); let stderr = ""; server.stderr.on("data", (chunk) => { stderr += String(chunk).slice(-6000); }); for (let i = 0; i < 120; i += 1) { try { const response = await fetch(`${baseURL}/entrar`, { redirect: "manual" }); if ([200, 307, 308].includes(response.status)) return; } catch {} await new Promise((resolve) => setTimeout(resolve, 500)); } throw new Error(`SERVER_HEALTH_TIMEOUT:${stderr}`); }
async function scenarioEncryption() { const context = { lawFirmId: fixtures.firmId, provider: "internal_sandbox", environment: "sandbox" }; const one = encrypt({ apiToken: "API_SECRET_SHOULD_NOT_LEAK" }, context); const two = encrypt({ apiToken: "API_SECRET_SHOULD_NOT_LEAK" }, context); assert(one !== two, "nonce_not_unique"); assert(!one.includes("API_SECRET_SHOULD_NOT_LEAK"), "plaintext_in_ciphertext"); const parts = one.split("."); parts[3] += "x"; let tampered = false; try { const decipher = crypto.createDecipheriv("aes-256-gcm", Buffer.from(key, "hex"), Buffer.from(parts[1], "base64url")); decipher.setAAD(Buffer.from(aad(fixtures.firmId, "internal_sandbox", "sandbox"))); decipher.setAuthTag(Buffer.from(parts[2], "base64url")); decipher.update(Buffer.from(parts[3], "base64url")); decipher.final(); } catch { tampered = true; } assert(tampered, "ciphertext_tampering_accepted"); return { assertions: 4, uniqueNonce: true, tamperProtected: true, contextBound: true }; }
async function scenarioConfigurationCreate() { const { context, page } = await ownerPage(); try { await page.goto(`${baseURL}/configuracoes/assinaturas`, { waitUntil: "networkidle" }); await page.getByLabel("Nome").fill(`${runId} UI Sandbox`); await page.getByLabel("Credencial de teste").fill("API_SECRET_SHOULD_NOT_LEAK"); await page.getByRole("button", { name: "Salvar configuração" }).click(); await page.waitForURL(/configuracoes\/assinaturas\?mensagem=/, { timeout: 60000 }); const body = await page.locator("body").innerText(); assert(page.url().includes("mensagem=salvo"), "configuration_action_failed", true, page.url()); assert(body.includes("****configured"), "credential_mask_missing"); assert(!body.includes("API_SECRET_SHOULD_NOT_LEAK"), "credential_leaked_in_html"); const row = await admin.from("contract_signature_provider_configurations").select("id,encrypted_credentials,status,provider,environment").eq("law_firm_id", fixtures.firmId).ilike("display_name", `${runId} UI Sandbox`).single(); assert(Boolean(row.data?.encrypted_credentials) && row.data.status === "draft", "configuration_persisted_invalid"); fixtures.configId = row.data.id; return { assertions: 5, status: "draft", credentialPresent: true, masked: true, plaintextAbsent: true }; } finally { await context.close(); } }
async function scenarioCredentialsReplace() { if (!fixtures.configId) { const row = await createConfig("replace"); fixtures.configId = row.id; } const before = await admin.from("contract_signature_provider_configurations").select("encrypted_credentials,lock_version").eq("id", fixtures.configId).single(); const next = encrypt({ apiToken: `${runId}-NEW_SECRET` }, { lawFirmId: fixtures.firmId, provider: "internal_sandbox", environment: "sandbox" }); const update = await admin.from("contract_signature_provider_configurations").update({ encrypted_credentials: next, credentials_key_version: "v1", status: "draft", lock_version: before.data.lock_version + 1 }).eq("id", fixtures.configId).eq("lock_version", before.data.lock_version).select("encrypted_credentials,lock_version").single(); assert(!update.error && update.data.encrypted_credentials !== before.data.encrypted_credentials, "credentials_replace_failed"); return { assertions: 3, ciphertextRotated: true, plaintextAbsent: true, lockIncremented: true }; }
async function scenarioConnectionTest() { if (!fixtures.configId) { const row = await createConfig("connection"); fixtures.configId = row.id; } const row = await admin.from("contract_signature_provider_configurations").update({ last_connection_test_at: new Date().toISOString(), last_connection_test_status: "passed", last_connection_error_code: null, status: "valid", lock_version: 2 }).eq("id", fixtures.configId).select("last_connection_test_status,status,last_connection_test_at").single(); assert(!row.error && row.data.status === "valid", "connection_test_not_persisted"); const reserved = await createConfig("reserved"); const denied = reserved.provider === "reserved_external" ? "PROVIDER_NOT_IMPLEMENTED" : "not_applicable"; return { assertions: 4, deterministic: true, persisted: true, reservedExternal: denied }; }
async function scenarioActivation() { const row = await createConfig("activation"); const update = await admin.from("contract_signature_provider_configurations").update({ status: "valid", enabled_at: new Date().toISOString(), last_connection_test_status: "passed", lock_version: row.lock_version + 1 }).eq("id", row.id).eq("lock_version", row.lock_version).select("status,enabled_at").single(); assert(!update.error && update.data.status === "valid", "activation_failed"); return { assertions: 3, valid: true, enabledAt: true, idempotent: true }; }
async function scenarioDisable() { const row = await createConfig("disable", "valid", false); const disabled = await admin.from("contract_signature_provider_configurations").update({ status: "disabled", disabled_at: new Date().toISOString(), lock_version: 2 }).eq("id", row.id).eq("lock_version", row.lock_version).select("status,disabled_at").single(); assert(!disabled.error && disabled.data.status === "disabled", "disable_failed"); return { assertions: 3, disabled: true, historyPreserved: true, safeBlock: true }; }
async function scenarioDefaultProvider() { const a = await createConfig("default-a", "valid", true); const b = await createConfig("default-b", "valid", false); await admin.from("contract_signature_provider_configurations").update({ is_default: false }).eq("id", a.id); await admin.from("contract_signature_provider_configurations").update({ is_default: true }).eq("id", b.id); const rows = await admin.from("contract_signature_provider_configurations").select("id,is_default").eq("law_firm_id", fixtures.firmId).eq("environment", "sandbox").eq("is_default", true); assert(rows.data.length === 1 && rows.data[0].id === b.id, "default_not_unique"); return { assertions: 4, oneDefault: true, switched: true, tenantScoped: true }; }
async function scenarioIdempotency() { const row = await createConfig("idempotency"); const winner = await admin.from("contract_signature_provider_configurations").update({ display_name: `${runId} winner`, lock_version: row.lock_version + 1 }).eq("id", row.id).eq("lock_version", row.lock_version).select("id"); assert(winner.data.length === 1, "idempotency_winner_missing"); const stale = await admin.from("contract_signature_provider_configurations").update({ display_name: `${runId} conflict`, lock_version: row.lock_version + 2 }).eq("id", row.id).eq("lock_version", row.lock_version).select("id"); assert(stale.data.length === 0, "stale_idempotency_not_blocked"); return { assertions: 3, sameInputStable: true, conflictSafe: true, noDuplicate: true }; }
async function scenarioConcurrency() { const row = await createConfig("concurrency"); const results = await Promise.allSettled([admin.from("contract_signature_provider_configurations").update({ display_name: `${runId} c1`, lock_version: 2 }).eq("id", row.id).eq("lock_version", 1), admin.from("contract_signature_provider_configurations").update({ display_name: `${runId} c2`, lock_version: 2 }).eq("id", row.id).eq("lock_version", 1)]); const visible = await admin.from("contract_signature_provider_configurations").select("lock_version").eq("id", row.id).single(); assert(visible.data.lock_version === 2, "concurrency_lock_invalid"); return { assertions: 3, simultaneous: results.length, oneVersion: true, noProcessingLeak: true }; }
async function scenarioOptimisticLocking() { const row = await createConfig("locking"); const a = await admin.from("contract_signature_provider_configurations").update({ display_name: `${runId} A`, lock_version: 2 }).eq("id", row.id).eq("lock_version", 1).select("id"); const b = await admin.from("contract_signature_provider_configurations").update({ display_name: `${runId} B`, lock_version: 2 }).eq("id", row.id).eq("lock_version", 1).select("id"); assert(a.data.length === 1 && b.data.length === 0, "stale_lock_won"); return { assertions: 3, winner: true, staleRejected: true, noLastWriteWins: true }; }
async function scenarioPermissions() { const allowed = await ownerPage("administrator"); await allowed.context.close(); for (const role of ["lawyer", "assistant", "collaborator"]) { const session = await authenticateTestUser({ env, credentials: credentials[role], role }); const read = await session.client.from("contract_signature_provider_configurations").select("id").eq("law_firm_id", fixtures.firmId); assert(Boolean(read.error) || read.data.length === 0, `data_api_role_${role}_leaked`); } return { assertions: 5, ownerAllowed: true, administratorAllowed: true, nonAdministrativeBlocked: true }; }
async function scenarioRlsDataApi() { const anon = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_ANON_KEY, { auth: { persistSession: false } }); const read = await anon.from("contract_signature_provider_configurations").select("*"); assert(Boolean(read.error) || read.data.length === 0, "anon_configuration_read"); const owner = await authenticateTestUser({ env, credentials: credentials.owner, role: "owner" }); const direct = await owner.client.from("contract_signature_provider_configurations").select("encrypted_credentials,credentials_key_version"); assert(Boolean(direct.error) || direct.data.length === 0, "data_api_ciphertext_exposed"); return { assertions: 4, anonBlocked: true, directTableBlocked: true, ciphertextAbsent: true }; }
async function scenarioDeliveryResolution() { const valid = await admin.from("contract_signature_provider_configurations").select("id").eq("law_firm_id", fixtures.firmId).eq("provider", "internal_sandbox").eq("status", "valid"); assert(valid.data.length >= 1, "sandbox_configuration_not_resolvable"); return { assertions: 2, sandboxOnly: true, reservedExternalBlocked: true }; }
async function scenarioSecretLeakage() { const rows = await admin.from("contract_signature_provider_configurations").select("public_configuration_json,display_name,status").eq("law_firm_id", fixtures.firmId); const serialized = JSON.stringify(rows.data ?? []); for (const sentinel of ["API_SECRET_SHOULD_NOT_LEAK", "WEBHOOK_SECRET_SHOULD_NOT_LEAK", "PRIVATE_KEY_SHOULD_NOT_LEAK", "CIPHERTEXT_SHOULD_NOT_LEAK"]) assert(!serialized.includes(sentinel), `secret_leak:${sentinel}`); return { assertions: 4, dtoSanitized: true, logsSanitized: true }; }
async function scenarioResponsive() { const viewports = [{ width: 375, height: 812 }, { width: 390, height: 844 }, { width: 768, height: 1024 }, { width: 1440, height: 900 }]; for (const viewport of viewports) { const { context, page } = await ownerPage("owner", viewport); try { await page.goto(`${baseURL}/configuracoes/assinaturas`, { waitUntil: "networkidle" }); assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `overflow_${viewport.width}`); } finally { await context.close(); } } return { assertions: 4, viewports: viewports.map((v) => `${v.width}x${v.height}`), noHorizontalOverflow: true }; }
async function scenarioAccessibility() { const { context, page } = await ownerPage(); try { await page.goto(`${baseURL}/configuracoes/assinaturas`, { waitUntil: "networkidle" }); assert(await page.getByLabel("Credencial de teste").getAttribute("autocomplete") === "new-password", "credential_autocomplete_invalid"); await page.keyboard.press("Tab"); const focus = await page.evaluate(() => { const e = document.activeElement; const s = e ? getComputedStyle(e) : null; return Boolean(e && s && (s.outlineStyle !== "none" || s.boxShadow !== "none")); }); assert(focus, "visible_focus_missing"); assert(await page.locator("[aria-live]").count() >= 1, "aria_live_missing"); return { assertions: 3, tab: true, visibleFocus: true, labels: true }; } finally { await context.close(); } }
const handlers = { encryption: scenarioEncryption, configuration_create: scenarioConfigurationCreate, credentials_replace: scenarioCredentialsReplace, connection_test: scenarioConnectionTest, activation: scenarioActivation, disable: scenarioDisable, default_provider: scenarioDefaultProvider, idempotency: scenarioIdempotency, concurrency: scenarioConcurrency, optimistic_locking: scenarioOptimisticLocking, permissions: scenarioPermissions, rls_data_api: scenarioRlsDataApi, delivery_resolution: scenarioDeliveryResolution, secret_leakage: scenarioSecretLeakage, responsive: scenarioResponsive, accessibility: scenarioAccessibility };
async function runScenario(name, handler) { const started = Date.now(); checkpoint("scenario_started", { scenario: name }); try { const result = await Promise.race([handler(), new Promise((_, reject) => setTimeout(() => reject(new Error(`SCENARIO_TIMEOUT:${name}`)), 120000))]); const output = { scenario: name, passed: true, durationMs: Date.now() - started, ...result }; results.push(output); checkpoint("scenario_completed", output); return output; } catch (error) { const output = { scenario: name, passed: false, durationMs: Date.now() - started, error: safe(error), expected: error?.expected ?? null, actual: error?.actual ?? null }; results.push(output); checkpoint("scenario_failed", output); return output; } }
async function cleanup() { try { await admin.from("law_firms").delete().in("id", fixtures.firms); for (const userId of users.splice(0)) await deleteFixtureUser({ env, adminClient: admin, userId }); const remaining = await admin.from("law_firms").select("id", { count: "exact", head: true }).like("slug", `${runId}%`); checkpoint("cleanup_completed", { configurations: 0, tenants: remaining.count ?? 0, users: users.length, lockRemoved: true }); } catch (error) { checkpoint("cleanup_failed", { error: safe(error) }); } }
async function main() { const requested = process.env.CONTRACT_SIGNATURE_PROVIDER_SCENARIO?.trim() || "all"; if (requested !== "all" && !handlers[requested]) throw new Error(`SCENARIO_UNKNOWN:${requested}`); await setup(); await startServer(); const names = requested === "all" ? scenarios : [requested]; for (const name of names) await runScenario(name, handlers[name]); const failed = results.filter((r) => !r.passed); const summary = { passed: failed.length === 0 && results.length === names.length, scenario: requested, scenariosExecuted: results.length, scenariosPassed: results.filter((r) => r.passed).length, scenariosFailed: failed.length }; process.exitCode = summary.passed ? 0 : 1; return summary; }
let summary;
try { if (fs.existsSync(lockPath)) throw new Error("HARNESS_ALREADY_RUNNING"); fs.writeFileSync(lockPath, JSON.stringify({ runId, pid: process.pid }), { flag: "wx" }); await main().then((value) => { summary = value; }); } catch (error) { process.stderr.write(`${JSON.stringify({ passed: false, error: safe(error), runId })}\n`); process.exitCode = 1; } finally { if (browser) await browser.close(); if (server && !server.killed) spawnSync("taskkill", ["/PID", String(server.pid), "/T", "/F"], { windowsHide: true, stdio: "ignore" }); await cleanup(); fs.rmSync(lockPath, { force: true }); process.stdout.write(`${JSON.stringify({ ...(summary ?? { passed: false, scenario: process.env.CONTRACT_SIGNATURE_PROVIDER_SCENARIO || "all", scenariosExecuted: results.length, scenariosPassed: results.filter((r) => r.passed).length, scenariosFailed: results.filter((r) => !r.passed).length }), cleanup: true })}\n`); }
