import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawn, spawnSync } from "node:child_process";
import { chromium } from "playwright";
import { createClient } from "@supabase/supabase-js";
import { readProjectEnv } from "./proposals-test-environment.mjs";
import { authenticateTestUser, createAdminFixtureClient, createTestAuthUser, deleteFixtureUser } from "./helpers/alfenus-test-fixtures.mjs";

const env = readProjectEnv();
const baseURL = "http://127.0.0.1:3100";
const admin = createAdminFixtureClient(env);
const runId = `signature-delivery-${Date.now()}-${crypto.randomBytes(3).toString("hex")}`;
const lockPath = path.join(os.tmpdir(), "alfenus-contract-signature-delivery.lock");
const password = `P!${crypto.randomBytes(18).toString("base64url")}9a`;
const scenarios = ["adapter_registry", "send", "send_idempotency", "reconciliation", "send_concurrency", "temporary_failure_retry", "permanent_failure", "webhook_validation", "webhook_idempotency", "webhook_out_of_order", "partial_signature", "completed_signature", "refusal", "expiration", "cancellation", "permissions", "rls_data_api", "snapshot_security", "responsive", "accessibility"];
const emails = Object.fromEntries(["owner", "administrator", "lawyer", "assistant", "collaborator", "orphan", "other"].map((role) => [role, `${runId}-${role}@example.com` ]));
const credentials = Object.fromEntries(Object.entries(emails).map(([role, email]) => [role, { email, password }]));
const users = [];
const fixtures = { envelopes: {}, documents: [], versions: [], firms: [], contractId: null, firmId: null, otherFirmId: null, ownerId: null };
const results = [];
let server;
let browser;
const assert = (condition, message, extra = {}) => { if (!condition) throw Object.assign(new Error(message), { expected: true, actual: extra }); };
const sha = (value) => crypto.createHash("sha256").update(value, "utf8").digest("hex");
const checkpoint = (step, data = {}) => process.stdout.write(`${JSON.stringify({ step, runId, ...data })}\n`);
const safe = (error) => String(error?.message ?? error).replace(/(token|secret|password|key|path)=?[^\s,}]*/gi, "$1=<redacted>");

async function member(role, firmId, name = role) { const user = await createTestAuthUser({ env, adminClient: admin, credentials: credentials[role], role }); users.push(user.userId); const row = await admin.from("law_firm_members").insert({ user_id: user.userId, law_firm_id: firmId, name, email: emails[role], role: role === "administrator" ? "administrador" : role === "lawyer" ? "advogado" : role === "assistant" ? "assistente" : role === "collaborator" ? "colaborador" : "proprietario", status: "ativo" }).select("id").single(); if (row.error) throw row.error; return user.userId; }
async function createVersion(firmId, contractId, userId, title) { const row = await admin.from("contract_conversion_versions").insert({ law_firm_id: firmId, contract_id: contractId, version_number: fixtures.versions.length + 1, title, content: "Servicos juridicos do envelope de teste.", snapshot_json: { internalNotes: "INTERNAL_NOTE_SHOULD_NOT_LEAK", pricingSnapshot: { cost: "INTERNAL_COST_SHOULD_NOT_LEAK" } }, snapshot_hash: sha(`${runId}-${title}`), created_by: userId, parties_json: { contractor: { name: "Alfenus" }, client: { name: "Cliente de teste" } }, commercial_terms_json: { currency: "BRL", totalCents: 10000 }, metadata_json: { memory: "PRICING_MEMORY_SHOULD_NOT_LEAK", storagePath: "STORAGE_PATH_SHOULD_NOT_LEAK" }, readiness_json: [], is_active: fixtures.versions.length === 0 }).select("id").single(); if (row.error) throw row.error; fixtures.versions.push(row.data.id); const clauses = await admin.from("contract_conversion_clauses").insert([{ law_firm_id: firmId, contract_id: contractId, version_id: row.data.id, title: "Objeto", content: "Objeto do contrato.", order_index: 0 }, { law_firm_id: firmId, contract_id: contractId, version_id: row.data.id, title: "Honorarios", content: "Honorarios do contrato.", order_index: 1 }]); if (clauses.error) throw clauses.error; return row.data.id; }
async function createDocument(firmId, contractId, versionId, userId, label) { const row = await admin.from("contract_documents").insert({ law_firm_id: firmId, contract_id: contractId, contract_version_id: versionId, document_type: "contract", status: "completed", storage_bucket: "documents", storage_path: `${runId}/${label}.pdf`, file_name: `${label}.pdf`, mime_type: "application/pdf", file_size: 2048, page_count: 2, contract_content_hash: sha(`${runId}-${label}-content`), renderer_version: "delivery-test", template_version: "delivery-test-v1", file_hash: sha(`${runId}-${label}-file`), generated_by: userId, metadata: { internalNotes: "INTERNAL_NOTE_SHOULD_NOT_LEAK", storagePath: "STORAGE_PATH_SHOULD_NOT_LEAK" } }).select("id").single(); if (row.error) throw row.error; fixtures.documents.push(row.data.id); return row.data.id; }
async function createEnvelope(label, documentId, versionId, status = "prepared") { const id = crypto.randomUUID(); const inputHash = sha(`${runId}-${label}`); const row = await admin.from("contract_signature_envelopes").insert({ id, law_firm_id: fixtures.firmId, contract_id: fixtures.contractId, contract_document_id: documentId, contract_version_id: versionId, status, title: `${runId} ${label}`, document_hash: sha(`${runId}-${label}-doc`), document_file_size: 2048, document_page_count: 2, document_snapshot_json: { envelopeId: id, contractId: fixtures.contractId, contractDocumentId: documentId, contractVersionId: versionId, documentHash: sha(`${runId}-${label}-doc`), title: `${runId} ${label}`, signers: [{ name: "Cliente", email: emails.owner, signingOrder: 1 }, { name: "Testemunha", email: emails.other, signingOrder: 2 }], internalNotes: "INTERNAL_NOTE_SHOULD_NOT_LEAK", pricingSnapshot: "INTERNAL_COST_SHOULD_NOT_LEAK", storagePath: "STORAGE_PATH_SHOULD_NOT_LEAK" }, consent_version: "delivery-test-v1", signing_order_enabled: true, prepared_at: status === "prepared" ? new Date().toISOString() : null, created_by: fixtures.ownerId, updated_by: fixtures.ownerId, lock_version: status === "prepared" ? 2 : 1, idempotency_key: `${runId}-${label}`, input_hash: inputHash }).select("id").single(); if (row.error) throw row.error; const signers = await admin.from("contract_signature_signers").insert([{ law_firm_id: fixtures.firmId, envelope_id: id, signer_type: "person", role: "cliente", name: "Cliente", email: emails.owner, signing_order: 1, requires_identity_verification: false, status: "pending" }, { law_firm_id: fixtures.firmId, envelope_id: id, signer_type: "internal_witness", role: "testemunha", name: "Testemunha", email: emails.other, signing_order: 2, requires_identity_verification: false, status: "pending" }]); if (signers.error) throw signers.error; const ev = await admin.from("contract_signature_events").insert({ law_firm_id: fixtures.firmId, envelope_id: id, event_type: status === "prepared" ? "signature_envelope_prepared" : "signature_envelope_created", actor_user_id: fixtures.ownerId, deduplication_key: `${runId}-${label}-created`, safe_metadata_json: {} }); if (ev.error) throw ev.error; fixtures.envelopes[label] = { id, documentId, versionId }; return fixtures.envelopes[label]; }
async function markSent(label) { const item = fixtures.envelopes[label]; const providerEnvelopeId = `sandbox-${sha(item.id).slice(0, 24)}`; const delivery = await admin.from("contract_signature_provider_deliveries").insert({ law_firm_id: fixtures.firmId, envelope_id: item.id, provider: "internal_sandbox", provider_envelope_id: providerEnvelopeId, status: "sent", attempt_number: 1, request_snapshot_json: { envelopeId: item.id, documentHash: sha(`${runId}-${label}-doc`) }, response_snapshot_json: { provider: "internal_sandbox", status: "sent" }, sent_at: new Date().toISOString(), last_synced_at: new Date().toISOString(), lock_version: 2 }).select("id").single(); if (delivery.error) throw delivery.error; const up = await admin.from("contract_signature_envelopes").update({ status: "sent", provider: "internal_sandbox", provider_envelope_id: providerEnvelopeId, lock_version: 3, updated_by: fixtures.ownerId }).eq("id", item.id).eq("status", "prepared"); if (up.error) throw up.error; item.providerEnvelopeId = providerEnvelopeId; return item; }
async function setup() { checkpoint("fixtures_started"); const firm = await admin.from("law_firms").insert({ name: `${runId} Firm`, slug: runId }).select("id").single(); if (firm.error) throw firm.error; fixtures.firmId = firm.data.id; fixtures.firms.push(fixtures.firmId); const otherFirm = await admin.from("law_firms").insert({ name: `${runId} Other`, slug: `${runId}-other` }).select("id").single(); if (otherFirm.error) throw otherFirm.error; fixtures.otherFirmId = otherFirm.data.id; fixtures.firms.push(fixtures.otherFirmId); fixtures.ownerId = await member("owner", fixtures.firmId, "Delivery Owner"); for (const role of ["administrator", "lawyer", "assistant", "collaborator"]) await member(role, fixtures.firmId); const orphan = await createTestAuthUser({ env, adminClient: admin, credentials: credentials.orphan, role: "orphan" }); users.push(orphan.userId); await member("other", fixtures.otherFirmId); const client = await admin.from("clients").insert({ law_firm_id: fixtures.firmId, name: `${runId} Client`, person_type: "fisica" }).select("id").single(); if (client.error) throw client.error; const contract = await admin.from("contracts").insert({ law_firm_id: fixtures.firmId, client_id: client.data.id, service_description: `${runId} Contract`, total_amount_cents: 10000, upfront_amount_cents: 1000, balance_cents: 9000, has_installments: true, installments_count: 2, status: "rascunho" }).select("id").single(); if (contract.error) throw contract.error; fixtures.contractId = contract.data.id; const version = await createVersion(fixtures.firmId, fixtures.contractId, fixtures.ownerId, `${runId} Contract Version`); const document = await createDocument(fixtures.firmId, fixtures.contractId, version, fixtures.ownerId, "primary"); for (const label of ["temporary", "permanent", "partial", "refusal", "expiration", "cancellation", "reconciliation", "concurrency"]) { const v = label === "temporary" ? await createVersion(fixtures.firmId, fixtures.contractId, fixtures.ownerId, `${runId} [temporary-failure]`) : label === "permanent" ? await createVersion(fixtures.firmId, fixtures.contractId, fixtures.ownerId, `${runId} [permanent-failure]`) : version; await createEnvelope(label, document, v); await markSent(label); } await createEnvelope("primary", document, version); checkpoint("fixtures_created", { tenantA: true, tenantB: true, signers: 2, envelopes: Object.keys(fixtures.envelopes).length }); }
async function startServer() { server = spawn("cmd.exe", ["/d", "/s", "/c", "set SIGNATURE_SANDBOX_ENABLED=true&& npx next start -p 3100"], { cwd: process.cwd(), windowsHide: true, stdio: ["ignore", "pipe", "pipe"] }); let stderr = ""; server.stdout.on("data", (chunk) => process.stdout.write(String(chunk))); server.stderr.on("data", (chunk) => { stderr += String(chunk).slice(-8000); process.stderr.write(String(chunk)); }); for (let i = 0; i < 120; i++) { try { const response = await fetch(`${baseURL}/entrar`, { redirect: "manual" }); if ([200, 307, 308].includes(response.status)) return; } catch {} await new Promise((resolve) => setTimeout(resolve, 500)); } throw new Error(`SERVER_HEALTH_TIMEOUT:${stderr}`); }
async function ownerPage(viewport = { width: 1440, height: 900 }) { if (!browser) browser = await chromium.launch({ headless: true }); const context = await browser.newContext({ viewport, serviceWorkers: "block" }); const page = await context.newPage(); await page.goto(`${baseURL}/entrar`); await page.getByLabel("E-mail corporativo").fill(emails.owner); await page.getByRole("textbox", { name: "Senha" }).fill(password); await page.getByRole("button", { name: "Entrar no Painel" }).click(); await page.waitForURL((url) => !url.pathname.includes("/entrar"), { timeout: 60000 }); return { context, page }; }
async function sendThroughUI() { const { context, page } = await ownerPage(); const errors = []; page.on("pageerror", (error) => errors.push(error.message)); page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); }); try { await page.goto(`${baseURL}/contratos/${fixtures.contractId}/assinatura`, { waitUntil: "networkidle" }); const prepare = page.getByRole("button", { name: "Preparar envelope" }); if (await prepare.count()) await prepare.click(); const send = page.getByRole("button", { name: "Enviar para assinatura" }); assert(await send.count() === 1, "send_button_missing", { url: page.url(), body: (await page.locator("body").innerText()).slice(0, 1500) }); await send.dblclick(); for (let i = 0; i < 60; i++) { const row = (await admin.from("contract_signature_provider_deliveries").select("status,provider_envelope_id,last_error_code").eq("envelope_id", fixtures.envelopes.primary.id).maybeSingle()).data; if (row?.status === "sent") return row; if (row?.status === "failed") throw new Error(`SEND_FAILED:${JSON.stringify(row)}:${errors.join("|")}`); await new Promise((resolve) => setTimeout(resolve, 500)); } throw new Error(`SEND_TIMEOUT:${errors.join("|")}`); } finally { await context.close(); } }
function webhookPayload(providerEnvelopeId, eventType, signerEmails = [], eventId = `${runId}-${providerEnvelopeId}-${eventType}`) { const body = JSON.stringify({ providerEventId: eventId, providerEnvelopeId, eventType, signerEmails }); const signature = crypto.createHmac("sha256", env.SIGNATURE_SANDBOX_WEBHOOK_SECRET ?? "alfenus-internal-sandbox").update(body).digest("hex"); return { body, headers: { "content-type": "application/json", "x-alfenus-sandbox-signature": signature } }; }
async function postWebhook(item, eventType, signerEmails = [], eventId) { const payload = webhookPayload(item.providerEnvelopeId, eventType, signerEmails, eventId); const response = await fetch(`${baseURL}/api/signatures/webhooks/internal_sandbox`, { method: "POST", headers: payload.headers, body: payload.body }); const data = await response.json().catch(() => ({})); return { response, data }; }
async function scenarioAdapterRegistry() { const unknown = await fetch(`${baseURL}/api/signatures/webhooks/not-a-provider`, { method: "POST", body: "{}" }); assert(unknown.status === 404, "unknown_provider_not_rejected", { status: unknown.status }); const bad = await fetch(`${baseURL}/api/signatures/webhooks/internal_sandbox`, { method: "POST", body: "{}" }); assert(bad.status === 400, "sandbox_validation_not_rejected", { status: bad.status }); return { provider: "internal_sandbox", unknownRejected: true, concrete: true }; }
async function scenarioSend() { const row = await sendThroughUI(); fixtures.envelopes.primary.providerEnvelopeId = row.provider_envelope_id; assert(row.provider_envelope_id?.startsWith("sandbox-"), "provider_id_missing"); let events; for (let attempt = 0; attempt < 100; attempt += 1) { events = await admin.from("contract_signature_events").select("event_type,deduplication_key").eq("envelope_id", fixtures.envelopes.primary.id); if (events.data.filter((e) => e.event_type === "signature_envelope_sent").length === 1) break; await new Promise((resolve) => setTimeout(resolve, 100)); } assert(events.data.filter((e) => e.event_type === "signature_envelope_sent").length === 1, "sent_event_not_unique"); return { status: row.status, providerEnvelopeId: true, events: 1 }; }
async function scenarioSendIdempotency() { const delivery = await admin.from("contract_signature_provider_deliveries").select("id,provider_envelope_id").eq("envelope_id", fixtures.envelopes.primary.id).single(); const before = await admin.from("contract_signature_events").select("id", { count: "exact", head: true }).eq("envelope_id", fixtures.envelopes.primary.id).eq("event_type", "signature_envelope_sent"); const again = await admin.from("contract_signature_outbox").insert({ law_firm_id: fixtures.firmId, envelope_id: fixtures.envelopes.primary.id, operation_type: "send", status: "completed", attempt_count: 1, completed_at: new Date().toISOString(), idempotency_key: `delivery-${fixtures.envelopes.primary.id}-pending-1`, input_hash: sha("different-input") }); assert(Boolean(again.error), "idempotency_conflict_not_rejected"); const after = await admin.from("contract_signature_events").select("id", { count: "exact", head: true }).eq("envelope_id", fixtures.envelopes.primary.id).eq("event_type", "signature_envelope_sent"); assert(before.count === after.count, "retry_after_sent_added_event"); return { sameDelivery: true, sameProviderEnvelopeId: Boolean(delivery.data?.provider_envelope_id), conflict: true }; }
async function scenarioSendConcurrency() { const item = fixtures.envelopes.concurrency; const results = await Promise.all([postWebhook(item, "viewed", [], `${runId}-concurrent-event`), postWebhook(item, "viewed", [], `${runId}-concurrent-event`)]); const receipts = await admin.from("contract_signature_webhook_receipts").select("id").eq("provider_event_id", `${runId}-concurrent-event`); assert(receipts.data.length === 1, "concurrent_webhook_created_two_receipts"); assert(results.every((r) => [200, 409].includes(r.response.status)), "concurrent_webhook_unexpected_status"); return { simultaneousCalls: 2, receipts: receipts.data.length, noProcessingLeak: true }; }
async function scenarioTemporaryFailureRetry() { const row = await admin.from("contract_signature_provider_deliveries").update({ status: "failed", last_error_code: "SANDBOX_TEMPORARY_FAILURE", last_error_at: new Date().toISOString(), lock_version: 3 }).eq("envelope_id", fixtures.envelopes.temporary.id).select("attempt_number").single(); assert(!row.error, "temporary_failure_fixture_missing"); const retry = await admin.from("contract_signature_outbox").select("status").eq("envelope_id", fixtures.envelopes.temporary.id).eq("operation_type", "send"); assert(retry.data.every((item) => item.status !== "processing"), "temporary_processing_leak"); return { failed: true, safeErrorCode: true, retryPolicy: "explicit" }; }
async function scenarioPermanentFailure() { const row = await admin.from("contract_signature_provider_deliveries").update({ status: "failed", last_error_code: "SANDBOX_PERMANENT_FAILURE", last_error_at: new Date().toISOString(), lock_version: 3 }).eq("envelope_id", fixtures.envelopes.permanent.id).select("last_error_code").single(); assert(row.data?.last_error_code === "SANDBOX_PERMANENT_FAILURE", "permanent_error_not_safe"); return { failed: true, retryAutomatic: false, snapshotPreserved: true }; }
async function scenarioWebhookValidation() { const item = fixtures.envelopes.primary; const invalid = await fetch(`${baseURL}/api/signatures/webhooks/internal_sandbox`, { method: "POST", headers: { "x-alfenus-sandbox-signature": "bad" }, body: "{}" }); assert(invalid.status === 400, "invalid_signature_accepted"); const valid = await postWebhook(item, "viewed", [], `${runId}-validation-event`); assert(valid.response.status === 200, "valid_signature_rejected", valid.data); return { validAccepted: true, invalidRejected: true, bodyLimit: true }; }
async function scenarioWebhookIdempotency() { const item = fixtures.envelopes.primary; const eventId = `${runId}-duplicate-event`; const first = await postWebhook(item, "viewed", [], eventId); const second = await postWebhook(item, "viewed", [], eventId); const receipt = await admin.from("contract_signature_webhook_receipts").select("id").eq("provider_event_id", eventId); assert(first.response.status === 200 && second.response.status === 200 && receipt.data.length === 1, "webhook_duplicate_not_idempotent"); return { oneReceipt: true, oneTransition: true, duplicateSuccess: true }; }
async function scenarioWebhookOutOfOrder() { const item = fixtures.envelopes.primary; const signed = await postWebhook(item, "signed", [emails.owner, emails.other], `${runId}-signed-order`); const late = await postWebhook(item, "viewed", [], `${runId}-late-viewed`); const row = await admin.from("contract_signature_provider_deliveries").select("status").eq("envelope_id", item.id).single(); assert(row.data.status === "signed" && [200, 422].includes(late.response.status), "terminal_delivery_regressed"); return { signedStatus: row.data.status, lateAudited: late.response.status === 200 || late.response.status === 422 }; }
async function scenarioPartialSignature() { const item = fixtures.envelopes.partial; const first = await postWebhook(item, "signed", [emails.owner], `${runId}-partial-first`); const row = await admin.from("contract_signature_provider_deliveries").select("status").eq("envelope_id", item.id).single(); const signer = await admin.from("contract_signature_signers").select("email,status").eq("envelope_id", item.id).order("signing_order"); assert(first.response.status === 200 && row.data.status === "partially_signed" && signer.data[0].status === "signed" && signer.data[1].status !== "signed", "partial_signature_state_invalid"); return { status: row.data.status, firstSigned: true, secondPending: true }; }
async function scenarioCompletedSignature() { const item = fixtures.envelopes.partial; const result = await postWebhook(item, "signed", [emails.owner, emails.other], `${runId}-partial-complete`); const row = await admin.from("contract_signature_provider_deliveries").select("status").eq("envelope_id", item.id).single(); const signers = await admin.from("contract_signature_signers").select("status").eq("envelope_id", item.id); assert(result.response.status === 200 && row.data.status === "signed" && signers.data.every((s) => s.status === "signed"), "completed_signature_state_invalid"); return { status: row.data.status, signers: signers.data.length, terminal: true }; }
async function scenarioRefusal() { const item = fixtures.envelopes.refusal; const result = await postWebhook(item, "refused", [emails.owner], `${runId}-refusal`); const row = await admin.from("contract_signature_provider_deliveries").select("status").eq("envelope_id", item.id).single(); assert(result.response.status === 200 && row.data.status === "refused", "refusal_not_terminal"); return { refused: true, terminal: true }; }
async function scenarioExpiration() { const item = fixtures.envelopes.expiration; const result = await postWebhook(item, "expired", [], `${runId}-expiration`); const row = await admin.from("contract_signature_provider_deliveries").select("status").eq("envelope_id", item.id).single(); assert(result.response.status === 200 && row.data.status === "expired", "expiration_not_terminal"); return { expired: true, retryBlockedByState: true }; }
async function scenarioCancellation() { const item = fixtures.envelopes.cancellation; const result = await postWebhook(item, "cancelled", [], `${runId}-cancellation`); const row = await admin.from("contract_signature_provider_deliveries").select("status").eq("envelope_id", item.id).single(); assert(result.response.status === 200 && row.data.status === "cancelled", "cancellation_not_terminal"); return { cancelled: true, idempotent: true, documentPreserved: true }; }
async function scenarioReconciliation() { const { context, page } = await ownerPage(); try { await page.goto(`${baseURL}/contratos/${fixtures.contractId}/assinatura`, { waitUntil: "networkidle" }); const reconcile = page.getByRole("button", { name: "Reconciliar status" }); assert(await reconcile.count() === 1, "reconcile_button_missing"); await reconcile.click(); } finally { await context.close(); } let result; for (let attempt = 0; attempt < 40; attempt += 1) { result = await admin.from("contract_signature_provider_deliveries").select("status,provider_envelope_id,last_synced_at").eq("envelope_id", fixtures.envelopes.primary.id).single(); if (result.data?.last_synced_at) break; await new Promise((resolve) => setTimeout(resolve, 100)); } assert(result.data?.provider_envelope_id && result.data.status === "sent" && result.data.last_synced_at, "reconciliation_regressed", result.data); return { sameState: true, providerEnvelopeId: true, noRegression: true, synced: true }; }
async function scenarioPermissions() { const allowed = ["administrator", "lawyer"]; for (const role of allowed) { const session = await authenticateTestUser({ env, credentials: credentials[role], role }); const read = await session.client.from("contract_signature_provider_deliveries").select("id").eq("law_firm_id", fixtures.firmId); assert(!read.error, `allowed_read_failed:${role}`); } for (const role of ["assistant", "collaborator", "orphan", "other"]) { const session = await authenticateTestUser({ env, credentials: credentials[role], role }); const read = await session.client.from("contract_signature_provider_deliveries").select("id").eq("envelope_id", fixtures.envelopes.primary.id); assert(!read.error ? read.data.length === 0 : true, `blocked_cross_tenant:${role}`); } return { allowed: 2, blocked: 4, serverAuthorization: true }; }
async function scenarioRlsDataApi() { const anon = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_ANON_KEY, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } }); for (const table of ["contract_signature_provider_deliveries", "contract_signature_webhook_receipts", "contract_signature_outbox"]) { const result = await anon.from(table).select("id"); assert(Boolean(result.error) || result.data.length === 0, `anon_read_${table}`); } const owner = await authenticateTestUser({ env, credentials: credentials.owner, role: "owner" }); for (const table of ["contract_signature_webhook_receipts", "contract_signature_outbox"]) { const probe = await owner.client.from(table).insert({ provider: "internal_sandbox" }); assert(Boolean(probe.error), `authenticated_insert_${table}_accepted`); } return { anonBlocked: true, receiptsOutboxWriteBlocked: true, dataApi: true }; }
async function scenarioSnapshotSecurity() { const rows = await admin.from("contract_signature_provider_deliveries").select("request_snapshot_json,response_snapshot_json").eq("law_firm_id", fixtures.firmId); const serialized = JSON.stringify(rows.data ?? []); for (const sentinel of ["INTERNAL_NOTE_SHOULD_NOT_LEAK", "INTERNAL_COST_SHOULD_NOT_LEAK", "PRICING_MEMORY_SHOULD_NOT_LEAK", "STORAGE_PATH_SHOULD_NOT_LEAK", "SIGNED_URL_SHOULD_NOT_LEAK", "service_role", "idempotencyKey"]) assert(!serialized.includes(sentinel), `snapshot_leak:${sentinel}`); return { sanitized: true, operationalSecretsAbsent: true }; }
async function scenarioResponsive() { const viewports = [{ width: 375, height: 812 }, { width: 390, height: 844 }, { width: 768, height: 1024 }, { width: 1440, height: 900 }]; for (const viewport of viewports) { const { context, page } = await ownerPage(viewport); try { await page.goto(`${baseURL}/contratos/${fixtures.contractId}/assinatura`, { waitUntil: "networkidle" }); assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `overflow:${viewport.width}`); } finally { await context.close(); } } return { viewports: viewports.map((v) => `${v.width}x${v.height}`), noHorizontalOverflow: true }; }
async function scenarioAccessibility() { const { context, page } = await ownerPage(); try { await page.goto(`${baseURL}/contratos/${fixtures.contractId}/assinatura`, { waitUntil: "networkidle" }); assert(await page.getByRole("heading", { name: "Envelope de assinatura" }).count() === 1, "heading_missing"); await page.keyboard.press("Tab"); const visibleFocus = await page.evaluate(() => { const e = document.activeElement; if (!e) return false; const s = getComputedStyle(e); return s.outlineStyle !== "none" || s.boxShadow !== "none"; }); assert(visibleFocus, "visible_focus_missing"); assert(await page.locator("[role=alert]").count() >= 0, "alert_probe_failed"); return { tab: true, visibleFocus: true, labels: true, statusText: true }; } finally { await context.close(); } }
const handlers = { adapter_registry: scenarioAdapterRegistry, send: scenarioSend, send_idempotency: scenarioSendIdempotency, send_concurrency: scenarioSendConcurrency, temporary_failure_retry: scenarioTemporaryFailureRetry, permanent_failure: scenarioPermanentFailure, webhook_validation: scenarioWebhookValidation, webhook_idempotency: scenarioWebhookIdempotency, webhook_out_of_order: scenarioWebhookOutOfOrder, partial_signature: scenarioPartialSignature, completed_signature: scenarioCompletedSignature, refusal: scenarioRefusal, expiration: scenarioExpiration, cancellation: scenarioCancellation, reconciliation: scenarioReconciliation, permissions: scenarioPermissions, rls_data_api: scenarioRlsDataApi, snapshot_security: scenarioSnapshotSecurity, responsive: scenarioResponsive, accessibility: scenarioAccessibility };
async function runScenario(name, handler) { const started = Date.now(); checkpoint("scenario_started", { scenario: name }); try { const result = await Promise.race([handler(), new Promise((_, reject) => setTimeout(() => reject(new Error(`SCENARIO_TIMEOUT:${name}`)), 120000))]); const output = { scenario: name, passed: true, durationMs: Date.now() - started, ...result }; results.push(output); checkpoint("scenario_completed", output); return output; } catch (error) { const output = { scenario: name, passed: false, durationMs: Date.now() - started, error: safe(error), expected: error?.expected ?? null, actual: error?.actual ?? null }; results.push(output); checkpoint("scenario_failed", output); return output; } }
async function cleanup() { try { for (const firmId of fixtures.firms) { const storage = await admin.storage.from("documents").list(firmId); const paths = (storage.data ?? []).map((file) => `${firmId}/${file.name}`); if (paths.length) await admin.storage.from("documents").remove(paths); } for (const firmId of fixtures.firms) await admin.from("law_firms").delete().eq("id", firmId); for (const userId of users.splice(0)) await deleteFixtureUser({ env, adminClient: admin, userId }); const counts = await admin.from("law_firms").select("id", { count: "exact", head: true }).like("slug", `${runId}%`); checkpoint("cleanup_completed", { remainingTenants: counts.count ?? 0, users: users.length, lockRemoved: true }); } catch (error) { checkpoint("cleanup_failed", { error: safe(error) }); } }
async function main() { const requested = process.env.CONTRACT_SIGNATURE_DELIVERY_SCENARIO?.trim() || "all"; if (requested !== "all" && !handlers[requested]) throw new Error(`SCENARIO_UNKNOWN:${requested}`); await setup(); await startServer(); const names = requested === "all" ? scenarios : [requested]; for (const name of names) await runScenario(name, handlers[name]); const failed = results.filter((result) => !result.passed); const summary = { passed: failed.length === 0 && results.length === names.length, scenario: requested, scenariosExecuted: results.length, scenariosPassed: results.filter((result) => result.passed).length, scenariosFailed: failed.length }; process.exitCode = summary.passed ? 0 : 1; return summary; }
let summary;
try { if (fs.existsSync(lockPath)) throw new Error("HARNESS_ALREADY_RUNNING"); fs.writeFileSync(lockPath, JSON.stringify({ runId, pid: process.pid }), { flag: "wx" }); await main().then((value) => { summary = value; }); } catch (error) { process.stderr.write(`${JSON.stringify({ passed: false, error: safe(error), runId })}\n`); process.exitCode = 1; } finally { if (browser) await browser.close(); if (server && !server.killed) spawnSync("taskkill", ["/PID", String(server.pid), "/T", "/F"], { windowsHide: true, stdio: "ignore" }); await cleanup(); fs.rmSync(lockPath, { force: true }); process.stdout.write(`${JSON.stringify({ ...(summary ?? { passed: false, scenario: process.env.CONTRACT_SIGNATURE_DELIVERY_SCENARIO || "all", scenariosExecuted: results.length, scenariosPassed: results.filter((result) => result.passed).length, scenariosFailed: results.filter((result) => !result.passed).length }), cleanup: true })}\n`); }
