import { createClient } from '@supabase/supabase-js';
import crypto from 'node:crypto';
import { assertAllowedProposalsTestEnvironment } from './proposals-test-environment.mjs';

const env = assertAllowedProposalsTestEnvironment();
const url = env.NEXT_PUBLIC_SUPABASE_URL;
const admin = createClient(url, env.SUPABASE_SERVICE_ROLE_KEY, { auth: { autoRefreshToken: false, persistSession: false } });
const anonKey = env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const prefix = `proposal-runtime-${Date.now()}`;
const password = `P!${crypto.randomBytes(20).toString('base64url')}9a`;
const users = [];
const tenants = [];
const proposals = [];
const pricingScenarios = [];
const assert = (actual, expected, message) => { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(`${message}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`); };
const assertTruthy = (value, message) => { if (!value) throw new Error(message); };
const hash = (value) => crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
const clientFor = (user) => createClient(url, anonKey, { auth: { autoRefreshToken: false, persistSession: false } });
async function createUser(role, tenantId, label) {
  const email = `${prefix}-${label}@example.invalid`;
  const { data, error } = await admin.auth.admin.createUser({ email, password, email_confirm: true, user_metadata: { name: label } });
  if (error) throw error;
  users.push(data.user.id);
  if (tenantId) { const result = await admin.from('law_firm_members').insert({ user_id: data.user.id, law_firm_id: tenantId, name: label, email, role, status: 'ativo' }); if (result.error) throw result.error; }
  const client = clientFor(data.user); const login = await client.auth.signInWithPassword({ email, password }); if (login.error) throw login.error;
  return { id: data.user.id, email, client, role, tenantId };
}
async function rpc(user, name, args) { const result = await user.client.rpc(name, args); return result; }
async function main() {
  const a = await admin.from('law_firms').insert({ name: `${prefix} A`, slug: `${prefix}-a` }).select('id').single(); if (a.error) throw a.error; tenants.push(a.data.id);
  const b = await admin.from('law_firms').insert({ name: `${prefix} B`, slug: `${prefix}-b` }).select('id').single(); if (b.error) throw b.error; tenants.push(b.data.id);
  const ownerA = await createUser('proprietario', tenants[0], 'owner-a'); const adminA = await createUser('administrador', tenants[0], 'admin-a'); const lawyerA = await createUser('advogado', tenants[0], 'lawyer-a'); const assistantA = await createUser('assistente', tenants[0], 'assistant-a'); const collaboratorA = await createUser('colaborador', tenants[0], 'collaborator-a'); const ownerB = await createUser('proprietario', tenants[1], 'owner-b'); const noMembership = await createUser(null, null, 'no-membership');
  const scenarioId = crypto.randomUUID(); const versionId = crypto.randomUUID(); pricingScenarios.push(scenarioId);
  let result = await admin.from('pricing_scenarios').insert({ id: scenarioId, law_firm_id: tenants[0], created_by: ownerA.id, name: `${prefix} pricing`, status: 'draft', active_version_id: versionId }); if (result.error) throw result.error;
  result = await admin.from('pricing_scenario_versions').insert({ id: versionId, law_firm_id: tenants[0], pricing_scenario_id: scenarioId, created_by: ownerA.id, version_number: 1, scenario_type: 'main', parameters: { custom_inputs: { marginBps: 2500, internalCost: 9000 }, private_note: 'do not copy' }, calculation_result: { total_fee_cents: 100000, marginAmount: 25000, internalCost: 9000 }, calculation_memory: { steps: [{ step: 'private', value: 'do not copy' }] }, currency: 'BRL', total_amount_cents: 100000, entry_amount_cents: 20000, financed_amount_cents: 80000, installment_count: 4, success_fee_percentage_bps: 1000, monthly_fee_cents: 5000, monthly_fee_count: 3 }); if (result.error) throw result.error;
  result = await admin.from('pricing_scenario_items').insert({ id: crypto.randomUUID(), law_firm_id: tenants[0], scenario_version_id: versionId, item_type: 'activity', description: 'Consulta jurídica', quantity: 1, unit_amount_cents: 100000, total_amount_cents: 100000, order_index: 0, metadata: { includedInClientPrice: true } }); if (result.error) throw result.error;
  const manualHash = hash({ title: `${prefix} manual`, currency: 'BRL', validityDays: 15 });
  const manual = await rpc(ownerA, 'create_commercial_proposal_manual', { p_title: `${prefix} manual`, p_currency: 'BRL', p_validity_days: 15, p_idempotency_key: `${prefix}-manual` });
  assertTruthy(!manual.error, `manual creation failed: ${manual.error?.message}`); assertTruthy(manual.data?.[0]?.proposal_id, 'manual proposal missing'); proposals.push(manual.data[0].proposal_id);
  const retry = await rpc(ownerA, 'create_commercial_proposal_manual', { p_title: `${prefix} manual`, p_currency: 'BRL', p_validity_days: 15, p_idempotency_key: `${prefix}-manual` }); assertTruthy(!retry.error, 'manual retry failed'); assert(retry.data[0].proposal_id, manual.data[0].proposal_id, 'manual retry did not return same proposal');
  for (const user of [adminA, lawyerA]) { const result = await rpc(user, 'create_commercial_proposal_manual', { p_title: `${prefix} ${user.role}`, p_currency: 'BRL', p_validity_days: 10, p_idempotency_key: `${prefix}-${user.role}` }); assertTruthy(!result.error, `${user.role} manual creation blocked unexpectedly`); proposals.push(result.data[0].proposal_id); }
  for (const user of [assistantA, collaboratorA, noMembership]) { const result = await rpc(user, 'create_commercial_proposal_manual', { p_title: `${prefix} denied`, p_currency: 'BRL', p_validity_days: 10, p_idempotency_key: `${prefix}-denied-${user.role ?? 'none'}` }); assertTruthy(Boolean(result.error), `${user.role ?? 'none'} mutation was not blocked`); }
  const detail = await rpc(ownerA, 'get_commercial_proposal_secure', { p_proposal_id: manual.data[0].proposal_id }); assertTruthy(!detail.error && detail.data?.[0]?.id === manual.data[0].proposal_id, 'secure detail failed'); assertTruthy(!('internal_notes' in (detail.data?.[0] ?? {})), 'internal notes leaked by secure detail');
  const directProposal = await ownerA.client.from('commercial_proposals').select('internal_notes').eq('id', manual.data[0].proposal_id); assertTruthy(Boolean(directProposal.error), 'direct proposal sensitive SELECT was allowed'); const directVersion = await ownerA.client.from('commercial_proposal_versions').select('pricing_snapshot_json,payment_terms_json').eq('id', manual.data[0].version_id); assertTruthy(Boolean(directVersion.error), 'direct version sensitive SELECT was allowed');
  const cross = await rpc(ownerB, 'get_commercial_proposal_secure', { p_proposal_id: manual.data[0].proposal_id }); assert(!cross.data?.length, true, 'cross-tenant detail leaked');
  const updateA = await rpc(ownerA, 'update_commercial_proposal_metadata', { p_proposal_id: manual.data[0].proposal_id, p_expected_updated_at: detail.data[0].updated_at, p_title: `${prefix} updated`, p_internal_reference: 'R-1' }); assertTruthy(!updateA.error, `update A failed: ${updateA.error?.message}`);
  const updateB = await rpc(ownerA, 'update_commercial_proposal_metadata', { p_proposal_id: manual.data[0].proposal_id, p_expected_updated_at: detail.data[0].updated_at, p_title: `${prefix} overwrite` }); assertTruthy(Boolean(updateB.error) && updateB.error.message.includes('PROPOSAL_OPTIMISTIC_LOCK_CONFLICT'), 'optimistic lock did not reject stale update');
  result = await admin.from('commercial_proposal_recipients').insert({ law_firm_id: tenants[0], proposal_id: manual.data[0].proposal_id, recipient_type: 'client', name: 'Destinatário Runtime', email: `${prefix}@example.invalid`, phone: '+5511999999999', is_primary: true }); if (result.error) throw result.error;
  const duplicate = await rpc(ownerA, 'duplicate_commercial_proposal', { p_source_proposal_id: manual.data[0].proposal_id, p_title: `${prefix} copy`, p_copy_recipients: false, p_idempotency_key: `${prefix}-duplicate`, p_input_hash: hash({ source: manual.data[0].proposal_id }) }); assertTruthy(!duplicate.error, `duplicate failed: ${duplicate.error?.message}`); proposals.push(duplicate.data[0].proposal_id); assertTruthy(duplicate.data[0].proposal_id !== manual.data[0].proposal_id, 'duplicate reused proposal id');
  const copiedRecipients = await rpc(ownerA, 'duplicate_commercial_proposal', { p_source_proposal_id: manual.data[0].proposal_id, p_title: `${prefix} copy recipients`, p_copy_recipients: true, p_idempotency_key: `${prefix}-duplicate-recipients`, p_input_hash: hash({ source: manual.data[0].proposal_id, recipients: true }) }); assertTruthy(!copiedRecipients.error, `recipient duplicate failed: ${copiedRecipients.error?.message}`); proposals.push(copiedRecipients.data[0].proposal_id); const copiedRecipientRows = await admin.from('commercial_proposal_recipients').select('id').eq('proposal_id', copiedRecipients.data[0].proposal_id); assert(copiedRecipientRows.data?.length, 1, 'recipient copy was not preserved');
  const duplicateRetry = await rpc(ownerA, 'duplicate_commercial_proposal', { p_source_proposal_id: manual.data[0].proposal_id, p_title: `${prefix} copy`, p_copy_recipients: false, p_idempotency_key: `${prefix}-duplicate`, p_input_hash: hash({ source: manual.data[0].proposal_id }) }); assert(duplicateRetry.data[0].proposal_id, duplicate.data[0].proposal_id, 'duplicate retry mismatch');
  const concurrentKey = `${prefix}-concurrent`; const concurrentHash = hash({ source: manual.data[0].proposal_id, concurrent: true }); const concurrent = await Promise.all([1, 2].map(() => rpc(ownerA, 'duplicate_commercial_proposal', { p_source_proposal_id: manual.data[0].proposal_id, p_title: `${prefix} concurrent`, p_copy_recipients: false, p_idempotency_key: concurrentKey, p_input_hash: concurrentHash }))); if (concurrent.some((item) => item.error)) throw new Error(`concurrent duplicate failed: ${concurrent.find((item) => item.error)?.error.message}`); assert(concurrent[0].data[0].proposal_id, concurrent[1].data[0].proposal_id, 'concurrent duplicate created multiple proposals'); proposals.push(concurrent[0].data[0].proposal_id);
  const deniedDuplicate = await rpc(assistantA, 'duplicate_commercial_proposal', { p_source_proposal_id: manual.data[0].proposal_id, p_title: 'denied', p_copy_recipients: false, p_idempotency_key: `${prefix}-denied-duplicate`, p_input_hash: hash({ denied: true }) }); assertTruthy(Boolean(deniedDuplicate.error), 'assistant duplicate was not blocked'); const crossDuplicate = await rpc(ownerB, 'duplicate_commercial_proposal', { p_source_proposal_id: manual.data[0].proposal_id, p_title: 'cross', p_copy_recipients: false, p_idempotency_key: `${prefix}-cross-duplicate`, p_input_hash: hash({ cross: true }) }); assertTruthy(Boolean(crossDuplicate.error), 'cross-tenant duplicate was not blocked');
  const manualVersionId = manual.data[0].version_id; const immutableUpdate = await ownerA.client.from('commercial_proposal_versions').update({ title: 'tampered' }).eq('id', manualVersionId); assert(Boolean(immutableUpdate.error) || immutableUpdate.data?.length === 0, true, 'immutable version update was not blocked'); const immutableDelete = await ownerA.client.from('commercial_proposal_versions').delete().eq('id', manualVersionId); assert(Boolean(immutableDelete.error) || immutableDelete.data?.length === 0, true, 'immutable version delete was not blocked');
  for (const table of ['commercial_proposal_sections', 'commercial_proposal_items', 'commercial_proposal_events']) { const attempt = await ownerA.client.from(table).update({ title: 'tampered' }).eq(table === 'commercial_proposal_events' ? 'proposal_id' : 'proposal_version_id', manual.data[0].proposal_id); assert(Boolean(attempt.error) || attempt.data?.length === 0, true, `${table} update was not blocked`); }
  const pricingHash = hash({ scenarioId, versionId }); const pricing = await rpc(ownerA, 'create_commercial_proposal_from_pricing_version', { p_pricing_scenario_id: scenarioId, p_pricing_version_id: versionId, p_title: `${prefix} from pricing`, p_validity_days: 30, p_idempotency_key: `${prefix}-pricing`, p_input_hash: pricingHash }); assertTruthy(!pricing.error, `pricing creation failed: ${pricing.error?.message}`); proposals.push(pricing.data[0].proposal_id);
  const snapshot = await admin.from('commercial_proposal_versions').select('pricing_snapshot_json,commercial_summary_json').eq('id', pricing.data[0].version_id).single(); if (snapshot.error) throw snapshot.error; const serialized = JSON.stringify(snapshot.data); for (const required of ['pricingScenarioId','pricingVersionId','pricingVersionNumber','scenarioType','currency','snapshotAt']) assertTruthy(serialized.includes(required), `snapshot field missing: ${required}`); for (const forbidden of ['marginBps','marginAmount','internalCost','hourlyCost','private_note','calculation_memory','auth_token']) assert(!serialized.includes(forbidden), true, `forbidden snapshot field leaked: ${forbidden}`);
  console.log(JSON.stringify({ passed: true, project: env.ref.slice(0, 8), users: users.length, tenants: tenants.length, proposals: proposals.length }));
}
try { await main(); } catch (error) { console.error(JSON.stringify({ passed: false, message: error.message })); process.exitCode = 1; } finally {
  for (const id of proposals) await admin.from('commercial_proposals').delete().eq('id', id);
  for (const id of pricingScenarios) await admin.from('pricing_scenarios').delete().eq('id', id);
  for (const id of tenants) await admin.from('law_firms').delete().eq('id', id);
  for (const id of users) await admin.auth.admin.deleteUser(id);
}
