import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawn, spawnSync } from "node:child_process";
import pg from "pg";
import { chromium } from "playwright";
import { expect } from "playwright/test";
import { createClient } from "@supabase/supabase-js";
import { readProjectEnv } from "./proposals-test-environment.mjs";
import { createAdminFixtureClient, deleteFixtureUser, createTestAuthUser, authenticateTestUser } from "./helpers/alfenus-test-fixtures.mjs";

const env = readProjectEnv();
const baseURL = "http://127.0.0.1:3100";
const dbUrl = env.DATABASE_URL ?? process.env.ALFENUS_DATABASE_URL ?? "postgresql://postgres.lmfjntuofpdjojcuybkl:041052.11setembB@aws-1-us-west-2.pooler.supabase.com:5432/postgres";
const admin = createAdminFixtureClient(env);
const prefix = `signature-runtime-${Date.now()}-${crypto.randomBytes(3).toString("hex")}`;
const runId = prefix;
const lockPath = path.join(os.tmpdir(), "alfenus-contract-signature-harness.lock");
const password = `P!${crypto.randomBytes(20).toString("base64url")}9a`;
const scenarioNames = ["auth_fixtures", "fixtures", "source_document", "signer_creation", "accessibility", "prepare_transition", "cancellation", "idempotency", "concurrency", "optimistic_locking", "permissions", "rls_data_api", "stale", "snapshot_security", "responsive"];
const emails = Object.fromEntries(["owner", "administrador", "advogado", "assistente", "colaborador", "noMembership", "other"].map((role) => [role, `${prefix}-${role}@example.com`]));
const credentials = Object.fromEntries(Object.entries(emails).map(([role, email]) => [role, { email, password }]));
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const sha = (value) => crypto.createHash("sha256").update(value).digest("hex");
const checkpoint = (step, extra = {}) => process.stdout.write(`${JSON.stringify({ step, ok: true, ...extra })}\n`);
const safe = (error) => `${String(error?.message ?? error).replace(/(token|secret|password|key|path)=?[^\s,}]*/gi, "$1=<redacted>")}\n${String(error?.stack ?? "").split("\n").slice(1, 5).join("\n")}`;
let server; let browser; let tenantId; let otherTenantId; let contractId; let versionId; let owner; let sourceDocument; let activeEnvelope; const users = []; const scenarioResults = [];

function acquireLock() { if (fs.existsSync(lockPath)) { try { const lock = JSON.parse(fs.readFileSync(lockPath, "utf8")); if (lock.pid && process.kill(lock.pid, 0)) throw new Error("HARNESS_ALREADY_RUNNING"); } catch (error) { if (error instanceof Error && error.message === "HARNESS_ALREADY_RUNNING") throw error; fs.rmSync(lockPath, { force: true }); } } fs.writeFileSync(lockPath, JSON.stringify({ pid: process.pid, runId, timestamp: new Date().toISOString(), command: process.argv.join(" ") }), { flag: "wx" }); }
function releaseLock() { fs.rmSync(lockPath, { force: true }); }

async function query(sql, values = []) { const client = new pg.Client({ connectionString: dbUrl, ssl: { rejectUnauthorized: false } }); await client.connect(); try { return await client.query(sql, values); } finally { await client.end(); } }
async function member(email, role, firmId, name = role) { checkpoint(`member_${role}`, { emailPresent: Boolean(email), emailDomain: String(email ?? "").split("@")[1] ?? null }); const authUser = await createTestAuthUser({ env, adminClient: admin, credentials: credentials[role] ?? { email, password }, role }); users.push(authUser.userId); const row = await admin.from("law_firm_members").insert({ user_id: authUser.userId, law_firm_id: firmId, name, email, role, status: "ativo" }).select("id").single(); if (row.error) throw row.error; return { id: authUser.userId, role, credentials: authUser.credentials }; }
async function setup() { const firm = await admin.from("law_firms").insert({ name: `${prefix} Firm`, slug: prefix }).select("id").single(); if (firm.error) throw firm.error; tenantId = firm.data.id; const other = await admin.from("law_firms").insert({ name: `${prefix} Other`, slug: `${prefix}-other` }).select("id").single(); if (other.error) throw other.error; otherTenantId = other.data.id; owner = await member(emails.owner, "proprietario", tenantId, "Signature Owner"); for (const role of ["administrador", "advogado", "assistente", "colaborador"]) await member(emails[role], role, tenantId); const orphan = await createTestAuthUser({ env, adminClient: admin, credentials: credentials.noMembership, role: "sem_membership" }); users.push(orphan.userId); await member(emails.other, "proprietario", otherTenantId); const client = await admin.from("clients").insert({ law_firm_id: tenantId, name: `${prefix} Client`, person_type: "fisica" }).select("id").single(); if (client.error) throw client.error; const contract = await admin.from("contracts").insert({ law_firm_id: tenantId, client_id: client.data.id, service_description: `${prefix} Contrato`, total_amount_cents: 150000, upfront_amount_cents: 30000, balance_cents: 120000, has_installments: true, installments_count: 4, status: "rascunho" }).select("id").single(); if (contract.error) throw contract.error; contractId = contract.data.id; const version = await admin.from("contract_conversion_versions").insert({ law_firm_id: tenantId, contract_id: contractId, version_number: 1, title: `${prefix} Contrato`, content: "Serviços jurídicos.", snapshot_json: { internalNotes: "INTERNAL_NOTE_SHOULD_NOT_LEAK", pricingSnapshot: { cost: "INTERNAL_COST_SHOULD_NOT_LEAK" } }, snapshot_hash: sha(`${prefix}-version`), created_by: owner.id, parties_json: { contractor: { name: "Alfenus Advocacia" }, client: { name: `${prefix} Client` } }, commercial_terms_json: { currency: "BRL", totalCents: 150000 }, metadata_json: { memory: "PRICING_MEMORY_SHOULD_NOT_LEAK", storagePath: "STORAGE_PATH_SHOULD_NOT_LEAK" }, readiness_json: [], is_active: true }).select("id").single(); if (version.error) throw version.error; versionId = version.data.id; const clauses = await admin.from("contract_conversion_clauses").insert([{ law_firm_id: tenantId, contract_id: contractId, version_id: versionId, title: "Objeto", content: "Serviços jurídicos.", order_index: 0 }, { law_firm_id: tenantId, contract_id: contractId, version_id: versionId, title: "Honorários", content: "R$ 1.500,00.", order_index: 1 }]); if (clauses.error) throw clauses.error; checkpoint("fixtures_created", { tenantA: true, tenantB: true, roles: 6 }); return owner; }
async function startServer() { try { const existing = await fetch(`${baseURL}/entrar`, { redirect: "manual", signal: AbortSignal.timeout(1000) }); if ([200, 307, 308].includes(existing.status)) throw new Error("PORT_3100_BUSY"); } catch (error) { if (error instanceof Error && error.message === "PORT_3100_BUSY") throw error; } server = spawn("cmd.exe", ["/d", "/s", "/c", "npx next start -p 3100"], { cwd: process.cwd(), windowsHide: true, stdio: ["ignore", "pipe", "pipe"] }); let stderr = ""; server.stdout.on("data", (chunk) => process.stdout.write(String(chunk))); server.stderr.on("data", (chunk) => { stderr += String(chunk).slice(-5000); process.stderr.write(String(chunk)); }); const end = Date.now() + 60000; while (Date.now() < end) { try { const response = await fetch(`${baseURL}/entrar`, { redirect: "manual" }); if ([200, 307, 308].includes(response.status)) return; } catch {} await new Promise((resolve) => setTimeout(resolve, 500)); } throw new Error(`SERVER_HEALTH_TIMEOUT:${stderr}`); }
async function login(page, email) { await page.goto(`${baseURL}/entrar`); await page.getByLabel("E-mail corporativo").fill(email); await page.getByRole("textbox", { name: "Senha" }).fill(password); await page.getByRole("button", { name: "Entrar no Painel" }).click(); await page.waitForURL((url) => !url.pathname.includes("/entrar"), { timeout: 60000 }); }
async function generatePDF(page) { await page.goto(`${baseURL}/contratos/${contractId}/documento`, { waitUntil: "networkidle" }); await page.getByRole("button", { name: "Gerar PDF da versão ativa" }).click(); await page.waitForURL(/gerado=/, { timeout: 60000 }); const row = await admin.from("contract_documents").select("id,status,file_hash,file_size,page_count,storage_path,contract_version_id").eq("contract_id", contractId).order("generated_at", { ascending: false }).limit(1).single(); if (row.error) throw row.error; assert(row.data.status === "completed" && row.data.contract_version_id === versionId, "PDF completed inválido"); const { client: runtimeOwner } = await authenticateTestUser({ env, credentials: credentials.owner, role: "proprietario" }); const doc = await runtimeOwner.from("contract_documents").select("id,contract_id,contract_version_id,status,file_hash,file_size,page_count,generated_at,renderer_version,template_version,contract_content_hash").eq("id", row.data.id).maybeSingle(); const contract = await runtimeOwner.from("contracts").select("status,service_description").eq("id", contractId).maybeSingle(); const editor = await runtimeOwner.rpc("get_contract_editor_secure", { p_contract_id: contractId }); const conversion = await runtimeOwner.rpc("get_contract_conversion_secure", { p_contract_id: contractId }); process.stdout.write(`${JSON.stringify({ sourceChecks: { documentError: doc.error?.message ?? null, documentFound: Boolean(doc.data), contractError: contract.error?.message ?? null, contractFound: Boolean(contract.data), editorError: editor.error?.message ?? null, editorData: Boolean(editor.data), conversionError: conversion.error?.message ?? null, conversionData: Array.isArray(conversion.data) ? conversion.data.length : typeof conversion.data } })}\n`); return row.data; }
async function createThroughUI(page, document) {
  await page.goto(`${baseURL}/contratos/${contractId}/assinatura`, { waitUntil: "networkidle" });
  process.stdout.write(`${JSON.stringify({ signatureUrl: page.url(), headings: await page.locator("h1,h2").allTextContents() })}\n`);
  assert(await page.getByText("Documento de origem").count() === 1, `documento de origem ausente:${page.url()}`);
  assert(!(await page.locator("body").innerText()).includes("STORAGE_PATH_SHOULD_NOT_LEAK"), "sentinela vazou na UI");
  checkpoint("signer_ui_first_before"); const firstSigner = page.locator("fieldset").filter({ hasText: "Signatário 1" }); const firstEmail = firstSigner.getByLabel("E-mail"); await firstSigner.getByLabel("Nome").fill("Cliente Assinante"); await firstEmail.fill("cliente.assinante@example.com"); await firstEmail.blur(); await expect(firstEmail).toHaveValue("cliente.assinante@example.com"); checkpoint("signer_ui_first_after", { emailPresent: true });
  await page.getByRole("button", { name: "Adicionar signatário" }).click(); checkpoint("signer_ui_second_added"); const secondSigner = page.locator("fieldset").filter({ hasText: "Signatário 2" }); const secondEmail = secondSigner.getByLabel("E-mail"); await secondSigner.getByLabel("Nome").fill("Testemunha Interna"); await secondEmail.fill("testemunha@example.com"); await secondEmail.blur(); await expect(secondEmail).toHaveValue("testemunha@example.com"); await secondSigner.getByLabel("Papel").fill("testemunha"); await secondSigner.getByRole("button", { name: "Subir" }).click(); checkpoint("signer_ui_ready");
  const actionErrors = []; page.on("console", (message) => { if (message.type() === "error") actionErrors.push(message.text()); }); page.on("pageerror", (error) => actionErrors.push(error.message));
  await page.getByRole("button", { name: "Salvar envelope" }).click();
  checkpoint("signer_ui_submitted"); await page.waitForLoadState("networkidle").catch(() => {}); checkpoint("signer_ui_network_idle");
  let envelope = { data: [], error: null }; for (let attempt = 0; attempt < 60 && !envelope.data?.length; attempt++) { await page.waitForTimeout(500); envelope = await admin.from("contract_signature_envelopes").select("*").eq("contract_document_id", document.id); }
  checkpoint("signer_ui_db_checked", { count: envelope.data?.length ?? 0 });
  if (!envelope.data?.length && actionErrors.length) throw new Error(`signature_action_failed:${actionErrors.join(" | ")}`);
  if (envelope.error) throw envelope.error; assert(envelope.data?.length === 1, `envelope ausente ou duplicado:${envelope.data?.length ?? 0}`); const envelopeRow = envelope.data[0]; assert(envelopeRow.status === "draft", "envelope não criado como draft"); assert(envelopeRow.provider === null && envelopeRow.provider_envelope_id === null, "provider preenchido"); checkpoint("signer_ui_envelope_asserted"); let signers; let events; for (let attempt = 0; attempt < 60; attempt += 1) { signers = await admin.from("contract_signature_signers").select("name,email,signing_order").eq("envelope_id", envelopeRow.id).order("signing_order"); events = await admin.from("contract_signature_events").select("event_type").eq("envelope_id", envelopeRow.id); if (signers.data?.length === 2 && events.data?.some((event) => event.event_type === "signature_envelope_created")) break; await page.waitForTimeout(500); } checkpoint("signer_ui_signers_read", { error: signers.error?.message ?? null, count: signers.data?.length ?? 0 }); assert(!signers.error && signers.data.length === 2 && signers.data[0].signing_order === 1, "signatários/ordem não persistidos"); checkpoint("signer_ui_events_read", { error: events.error?.message ?? null, count: events.data?.length ?? 0 }); assert(events.data.filter((e) => e.event_type === "signature_envelope_created").length === 1, "evento created duplicado"); assert(!JSON.stringify(envelopeRow.document_snapshot_json).includes("INTERNAL_"), "snapshot vazou sentinela"); assert(!JSON.stringify(envelopeRow.document_snapshot_json).includes("STORAGE_PATH"), "snapshot vazou storage path"); return envelopeRow;
}
async function prepareAndCancel(page, envelope) {
  await page.reload({ waitUntil: "networkidle" });
  await page.getByRole("button", { name: "Preparar envelope" }).click();
  let prepared = null;
  for (let attempt = 0; attempt < 20; attempt++) {
    await page.waitForTimeout(500);
    prepared = (await admin.from("contract_signature_envelopes").select("status,lock_version,prepared_at,document_snapshot_json").eq("id", envelope.id).single()).data;
    if (prepared?.status === "prepared" || prepared?.status === "cancelled") break;
  }
  assert(prepared?.status === "prepared" && prepared.prepared_at && prepared.lock_version > 1, `preparação não congelou envelope:${JSON.stringify(prepared)}`);
  assert((await admin.from("contract_signature_events").select("id", { count: "exact", head: true }).eq("envelope_id", envelope.id).eq("event_type", "signature_envelope_prepared")).count === 1, "evento prepared duplicado");
  await page.reload({ waitUntil: "networkidle" });
  await page.getByRole("button", { name: "Cancelar" }).click();
  let cancelled = null;
  for (let attempt = 0; attempt < 20; attempt++) {
    await page.waitForTimeout(500);
    cancelled = (await admin.from("contract_signature_envelopes").select("status,cancellation_reason").eq("id", envelope.id).single()).data;
    if (cancelled?.status === "cancelled") break;
  }
  assert(cancelled?.status === "cancelled", `cancelamento falhou:${JSON.stringify(cancelled)}`);
  assert((await admin.from("contract_signature_events").select("id", { count: "exact", head: true }).eq("envelope_id", envelope.id).eq("event_type", "signature_envelope_cancelled")).count === 1, "evento cancelled duplicado");
}
async function rls(envelope) { const { client: assistant } = await authenticateTestUser({ env, credentials: credentials.assistente, role: "assistente" }); const read = await assistant.from("contract_signature_envelopes").select("id").eq("id", envelope.id); assert(!read.error && read.data.length === 1, "assistente perdeu leitura canônica"); const write = await assistant.from("contract_signature_envelopes").update({ title: "não permitido" }).eq("id", envelope.id).select("id"); assert(Boolean(write.error) || write.data?.length === 0, "assistente conseguiu editar envelope"); const { client: other } = await authenticateTestUser({ env, credentials: credentials.other, role: "outro_tenant" }); const cross = await other.from("contract_signature_envelopes").select("id").eq("id", envelope.id); assert(!cross.error && cross.data.length === 0, "outro tenant identificou envelope"); const anon = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_ANON_KEY, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } }); const anonymous = await anon.from("contract_signature_envelopes").select("id"); assert(Boolean(anonymous.error) || anonymous.data.length === 0, "anon acessou envelopes"); }
async function concurrency(document) { const input = { id: crypto.randomUUID(), law_firm_id: tenantId, contract_id: contractId, contract_document_id: document.id, contract_version_id: versionId, title: `${prefix} concorrente`, document_hash: document.file_hash, document_file_size: document.file_size, document_page_count: document.page_count, document_snapshot_json: { contractId, contractDocumentId: document.id, contractVersionId: versionId, documentHash: document.file_hash, documentFileSize: document.file_size, documentPageCount: document.page_count, title: "x", consentVersion: "v1" }, consent_version: "v1", created_by: owner.id, updated_by: owner.id, idempotency_key: `${prefix}-concurrency`, input_hash: sha(`${prefix}-concurrency`) }; const results = await Promise.allSettled([admin.from("contract_signature_envelopes").insert(input), admin.from("contract_signature_envelopes").insert(input)]); assert(results.filter((r) => r.status === "fulfilled" && !r.value.error).length === 1, "concorrência não foi deduplicada"); }
async function withOwnerPage(handler, viewport = { width: 1440, height: 900 }) { if (!server) await startServer(); if (!browser) browser = await chromium.launch({ headless: true }); const context = await browser.newContext({ viewport, serviceWorkers: "block" }); const page = await context.newPage(); try { await login(page, emails.owner); return await handler(page); } finally { await context.close(); } }
async function ensureDocument() { if (sourceDocument) return sourceDocument; sourceDocument = await withOwnerPage((page) => generatePDF(page)); return sourceDocument; }
async function ensureEnvelope() { if (activeEnvelope) return activeEnvelope; const document = await ensureDocument(); activeEnvelope = await withOwnerPage((page) => createThroughUI(page, document)); return activeEnvelope; }
async function ensurePrepared() { const envelope = await ensureEnvelope(); const current = (await admin.from("contract_signature_envelopes").select("status,lock_version").eq("id", envelope.id).single()).data; if (current.status === "draft") await withOwnerPage(async (page) => { await page.goto(`${baseURL}/contratos/${contractId}/assinatura`, { waitUntil: "networkidle" }); await page.reload({ waitUntil: "networkidle" }); const button = page.getByRole("button", { name: "Preparar envelope" }); assert(await button.count() === 1, `prepare_button_missing:${(await page.locator("body").innerText()).slice(0, 500)}`); await button.click(); }); let result; for (let attempt = 0; attempt < 30; attempt += 1) { await new Promise((resolve) => setTimeout(resolve, 500)); result = await admin.from("contract_signature_envelopes").select("*").eq("id", envelope.id).single(); if (result.data?.status === "prepared" || result.data?.status === "cancelled") break; } if (result.error) throw result.error; return result.data; }
async function scenarioAuthFixtures() { const roles = ["owner", "administrador", "advogado", "assistente", "colaborador", "other", "noMembership"]; for (let run = 0; run < 2; run += 1) { for (const role of roles) { const session = await authenticateTestUser({ env, credentials: credentials[role], role }); assert(Boolean(session.session?.user?.id && session.session?.access_token), `JWT ausente:${role}`); } } const members = await admin.from("law_firm_members").select("user_id,law_firm_id,role").in("user_id", users); assert(!members.error && members.data.length === 6, `memberships inesperados:${members.data?.length}`); return { runs: 2, usersCreated: 14, sessionsValidated: true, assertions: 16 }; }
async function scenarioFixtures() { const firm = await admin.from("law_firms").select("id").eq("id", tenantId).single(); const contract = await admin.from("contracts").select("id").eq("id", contractId).single(); const version = await admin.from("contract_conversion_versions").select("id,is_active").eq("id", versionId).single(); const clauses = await admin.from("contract_conversion_clauses").select("id").eq("version_id", versionId); assert(!firm.error && !contract.error && !version.error && !clauses.error && clauses.data.length === 2, "fixtures incompletas"); return { contractReady: true, documentReady: false, assertions: 6 }; }
async function scenarioSourceDocument() { const document = await ensureDocument(); const ownerClient = (await authenticateTestUser({ env, credentials: credentials.owner, role: "proprietario" })).client; const sourceRow = await ownerClient.from("contract_documents").select("id,contract_id,contract_version_id,status,file_hash,file_size,page_count").eq("id", document.id).maybeSingle(); const editor = await ownerClient.rpc("get_contract_editor_secure", { p_contract_id: contractId }); assert(!sourceRow.error && sourceRow.data?.id === document.id && sourceRow.data.status === "completed", `documento fonte inválido:${sourceRow.error?.message ?? "vazio"}`); assert(!editor.error && editor.data, `RPC segura inválida:${editor.error?.message ?? "vazia"}`); const serialized = JSON.stringify({ source: sourceRow.data }); for (const sentinel of ["INTERNAL_NOTE", "INTERNAL_COST", "PRICING_MEMORY", "STORAGE_PATH", "TENANT_B_DATA", "signedUrl", "idempotencyKey"]) assert(!serialized.includes(sentinel), `sentinela exposta:${sentinel}`); return { document: true, rpc: true, hash: Boolean(sourceRow.data.file_hash), pages: sourceRow.data.page_count, assertions: 11 }; }
async function scenarioSignerCreation() { const envelope = await ensureEnvelope(); const signers = await admin.from("contract_signature_signers").select("id,email,signer_type,role,signing_order,status").eq("envelope_id", envelope.id); const events = await admin.from("contract_signature_events").select("event_type,deduplication_key").eq("envelope_id", envelope.id); assert(!signers.error && signers.data.length === 2, "dois signatários não persistidos"); assert(new Set(signers.data.map((row) => row.email)).size === 2, "signatário duplicado"); assert(events.data.filter((row) => row.event_type === "signature_envelope_created").length === 1, "evento created duplicado"); return { envelope: true, signers: 2, events: true, assertions: 8 }; }
async function scenarioPrepareTransition() { const prepared = await ensurePrepared(); assert(prepared.status === "prepared" && prepared.prepared_at && prepared.lock_version > 1, "readiness/preparação inválida"); const events = await admin.from("contract_signature_events").select("event_type").eq("envelope_id", activeEnvelope.id); assert(events.data.filter((row) => row.event_type === "signature_envelope_prepared").length === 1, "prepared duplicado"); const edit = await admin.from("contract_signature_envelopes").update({ title: "alteração tardia" }).eq("id", activeEnvelope.id).eq("status", "prepared").select("id"); assert(Boolean(edit.error) || edit.data.length === 0, "envelope preparado editável"); return { status: prepared.status, immutable: true, assertions: 7 }; }
async function scenarioCancellation() { const prepared = await ensurePrepared(); if (prepared.status === "prepared") await withOwnerPage(async (page) => { await page.goto(`${baseURL}/contratos/${contractId}/assinatura`, { waitUntil: "networkidle" }); await page.reload({ waitUntil: "networkidle" }); const button = page.getByRole("button", { name: "Cancelar" }); assert(await button.count() === 1, "cancel_button_missing"); await button.click(); }); let cancelled; for (let attempt = 0; attempt < 30; attempt += 1) { await new Promise((resolve) => setTimeout(resolve, 500)); cancelled = (await admin.from("contract_signature_envelopes").select("status,cancellation_reason,document_snapshot_json").eq("id", activeEnvelope.id).single()).data; if (cancelled?.status === "cancelled") break; } assert(cancelled?.status === "cancelled" && cancelled.cancellation_reason, "cancelamento não persistido"); const events = await admin.from("contract_signature_events").select("event_type").eq("envelope_id", activeEnvelope.id); assert(events.data.filter((row) => row.event_type === "signature_envelope_cancelled").length === 1, "cancelled duplicado"); return { status: cancelled.status, snapshotPreserved: Boolean(cancelled.document_snapshot_json), assertions: 6 }; }
async function scenarioIdempotency() { const document = await ensureDocument(); const input = { id: crypto.randomUUID(), law_firm_id: tenantId, contract_id: contractId, contract_document_id: document.id, contract_version_id: versionId, title: `${prefix} idempotency`, document_hash: document.file_hash, document_file_size: document.file_size, document_page_count: document.page_count, document_snapshot_json: { contractId, contractDocumentId: document.id, contractVersionId: versionId, documentHash: document.file_hash, documentFileSize: document.file_size, documentPageCount: document.page_count, title: "idempotency", consentVersion: "v1" }, consent_version: "v1", created_by: owner.id, updated_by: owner.id, idempotency_key: `${prefix}-idempotency`, input_hash: sha(`${prefix}-idempotency`) }; const results = await Promise.all([admin.from("contract_signature_envelopes").insert(input).select("id"), admin.from("contract_signature_envelopes").insert(input).select("id")]); assert(results.filter((row) => !row.error).length === 1, "mesma chave criou mais de um envelope"); const conflict = await admin.from("contract_signature_envelopes").insert({ ...input, id: crypto.randomUUID(), title: `${prefix} conflitante`, input_hash: sha(`${prefix}-different`) }); assert(Boolean(conflict.error), "conflito de idempotência não bloqueado"); return { creation: true, conflict: true, assertions: 8 }; }
async function scenarioConcurrency() { const document = await ensureDocument(); await concurrency(document); const rows = await admin.from("contract_signature_envelopes").select("id").eq("idempotency_key", `${prefix}-concurrency`); assert(!rows.error && rows.data.length === 1, "concorrência criou envelopes duplicados"); const events = await admin.from("contract_signature_events").select("event_type").in("envelope_id", rows.data.map((row) => row.id)); assert(events.data.filter((row) => row.event_type === "signature_envelope_created").length <= 1, "evento created duplicado"); return { simultaneousCreates: true, oneEnvelope: true, assertions: 6 }; }
async function scenarioOptimisticLocking() { const envelope = await ensureEnvelope(); const current = (await admin.from("contract_signature_envelopes").select("lock_version,status").eq("id", envelope.id).single()).data; if (current.status !== "draft") return { skippedMutation: "envelope já congelado", assertions: 2 }; const updates = await Promise.all([admin.from("contract_signature_envelopes").update({ title: `${prefix} A`, lock_version: current.lock_version + 1 }).eq("id", envelope.id).eq("lock_version", current.lock_version).select("id"), admin.from("contract_signature_envelopes").update({ title: `${prefix} B`, lock_version: current.lock_version + 1 }).eq("id", envelope.id).eq("lock_version", current.lock_version).select("id")]); assert(updates.filter((row) => !row.error && row.data.length === 1).length === 1, "optimistic locking não isolou concorrência"); return { oneWinner: true, staleRejected: true, assertions: 5 }; }
async function scenarioPermissions() { const envelope = await ensureEnvelope(); for (const role of ["administrador", "advogado"]) { const client = (await authenticateTestUser({ env, credentials: credentials[role], role })).client; const read = await client.from("contract_signature_envelopes").select("id").eq("id", envelope.id); assert(!read.error && read.data.length === 1, `leitura negada:${role}`); } for (const role of ["assistente", "colaborador"]) { const client = (await authenticateTestUser({ env, credentials: credentials[role], role })).client; const write = await client.from("contract_signature_envelopes").update({ title: "forbidden" }).eq("id", envelope.id).select("id"); assert(Boolean(write.error) || write.data.length === 0, `escrita permitida:${role}`); } const other = (await authenticateTestUser({ env, credentials: credentials.other, role: "outro_tenant" })).client; const cross = await other.from("contract_signature_envelopes").select("id").eq("id", envelope.id); assert(!cross.error && cross.data.length === 0, "tenant cruzado exposto"); const orphan = (await authenticateTestUser({ env, credentials: credentials.noMembership, role: "sem_membership" })).client; const none = await orphan.from("contract_signature_envelopes").select("id"); assert(Boolean(none.error) || none.data.length === 0, "sem membership acessou envelope"); return { ownerAdminLawyer: true, assistantCollaboratorBlocked: true, otherTenantBlocked: true, assertions: 12 }; }
async function scenarioRlsDataApi() { const envelope = await ensureEnvelope(); const anon = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_ANON_KEY, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } }); for (const table of ["contract_signature_envelopes", "contract_signature_signers", "contract_signature_events", "contract_signature_operations"]) { const result = await anon.from(table).select("id"); assert(Boolean(result.error) || result.data.length === 0, `anon acessou ${table}`); } const ownerClient = (await authenticateTestUser({ env, credentials: credentials.owner, role: "proprietario" })).client; const forged = await ownerClient.from("contract_signature_events").insert({ law_firm_id: tenantId, envelope_id: envelope.id, event_type: "forged", actor_user_id: crypto.randomUUID(), deduplication_key: `${prefix}-forged`, safe_metadata_json: {} }); assert(Boolean(forged.error), "evento forjado aceito"); return { anonBlocked: true, directEventForgeryBlocked: true, assertions: 9 }; }
async function scenarioStale() { const document = await ensureDocument(); const row = await admin.from("contract_documents").select("id,contract_version_id,file_hash,status").eq("id", document.id).single(); assert(!row.error && row.data.status === "completed" && row.data.contract_version_id === versionId, "documento de origem não preservado"); const envelope = await ensureEnvelope(); const current = await admin.from("contract_signature_envelopes").select("contract_version_id,document_hash,document_snapshot_json,status").eq("id", envelope.id).single(); assert(!current.error && current.data.contract_version_id === versionId && current.data.document_hash === document.file_hash, "snapshot não está congelado"); return { sourcePreserved: true, snapshotFrozen: true, assertions: 6 }; }
async function scenarioSnapshotSecurity() { const envelope = await ensureEnvelope(); const row = await admin.from("contract_signature_envelopes").select("document_snapshot_json").eq("id", envelope.id).single(); const serialized = JSON.stringify(row.data?.document_snapshot_json ?? {}); for (const sentinel of ["INTERNAL_NOTE", "INTERNAL_COST", "PRICING_MEMORY", "STORAGE_PATH", "TENANT_B_DATA", "signedUrl", "service_role", "idempotencyKey"]) assert(!serialized.includes(sentinel), `snapshot inseguro:${sentinel}`); return { sanitized: true, sensitiveFieldsAbsent: true, assertions: 10 }; }
async function scenarioResponsive() { for (const viewport of [{ width: 375, height: 812 }, { width: 390, height: 844 }, { width: 768, height: 1024 }, { width: 1440, height: 900 }]) await withOwnerPage(async (page) => { await page.goto(`${baseURL}/contratos/${contractId}/assinatura`, { waitUntil: "networkidle" }); assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `overflow:${viewport.width}`); }, viewport); return { viewports: 4, assertions: 8 }; }
async function scenarioAccessibility() { await ensureEnvelope(); await withOwnerPage(async (page) => { await page.goto(`${baseURL}/contratos/${contractId}/assinatura`, { waitUntil: "networkidle" }); const heading = await page.getByRole("heading", { name: "Envelope de assinatura" }).count(); const text = await page.getByText("Histórico de envelopes").count(); assert(heading === 1 && text === 1, "estrutura sem nome acessível"); await page.keyboard.press("Tab"); assert(await page.evaluate(() => Boolean(document.activeElement)), "foco ausente"); const focused = await page.evaluate(() => { const element = document.activeElement; if (!element) return false; const style = getComputedStyle(element); return style.outlineStyle !== "none" || style.boxShadow !== "none"; }); assert(focused, "foco visível ausente"); }); return { namedStructure: true, keyboardFocus: true, assertions: 6 }; }
async function runScenario(name, handler) { const started = Date.now(); checkpoint("scenario_started", { scenario: name }); try { const result = await Promise.race([handler(), new Promise((_, reject) => setTimeout(() => reject(new Error(`SCENARIO_TIMEOUT:${name}`)), 120000))]); const output = { scenario: name, passed: true, durationMs: Date.now() - started, ...result }; scenarioResults.push(output); checkpoint("scenario_completed", output); return output; } catch (error) { const output = { scenario: name, passed: false, durationMs: Date.now() - started, error: safe(error) }; scenarioResults.push(output); process.stderr.write(`${JSON.stringify({ step: "scenario_failed", ...output })}\n`); return output; } }
async function cleanup() { try { const pattern = `${prefix}%`; const firms = await admin.from("law_firms").select("id").like("slug", pattern); for (const firm of firms.data ?? []) { const listed = await admin.storage.from("documents").list(firm.id); const paths = (listed.data ?? []).map((file) => `${firm.id}/${file.name}`); if (paths.length) await admin.storage.from("documents").remove(paths); } const statements = ["delete from contract_signature_events where envelope_id in (select id from contract_signature_envelopes where title like $1)", "delete from contract_signature_signers where envelope_id in (select id from contract_signature_envelopes where title like $1)", "delete from contract_signature_operations where envelope_id in (select id from contract_signature_envelopes where title like $1)", "delete from contract_signature_envelopes where title like $1", "delete from contract_document_operations where contract_id in (select id from contracts where service_description like $1)", "delete from contract_documents where contract_id in (select id from contracts where service_description like $1)", "delete from contract_conversion_clauses where contract_id in (select id from contracts where service_description like $1)", "delete from contract_conversion_versions where contract_id in (select id from contracts where service_description like $1)", "delete from contracts where service_description like $1", "delete from clients where name like $1", "delete from law_firm_members where law_firm_id in (select id from law_firms where slug like $1)", "delete from law_firms where slug like $1"]; for (const statement of statements) await query(statement, [pattern]); for (const userId of users.splice(0)) await deleteFixtureUser({ env, adminClient: admin, userId }); const counts = await query("select (select count(*) from law_firm_members m join law_firms f on f.id=m.law_firm_id where f.slug like $1)::int as memberships, (select count(*) from law_firms where slug like $1)::int as tenants, (select count(*) from contracts where service_description like $1)::int as contracts, (select count(*) from contract_signature_envelopes where title like $1)::int as envelopes", [pattern]); process.stdout.write(`${JSON.stringify({ cleanup: counts.rows[0] })}\n`); } catch (error) { process.stderr.write(`${JSON.stringify({ cleanup_error: safe(error) })}\n`); } }
const scenarioHandlers = { auth_fixtures: scenarioAuthFixtures, fixtures: scenarioFixtures, source_document: scenarioSourceDocument, signer_creation: scenarioSignerCreation, prepare_transition: scenarioPrepareTransition, cancellation: scenarioCancellation, idempotency: scenarioIdempotency, concurrency: scenarioConcurrency, optimistic_locking: scenarioOptimisticLocking, permissions: scenarioPermissions, rls_data_api: scenarioRlsDataApi, stale: scenarioStale, snapshot_security: scenarioSnapshotSecurity, responsive: scenarioResponsive, accessibility: scenarioAccessibility };
async function main() { const requested = process.env.CONTRACT_SIGNATURE_TEST_SCENARIO?.trim() || "all"; const names = requested === "all" ? scenarioNames : [requested]; assert(names.every((name) => scenarioHandlers[name]), `SCENARIO_UNKNOWN:${requested}`); const requiresRuntime = names.some((name) => !["auth_fixtures", "fixtures"].includes(name)); if (requiresRuntime) { await startServer(); checkpoint("server_started", { port: 3100, runId }); } for (const name of names) await runScenario(name, scenarioHandlers[name]); const failed = scenarioResults.filter((result) => !result.passed); const summary = { passed: failed.length === 0 && (requested === "all" ? scenarioResults.length === 15 : scenarioResults.length === 1), scenario: requested, scenariosExecuted: scenarioResults.length, scenariosPassed: scenarioResults.filter((result) => result.passed).length, scenariosFailed: failed.length }; process.exitCode = summary.passed ? 0 : 1; return summary; }
let finalSummary = null;
try { acquireLock(); checkpoint("lock_acquired", { runId }); checkpoint("environment_validated", { supabase: true, runId }); await setup(); checkpoint("fixtures_created", { runId }); finalSummary = await main(); } catch (error) { process.stderr.write(`${JSON.stringify({ passed: false, error: safe(error), runId })}\n`); process.exitCode = 1; } finally { if (browser) await browser.close(); if (server && !server.killed) spawnSync("taskkill", ["/PID", String(server.pid), "/T", "/F"], { windowsHide: true, stdio: "ignore" }); await cleanup(); releaseLock(); process.stdout.write(`${JSON.stringify({ ...(finalSummary ?? { passed: false, scenario: process.env.CONTRACT_SIGNATURE_TEST_SCENARIO || "all", scenariosExecuted: scenarioResults.length, scenariosPassed: scenarioResults.filter((result) => result.passed).length, scenariosFailed: scenarioResults.filter((result) => !result.passed).length }), cleanup: true, runId })}\n`); }
