import { chromium } from "playwright";
import { createClient } from "@supabase/supabase-js";
import pg from "pg";
import crypto from "node:crypto";
import fs from "node:fs";

const env = Object.fromEntries(fs.readFileSync(".env.local", "utf8").split(/\r?\n/).filter((line) => line.includes("=")).map((line) => { const i = line.indexOf("="); return [line.slice(0, i), line.slice(i + 1).trim()]; }));
const admin = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, { auth: { autoRefreshToken: false, persistSession: false } });
const dbUrl = env.DATABASE_URL ?? "postgresql://postgres.lmfjntuofpdjojcuybkl:041052.11setembB@aws-1-us-west-2.pooler.supabase.com:5432/postgres";
const baseURL = "http://127.0.0.1:3100"; const prefix = `remaining-${Date.now()}`; const password = `P!${crypto.randomBytes(16).toString("base64url")}9a`; const ownerEmail = `${prefix}-owner@example.invalid`; const assistantEmail = `${prefix}-assistant@example.invalid`;
let tenantId; let ownerId; let assistantId; let scenarioId; let pricingVersionId; let proposalId;
const assert = (value, message) => { if (!value) throw new Error(message); };
async function login(page, email) { await page.goto(`${baseURL}/entrar`); await page.getByLabel("E-mail corporativo").fill(email); await page.getByRole("textbox", { name: "Senha" }).fill(password); await page.getByRole("button", { name: "Entrar no Painel" }).click(); await page.waitForURL((url) => !url.pathname.includes("/entrar"), { timeout: 30000 }); }
async function waitForPricingSummary(page) { await page.waitForURL(/\/propostas\/nova\?scenarioId=[^&]+&versionId=/); await page.locator("text=Carregando...").waitFor({ state: "hidden", timeout: 60000 }).catch(() => {}); await page.getByTestId("pricing-service").waitFor({ state: "visible", timeout: 60000 }); const summary = page.locator('[aria-label="Resumo do simulador"]'); await summary.waitFor({ state: "visible" }); await page.getByRole("alert").waitFor({ state: "hidden", timeout: 1000 }).catch(() => {}); for (const id of ["pricing-service", "pricing-version", "pricing-total", "pricing-entry", "pricing-installments", "pricing-recurring", "pricing-success-fee"]) assert((await page.getByTestId(id).innerText()).trim() !== "", `${id} vazio`); return summary; }
async function waitForVersionCount(proposalId, minimum, page) { const deadline = Date.now() + 30000; let actual = 0; while (Date.now() < deadline) { const result = await admin.from("commercial_proposal_versions").select("id", { count: "exact", head: true }).eq("proposal_id", proposalId); actual = result.count ?? 0; if (actual >= minimum) return; await new Promise((resolve) => setTimeout(resolve, 250)); } const status = await page.getByRole("status").allTextContents().catch(() => []); throw new Error(`versões persistidas expected >= ${minimum}, actual ${actual}; status ${status.join(" | ")}`); }
async function cleanup() { const c = new pg.Client({ connectionString: dbUrl, ssl: { rejectUnauthorized: false } }); await c.connect(); await c.query("set session_replication_role=replica"); for (const pattern of [`${prefix}%`]) { await c.query("delete from commercial_proposal_recipients where proposal_id in (select id from commercial_proposals where title like $1)", [pattern]); await c.query("delete from commercial_proposal_events where proposal_id in (select id from commercial_proposals where title like $1)", [pattern]); await c.query("delete from commercial_proposal_versions where proposal_id in (select id from commercial_proposals where title like $1)", [pattern]); await c.query("delete from commercial_proposals where title like $1", [pattern]); await c.query("delete from pricing_scenario_items where scenario_version_id in (select id from pricing_scenario_versions where pricing_scenario_id in (select id from pricing_scenarios where name like $1))", [pattern]); await c.query("delete from pricing_scenario_versions where pricing_scenario_id in (select id from pricing_scenarios where name like $1)", [pattern]); await c.query("delete from pricing_scenarios where name like $1", [pattern]); await c.query("delete from law_firm_members where law_firm_id in (select id from law_firms where slug like $1)", [pattern]); await c.query("delete from law_firms where slug like $1", [pattern]); await c.query("delete from auth.users where email like $1", [pattern]); } const result = await c.query("select (select count(*) from auth.users where email like $1) users,(select count(*) from law_firms where slug like $1) tenants,(select count(*) from commercial_proposals where title like $1) proposals,(select count(*) from pricing_scenarios where name like $1) pricing", [`${prefix}%`]); console.log(JSON.stringify({ cleanup: result.rows[0] })); await c.end(); }
try {
  const tenant = await admin.from("law_firms").insert({ name: `${prefix} Office`, slug: prefix }).select("id").single(); if (tenant.error) throw tenant.error; tenantId = tenant.data.id;
  const owner = await admin.auth.admin.createUser({ email: ownerEmail, password, email_confirm: true }); if (owner.error) throw owner.error; ownerId = owner.data.user.id; const assistant = await admin.auth.admin.createUser({ email: assistantEmail, password, email_confirm: true }); if (assistant.error) throw assistant.error; assistantId = assistant.data.user.id;
  for (const member of [{ user_id: ownerId, role: "proprietario", name: "Owner", email: ownerEmail }, { user_id: assistantId, role: "assistente", name: "Assistant", email: assistantEmail }]) { const result = await admin.from("law_firm_members").insert({ ...member, law_firm_id: tenantId, status: "ativo" }); if (result.error) throw result.error; }
  scenarioId = crypto.randomUUID(); pricingVersionId = crypto.randomUUID(); let result = await admin.from("pricing_scenarios").insert({ id: scenarioId, law_firm_id: tenantId, created_by: ownerId, name: `${prefix} Pricing`, status: "draft", active_version_id: pricingVersionId }); if (result.error) throw result.error; result = await admin.from("pricing_scenario_versions").insert({ id: pricingVersionId, law_firm_id: tenantId, pricing_scenario_id: scenarioId, created_by: ownerId, version_number: 1, scenario_type: "main", parameters: {}, calculation_result: {}, calculation_memory: { private: true }, currency: "BRL", total_amount_cents: 100000, entry_amount_cents: 20000, financed_amount_cents: 80000, installment_count: 4, success_fee_percentage_bps: 1000, monthly_fee_cents: 5000, monthly_fee_count: 3 }); if (result.error) throw result.error;
  const browser = await chromium.launch({ headless: true }); try { const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, serviceWorkers: "block" }); const page = await context.newPage(); const browserErrors = []; page.on("pageerror", (error) => browserErrors.push(error.message)); page.on("console", (message) => { if (message.type() === "error") browserErrors.push(message.text()); });
    await login(page, ownerEmail); await page.goto(`${baseURL}/simulador/${scenarioId}`); await page.getByRole("link", { name: "Criar proposta comercial" }).click(); const summary = await waitForPricingSummary(page); assert(!(await summary.innerText()).match(/memória|custo interno|margem|snapshot|NaN|undefined|null/i), "pricing expôs dado proibido"); await page.getByRole("button", { name: "Criar proposta comercial" }).click(); await page.waitForURL(/\/propostas\/[^/]+\/editar/); proposalId = page.url().match(/propostas\/([^/]+)\/editar/)?.[1]; assert(proposalId, "proposal id ausente");
    await page.getByLabel("Título").fill(`${prefix} Version A`); await page.getByRole("button", { name: /Seção/i }).click(); await page.locator("input.font-medium").last().fill(`${prefix} Section A`); await page.getByRole("button", { name: /Item/i }).click(); await page.locator('input[placeholder="Descrição"]').last().fill(`${prefix} Item A`); await page.locator('input[placeholder="Valor em centavos"]').last().fill("110000"); await page.getByLabel("Validade em dias").fill("30"); await page.getByRole("button", { name: /Salvar nova versão/i }).click(); await waitForVersionCount(proposalId, 2, page);
    await page.getByLabel("Título").fill(`${prefix} Version B`); await page.locator("input.font-medium").last().fill(`${prefix} Section B`); await page.locator('input[placeholder="Descrição"]').last().fill(`${prefix} Item B`); await page.locator('input[placeholder="Valor em centavos"]').last().fill("130000"); await page.getByLabel("Validade em dias").fill("60"); await page.getByRole("button", { name: /Salvar nova versão/i }).click(); await waitForVersionCount(proposalId, 3, page);
    const versions = await admin.from("commercial_proposal_versions").select("id, version_number").eq("proposal_id", proposalId).order("version_number"); if (versions.error) throw versions.error; assert((versions.data ?? []).length >= 3, "versões A/B não criadas"); const a = versions.data.at(-2).id; const b = versions.data.at(-1).id;
    await page.goto(`${baseURL}/propostas/${proposalId}/comparar?a=${a}&b=${b}`); await page.getByRole("combobox", { name: "Versão A" }).waitFor(); assert(page.url().includes(`a=${a}&b=${b}`), "URL A/B ausente"); await page.getByRole("region", { name: "Resultado da comparação" }).waitFor({ state: "visible" }); const comparison = await page.getByRole("region", { name: "Resultado da comparação" }).innerText(); assert(/Version A|Version B|Delta monetário|Seções|Itens/.test(comparison), "comparação estruturada incompleta"); assert(!/NaN|undefined|JSON.stringify|\{.*\}/i.test(comparison), "comparação expôs valor inválido ou JSON bruto"); await page.reload(); assert(page.url().includes(`a=${a}&b=${b}`), "reload perdeu seleção");
    await page.goto(`${baseURL}/propostas/${proposalId}`); const archive = page.getByRole("button", { name: /Arquivar/i }); await archive.click(); const dialog = page.getByRole("dialog"); await dialog.waitFor({ state: "visible" }); const activeInside = await dialog.evaluate((node) => node.contains(document.activeElement)); assert(activeInside, "foco não entrou no dialog"); await page.keyboard.press("Escape"); await dialog.waitFor({ state: "hidden" }); await archive.click(); const stableDialog = page.getByRole("dialog"); await stableDialog.waitFor({ state: "visible" }); await stableDialog.getByRole("button", { name: "Arquivar" }).click(); await page.waitForTimeout(1000); const archived = await admin.from("commercial_proposals").select("status, active_version_id").eq("id", proposalId).single(); assert(archived.data?.status === "archived", `status esperado archived, real ${archived.data?.status}`); const archivedEvent = await admin.from("commercial_proposal_events").select("id", { count: "exact", head: true }).eq("proposal_id", proposalId).eq("event_type", "proposal_archived"); assert((archivedEvent.count ?? 0) === 1, `eventos archived esperados 1, reais ${archivedEvent.count ?? 0}`);
    await page.goto(`${baseURL}/propostas`); await page.locator("select").selectOption("archived"); assert((await page.locator("body").innerText()).includes(prefix), "arquivada não aparece no filtro"); await page.goto(`${baseURL}/propostas/${proposalId}`); await page.reload(); await page.getByRole("button", { name: /Restaurar/i }).click(); await page.getByRole("dialog").getByRole("button", { name: "Restaurar" }).click(); await page.waitForTimeout(1000); const restored = await admin.from("commercial_proposals").select("status, active_version_id").eq("id", proposalId).single(); assert(restored.data?.status === "draft", `status esperado draft, real ${restored.data?.status}`); const restoredEvent = await admin.from("commercial_proposal_events").select("id", { count: "exact", head: true }).eq("proposal_id", proposalId).eq("event_type", "proposal_restored"); assert((restoredEvent.count ?? 0) === 1, `eventos restored esperados 1, reais ${restoredEvent.count ?? 0}`); assert(restored.data?.active_version_id === archived.data?.active_version_id, "activeVersionId não preservado");
    const assistantContext = await browser.newContext({ viewport: { width: 1440, height: 900 }, serviceWorkers: "block" }); const assistantPage = await assistantContext.newPage(); await assistantContext.clearCookies(); await login(assistantPage, assistantEmail); await assistantPage.goto(`${baseURL}/propostas`); assert(!(await assistantPage.getByRole("link", { name: /Nova proposta/i }).count()), "assistente vê Nova proposta"); const assistantNovaResponse = await assistantPage.goto(`${baseURL}/propostas/nova`); console.log(JSON.stringify({ assistantNovaStatus: assistantNovaResponse?.status(), assistantNovaUrl: assistantPage.url(), assistantNovaLocation: assistantNovaResponse?.headers()["location"] ?? null })); assert(!assistantPage.url().includes("/propostas/nova"), `nova proposta não bloqueada server-side: ${assistantPage.url()}`); await assistantPage.goto(`${baseURL}/propostas/${proposalId}/editar`); assert(!assistantPage.url().endsWith("/editar"), "editor não bloqueado server-side"); const restrictedText = await assistantPage.locator("body").innerText(); assert(!/internalNotes|pricingSnapshot|pricing_snapshot_json|inputHash|idempotencyKey|memória de cálculo|custo interno|margem/i.test(restrictedText), "payload restrito expôs dado sensível"); await assistantContext.close(); assert(browserErrors.length === 0, `erros do navegador: ${browserErrors.join(" | ")}`);
    console.log(JSON.stringify({ passed: true, comparison: true, archiveRestore: true, assistant: true, accessibility: true }));
  } finally { await browser.close(); }
} catch (error) { console.error(JSON.stringify({ passed: false, message: error?.stack ?? String(error) })); process.exitCode = 1; } finally { await cleanup(); }
