import { createClient } from '@supabase/supabase-js';
import crypto from 'node:crypto';
import { assertAllowedProposalsTestEnvironment } from './proposals-test-environment.mjs';

const env = assertAllowedProposalsTestEnvironment();
const admin = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, { auth: { autoRefreshToken: false, persistSession: false } });
const anonKey = env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const prefix = `proposal-application-${Date.now()}`;
const password = `P!${crypto.randomBytes(24).toString('base64url')}9a`;
const users = [], tenants = [], proposals = [], pricing = [];
const fail = (message) => { throw new Error(message); };
const ok = (value, message) => { if (!value) fail(message); };
const rpc = (user, name, args) => user.client.rpc(name, args);
const makeClient = () => createClient(env.NEXT_PUBLIC_SUPABASE_URL, anonKey, { auth: { autoRefreshToken: false, persistSession: false } });
async function user(role, tenantId, label) { const email = `${prefix}-${label}@example.invalid`; const created = await admin.auth.admin.createUser({ email, password, email_confirm: true }); if (created.error) throw created.error; users.push(created.data.user.id); if (tenantId) { const member = await admin.from('law_firm_members').insert({ user_id: created.data.user.id, law_firm_id: tenantId, name: label, email, role, status: 'ativo' }); if (member.error) throw member.error; } const client = makeClient(); const login = await client.auth.signInWithPassword({ email, password }); if (login.error) throw login.error; return { id: created.data.user.id, client, role, tenantId }; }
async function detail(actor, id) { const result = await rpc(actor, 'get_commercial_proposal_secure', { p_proposal_id: id }); if (result.error) throw result.error; return result.data?.[0]; }
async function main() {
  for (const suffix of ['a', 'b']) { const created = await admin.from('law_firms').insert({ name: `${prefix}-${suffix}`, slug: `${prefix}-${suffix}` }).select('id').single(); if (created.error) throw created.error; tenants.push(created.data.id); }
  const owner = await user('proprietario', tenants[0], 'owner'); const lawyer = await user('advogado', tenants[0], 'lawyer'); const assistant = await user('assistente', tenants[0], 'assistant'); const collaborator = await user('colaborador', tenants[0], 'collaborator'); const otherTenant = await user('proprietario', tenants[1], 'other'); const noMembership = await user(null, null, 'none');
  const anonymous = makeClient();
  const created = await rpc(owner, 'create_commercial_proposal_manual', { p_title: `${prefix}-base`, p_currency: 'BRL', p_validity_days: 30, p_idempotency_key: `${prefix}-manual` }); ok(!created.error && created.data?.[0]?.proposal_id, `manual: ${created.error?.message}`); const proposalId = created.data[0].proposal_id; proposals.push(proposalId);
  const second = await rpc(owner, 'create_commercial_proposal_manual', { p_title: `${prefix}-second`, p_currency: 'BRL', p_validity_days: 30, p_idempotency_key: `${prefix}-second` }); ok(!second.error, `second: ${second.error?.message}`); proposals.push(second.data[0].proposal_id);
  const base = await detail(owner, proposalId); const draft = { title: `${prefix}-version-2`, currency: 'BRL', validityDays: 45, summary: { currency: 'BRL', subtotalCents: 10000, discountCents: 1000, totalCents: 9000, entryAmountCents: 1000, installmentCount: 4, installmentAmountCents: 2000, recurringAmountCents: 0, recurringMonths: 0, successFeeBps: 0 }, paymentTerms: { methods: ['pix'], installments: 4 }, sections: [{ sectionType: 'fees', title: 'Honorarios', bodyMarkdown: 'Escopo', orderIndex: 0, isRequired: true }, { sectionType: 'validity', title: 'Validade', bodyMarkdown: '45 dias', orderIndex: 1, isRequired: true }], items: [{ itemType: 'service', description: 'Servico juridico', quantity: 1, unitAmountCents: 9000, totalAmountCents: 9000, isOptional: false, isIncluded: true, orderIndex: 0, metadata: {} }], contentHash: crypto.createHash('sha256').update(`${prefix}-version-2`).digest('hex') };
  const version = await rpc(owner, 'create_commercial_proposal_version', { p_proposal_id: proposalId, p_expected_updated_at: base.updated_at, p_draft: draft }); ok(!version.error && version.data?.[0]?.version_number === 2, `version: ${version.error?.message}`); const versionId = version.data[0].version_id;
  const sections = await admin.from('commercial_proposal_sections').select('id').eq('proposal_version_id', versionId); const items = await admin.from('commercial_proposal_items').select('id').eq('proposal_version_id', versionId); ok(sections.data?.length === 2 && items.data?.length === 1, 'version children not persisted');
  const afterVersion = await detail(owner, proposalId); const activated = await rpc(owner, 'activate_commercial_proposal_version', { p_proposal_id: proposalId, p_version_id: versionId, p_expected_updated_at: afterVersion.updated_at }); ok(!activated.error, `activate: ${activated.error?.message}`); const active = await detail(owner, proposalId); ok(active.active_version_id === versionId, 'active version mismatch');
  const wrongActivation = await rpc(owner, 'activate_commercial_proposal_version', { p_proposal_id: proposalId, p_version_id: second.data[0].version_id, p_expected_updated_at: active.updated_at }); ok(Boolean(wrongActivation.error), 'foreign version activation was not blocked');
  const immutable = await owner.client.from('commercial_proposal_versions').update({ title: 'tampered' }).eq('id', versionId); ok(Boolean(immutable.error) || immutable.data?.length === 0, 'version update was allowed'); const deleted = await owner.client.from('commercial_proposal_versions').delete().eq('id', versionId); ok(Boolean(deleted.error) || deleted.data?.length === 0, 'version delete was allowed');
  const incomplete = await rpc(owner, 'transition_commercial_proposal', { p_proposal_id: second.data[0].proposal_id, p_to: 'ready', p_expected_updated_at: (await detail(owner, second.data[0].proposal_id)).updated_at }); ok(Boolean(incomplete.error) && incomplete.error.message.includes('PROPOSAL_NOT_READY'), 'incomplete readiness was not blocked');
  const ready = await rpc(owner, 'transition_commercial_proposal', { p_proposal_id: proposalId, p_to: 'ready', p_expected_updated_at: (await detail(owner, proposalId)).updated_at }); ok(!ready.error, `ready: ${ready.error?.message}`); let current = await detail(owner, proposalId); const back = await rpc(owner, 'transition_commercial_proposal', { p_proposal_id: proposalId, p_to: 'draft', p_expected_updated_at: current.updated_at }); ok(!back.error, `ready to draft: ${back.error?.message}`); current = await detail(owner, proposalId); const cancelled = await rpc(owner, 'transition_commercial_proposal', { p_proposal_id: proposalId, p_to: 'cancelled', p_expected_updated_at: current.updated_at }); ok(!cancelled.error, `cancel: ${cancelled.error?.message}`);
  const recipient = await rpc(owner, 'upsert_commercial_proposal_recipient', { p_proposal_id: proposalId, p_recipient: { recipientType: 'client', name: 'Cliente', email: 'cliente@example.invalid', phone: '+55 (11) 99999-9999', isPrimary: true } }); ok(!recipient.error, `recipient: ${recipient.error?.message}`); const recipientRows = await rpc(owner, 'get_commercial_proposal_recipients_secure', { p_proposal_id: proposalId }); ok(!recipient.error && recipientRows.data?.length === 1 && recipientRows.data[0].is_primary, 'recipient not persisted'); const secondRecipient = await rpc(owner, 'upsert_commercial_proposal_recipient', { p_proposal_id: proposalId, p_recipient: { recipientType: 'contact', name: 'Contato', email: 'contato@example.invalid', phone: '+55 11 98888-8888', isPrimary: false } }); ok(!secondRecipient.error, `second recipient: ${secondRecipient.error?.message}`); const updatedRecipient = await rpc(owner, 'upsert_commercial_proposal_recipient', { p_proposal_id: proposalId, p_recipient: { id: secondRecipient.data[0].recipient_id, recipientType: 'contact', name: 'Contato atualizado', email: 'novo@example.invalid', phone: '+55 11 97777-7777', isPrimary: true } }); ok(!updatedRecipient.error, `recipient update: ${updatedRecipient.error?.message}`); const afterRecipients = await rpc(owner, 'get_commercial_proposal_recipients_secure', { p_proposal_id: proposalId }); ok(afterRecipients.data?.filter((row) => row.is_primary).length === 1, 'more than one primary recipient'); const removed = await rpc(owner, 'remove_commercial_proposal_recipient', { p_proposal_id: proposalId, p_recipient_id: recipient.data[0].recipient_id }); ok(!removed.error, `recipient removal: ${removed.error?.message}`);
  for (const actor of [assistant, collaborator, otherTenant, noMembership]) { const denied = await rpc(actor, 'create_commercial_proposal_version', { p_proposal_id: proposalId, p_expected_updated_at: current.updated_at, p_draft: draft }); ok(Boolean(denied.error), `${actor.role ?? 'none'} version mutation was allowed`); }
  for (const actor of [anonymous, noMembership.client, otherTenant.client]) { const query = await actor.rpc('get_commercial_proposal_secure', { p_proposal_id: proposalId }); ok(Boolean(query.error) || !query.data?.length, 'unauthorized detail leaked'); }
  const events = await rpc(owner, 'get_commercial_proposal_events_secure', { p_proposal_id: proposalId }); ok(!events.error, `events: ${events.error?.message}`); ok(events.data.every((event) => !JSON.stringify(event.metadata).match(/internal|token|sqlstate|stack/i)), 'sensitive event metadata leaked');
  console.log(JSON.stringify({ passed: true, users: users.length, tenants: tenants.length, proposals: proposals.length, version: versionId, events: events.data.length }));
}
try { await main(); } catch (error) { console.error(JSON.stringify({ passed: false, message: error.message })); process.exitCode = 1; } finally {
  for (const id of proposals) { await admin.from('commercial_proposal_recipients').delete().eq('proposal_id', id); await admin.from('commercial_proposal_events').delete().eq('proposal_id', id); await admin.from('commercial_proposal_versions').delete().eq('proposal_id', id); await admin.from('commercial_proposals').delete().eq('id', id); }
  for (const id of tenants) await admin.from('law_firms').delete().eq('id', id);
  for (const id of users) await admin.auth.admin.deleteUser(id);
  const remainingUsers = await admin.from('law_firm_members').select('id', { count: 'exact', head: true }).like('email', `${prefix}%`); const remainingTenants = await admin.from('law_firms').select('id', { count: 'exact', head: true }).like('slug', `${prefix}%`); const remainingProposals = await admin.from('commercial_proposals').select('id', { count: 'exact', head: true }).like('title', `${prefix}%`); console.log(JSON.stringify({ cleanup: { users: remainingUsers.count ?? 0, tenants: remainingTenants.count ?? 0, proposals: remainingProposals.count ?? 0 } }));
}
