create or replace function public.duplicate_commercial_proposal(p_source_proposal_id uuid,p_title text default null,p_copy_recipients boolean default false,p_idempotency_key text default null,p_input_hash text default null)
returns table(proposal_id uuid,version_id uuid,idempotent boolean,error_code text) language plpgsql security definer set search_path=public,extensions as $$
declare a uuid := (select auth.uid()); f uuid; sp public.commercial_proposals%rowtype; sv public.commercial_proposal_versions%rowtype; p uuid; v uuid; op public.commercial_proposal_idempotency_operations%rowtype; s record; i record;
begin
  select m.law_firm_id into f from public.law_firm_members m where m.user_id=a and m.status='ativo' order by m.created_at limit 1; if f is null or not public.has_law_firm_role(f,array['proprietario','administrador','advogado']::public.member_role[]) then raise exception 'PROPOSAL_PERMISSION_DENIED' using errcode='42501'; end if;
  select cp.* into sp from public.commercial_proposals cp where cp.id=p_source_proposal_id and cp.law_firm_id=f; if sp.id is null then raise exception 'PROPOSAL_NOT_FOUND' using errcode='P0002'; end if;
  select cv.* into sv from public.commercial_proposal_versions cv where cv.id=sp.active_version_id and cv.proposal_id=sp.id and cv.law_firm_id=f; if sv.id is null then raise exception 'PROPOSAL_VERSION_NOT_FOUND' using errcode='P0002'; end if;
  insert into public.commercial_proposal_idempotency_operations(law_firm_id,actor_id,source_pricing_version_id,operation_type,idempotency_key,input_hash,status) values(f,a,sp.source_pricing_version_id,'duplicate',p_idempotency_key,p_input_hash,'processing') on conflict (law_firm_id,actor_id,operation_type,idempotency_key) do nothing;
  select io.* into op from public.commercial_proposal_idempotency_operations io where io.law_firm_id=f and io.actor_id=a and io.operation_type='duplicate' and io.idempotency_key=p_idempotency_key;
  if op.input_hash <> p_input_hash then raise exception 'PROPOSAL_IDEMPOTENCY_CONFLICT' using errcode='P0001'; end if;
  if op.status='completed' then return query select op.result_proposal_id,op.result_version_id,true,null::text; return; end if;
  insert into public.commercial_proposals(law_firm_id,created_by,updated_by,client_id,contact_id,legal_case_id,source_pricing_scenario_id,source_pricing_version_id,origin_type,status,title,internal_reference,currency,valid_until,internal_notes) values(f,a,a,sp.client_id,sp.contact_id,sp.legal_case_id,sp.source_pricing_scenario_id,sp.source_pricing_version_id,'duplicated','draft',coalesce(nullif(btrim(p_title),''),sp.title),sp.internal_reference,sp.currency,sp.valid_until,sp.internal_notes) returning id into p;
  insert into public.commercial_proposal_versions(law_firm_id,proposal_id,version_number,schema_version,pricing_engine_version,title,introduction,conclusion,currency,subtotal_cents,discount_cents,total_cents,entry_amount_cents,installment_count,installment_amount_cents,recurring_amount_cents,recurring_months,success_fee_bps,validity_days,payment_terms_json,commercial_summary_json,pricing_snapshot_json,content_hash,pricing_snapshot_hash,created_by) values(f,p,1,sv.schema_version,sv.pricing_engine_version,coalesce(nullif(btrim(p_title),''),sv.title),sv.introduction,sv.conclusion,sv.currency,sv.subtotal_cents,sv.discount_cents,sv.total_cents,sv.entry_amount_cents,sv.installment_count,sv.installment_amount_cents,sv.recurring_amount_cents,sv.recurring_months,sv.success_fee_bps,sv.validity_days,sv.payment_terms_json,sv.commercial_summary_json,sv.pricing_snapshot_json,p_input_hash,sv.pricing_snapshot_hash,a) returning id into v;
  for s in select ps.* from public.commercial_proposal_sections ps where ps.proposal_version_id=sv.id loop insert into public.commercial_proposal_sections(law_firm_id,proposal_version_id,section_type,title,body_markdown,order_index,is_required) values(f,v,s.section_type,s.title,s.body_markdown,s.order_index,s.is_required); end loop;
  for i in select pi.* from public.commercial_proposal_items pi where pi.proposal_version_id=sv.id loop insert into public.commercial_proposal_items(law_firm_id,proposal_version_id,source_pricing_item_id,item_type,description,quantity,unit_amount_cents,total_amount_cents,is_optional,is_included,order_index,metadata) values(f,v,i.source_pricing_item_id,i.item_type,i.description,i.quantity,i.unit_amount_cents,i.total_amount_cents,i.is_optional,i.is_included,i.order_index,i.metadata); end loop;
  update public.commercial_proposals cp set active_version_id=v where cp.id=p;
  insert into public.commercial_proposal_events(law_firm_id,proposal_id,proposal_version_id,actor_id,event_type,metadata) values(f,p,v,a,'proposal_duplicated',jsonb_build_object('sourceProposalId',sp.id)),(f,p,v,a,'proposal_version_created','{}'::jsonb);
  update public.commercial_proposal_idempotency_operations io set proposal_id=p,result_proposal_id=p,result_version_id=v,status='completed',completed_at=now() where io.id=op.id;
  return query select p,v,false,null::text;
exception when others then if SQLERRM in ('PROPOSAL_PERMISSION_DENIED','PROPOSAL_NOT_FOUND','PROPOSAL_VERSION_NOT_FOUND','PROPOSAL_IDEMPOTENCY_CONFLICT') then raise; end if; raise exception 'PROPOSAL_PERSISTENCE_ERROR' using errcode='P0001'; end $$;
