import Link from "next/link";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { createPrivacyRequestAction } from "./actions";

export default async function PrivacyRequestPage({ searchParams }: { searchParams: Promise<{ erro?: string; enviado?: string }> }) {
  const params = await searchParams;
  return <main className="min-h-screen bg-muted/30 px-4 py-10"><div className="mx-auto max-w-xl space-y-6"><div><Link href="/privacidade" className="text-sm underline">Política de Privacidade</Link><h1 className="mt-4 text-3xl font-semibold tracking-tight">Solicitação do titular</h1><p className="mt-2 text-sm text-muted-foreground">Envie uma solicitação ao escritório responsável pelo tratamento dos seus dados.</p></div>{params.enviado ? <Card className="rounded-lg border-[var(--chart-2)]/30 bg-[var(--chart-2)]/5"><CardContent className="p-4 text-sm">Solicitação registrada. O escritório analisará o pedido dentro do prazo aplicável.</CardContent></Card> : null}{params.erro ? <Card className="rounded-lg border-destructive/30 bg-destructive/5"><CardContent className="p-4 text-sm text-destructive">Não foi possível registrar a solicitação. Confira os dados informados.</CardContent></Card> : null}<Card className="rounded-lg"><CardHeader><CardTitle>Registrar pedido</CardTitle><CardDescription>Informe o identificador do escritório em que seus dados são tratados.</CardDescription></CardHeader><CardContent><form action={createPrivacyRequestAction} className="space-y-4"><div className="space-y-2"><Label htmlFor="officeSlug">Identificador do escritório</Label><Input id="officeSlug" name="officeSlug" placeholder="ex.: almeida-ferraz" required /></div><div className="space-y-2"><Label htmlFor="name">Nome</Label><Input id="name" name="name" required /></div><div className="space-y-2"><Label htmlFor="email">E-mail</Label><Input id="email" name="email" type="email" required /></div><div className="space-y-2"><Label htmlFor="type">Tipo de solicitação</Label><select id="type" name="type" required className="h-9 w-full rounded-lg border border-input bg-background px-2.5 text-sm"><option value="informacao">Informações sobre o tratamento</option><option value="acesso">Acesso aos dados</option><option value="correcao">Correção</option><option value="portabilidade">Portabilidade</option><option value="anonimizacao">Anonimização</option><option value="eliminacao">Eliminação</option><option value="revogacao">Revogação de consentimento</option></select></div><div className="space-y-2"><Label htmlFor="details">Detalhes</Label><textarea id="details" name="details" rows={4} className="w-full rounded-lg border border-input bg-background px-2.5 py-2 text-sm" placeholder="Explique o pedido e informe dados que ajudem na identificação." /></div><button type="submit" className="h-9 w-full rounded-lg bg-primary px-3 text-sm font-medium text-primary-foreground">Enviar solicitação</button></form></CardContent></Card></div></main>;
}
