import Link from "next/link";
import { AppShell } from "@/components/layout/app-shell";
import { PageHeader } from "@/components/page-header";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getAppContext } from "@/lib/auth/context";
import { can } from "@/lib/auth/permissions";
import { formatDateTime } from "@/lib/formatters";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { updatePrivacyRequestAction } from "./actions";

export default async function PrivacyAdminPage({ searchParams }: { searchParams: Promise<{ erro?: string; salvo?: string }> }) {
  const context = await getAppContext(); const params = await searchParams;
  if (context.status !== "ready" || !context.member || !context.lawFirm) return <AppShell memberName={null}><PageHeader title="Privacidade e LGPD" description="Solicitações de titulares e evidências de tratamento." /><Card><CardContent className="p-6"><Link href="/entrar" className="underline">Entrar</Link></CardContent></Card></AppShell>;
  if (!can(context.member.role, "configuracoes.administrar")) return <AppShell memberName={context.member.name}><PageHeader title="Privacidade e LGPD" description="Solicitações de titulares e evidências de tratamento." /><Card><CardContent className="p-6 text-sm text-muted-foreground">Você não tem permissão para administrar solicitações LGPD.</CardContent></Card></AppShell>;
  const supabase = await getSupabaseServerClient();
  const result = supabase ? await (supabase as unknown as { from(table: string): { select(columns: string): { eq(column: string, value: string): { order(column: string, options: { ascending: boolean }): Promise<{ data: unknown[] | null }> } } } }).from("privacy_requests").select("id, requester_name, requester_email, request_type, details, status, due_at, resolution_notes, created_at").eq("law_firm_id", context.lawFirm.id).order("created_at", { ascending: false }) : { data: [] as unknown[] };
  const requests = (result.data ?? []) as Array<{ id: string; requester_name: string; requester_email: string; request_type: string; details: string | null; status: string; due_at: string; resolution_notes: string | null; created_at: string }>;
  return <AppShell memberName={context.member.name}><div className="space-y-6"><PageHeader title="Privacidade e LGPD" description="Controle solicitações de titulares, prazos e evidências de tratamento." /><div className="flex gap-3 text-sm"><Link href="/privacidade" className="underline">Ver política pública</Link><Link href="/configuracoes" className="underline">Voltar às configurações</Link></div>{params.erro ? <Card className="border-destructive/30 bg-destructive/5 rounded-lg"><CardContent className="p-4 text-sm text-destructive">Não foi possível salvar a solicitação.</CardContent></Card> : null}{params.salvo ? <Card className="border-[var(--chart-2)]/30 bg-[var(--chart-2)]/5 rounded-lg"><CardContent className="p-4 text-sm">Solicitação atualizada.</CardContent></Card> : null}<Card className="rounded-lg"><CardHeader><CardTitle>Solicitações recebidas</CardTitle><CardDescription>O prazo inicial é registrado por 15 dias; confirme a obrigação aplicável ao caso concreto.</CardDescription></CardHeader><CardContent>{requests.length === 0 ? <p className="text-sm text-muted-foreground">Nenhuma solicitação registrada.</p> : <div className="space-y-4">{requests.map((request) => <div key={request.id} className="rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-medium">{request.requester_name}</p><p className="text-sm text-muted-foreground">{request.requester_email} · {request.request_type}</p><p className="mt-1 text-xs text-muted-foreground">Recebida em {formatDateTime(request.created_at)} · prazo registrado: {formatDateTime(request.due_at)}</p></div><span className="text-sm font-medium">{request.status}</span></div>{request.details ? <p className="mt-3 text-sm">{request.details}</p> : null}<form action={updatePrivacyRequestAction} className="mt-4 grid gap-3 md:grid-cols-[180px_1fr_auto]"><input type="hidden" name="requestId" value={request.id} /><select name="status" defaultValue={request.status} className="h-9 rounded-lg border border-input bg-background px-2.5 text-sm"><option value="recebida">Recebida</option><option value="em_analise">Em análise</option><option value="atendida">Atendida</option><option value="negada">Negada</option><option value="cancelada">Cancelada</option></select><div className="space-y-1"><Label htmlFor={`notes-${request.id}`}>Observação de resolução</Label><Input id={`notes-${request.id}`} name="notes" defaultValue={request.resolution_notes ?? ""} /></div><button type="submit" className="h-9 self-end rounded-lg bg-primary px-3 text-sm font-medium text-primary-foreground">Salvar</button></form></div>)}</div>}</CardContent></Card></div></AppShell>;
}
